# Inspecting the raw Pew files (.sav)

We want to combine 9 Pew Research Center surveys and use Trump approval from them as an external resource for the analysis.

The files are in SPSS format (.sav). We do not have SPSS, so we read them in Jupyter with the pyreadstat library.

## 0. Setup

In [1]:
import re
from pathlib import Path

import pandas as pd
import pyreadstat
from IPython.display import display

pd.set_option("display.max_columns", None)
pd.set_option('display.max_colwidth', None)

ROOT = Path.cwd()
while not (ROOT / "data").exists() and ROOT != ROOT.parent:
    ROOT = ROOT.parent
SURVEY_DIR = ROOT / "data" / "raw" / "survey"
print("Project root:", ROOT)
print("Survey folder:", SURVEY_DIR)

Project root: D:\могилянка\обсус\reddit_project
Survey folder: D:\могилянка\обсус\reddit_project\data\raw\survey

## 1. Find and open all .sav files

The zip archives are extracted into `data/raw/survey`.

In [2]:
SAV_NAMES = {
    "Feb17 public.sav": "Feb17",
    "Apr17 public.sav": "Apr17",
    "Typology 17 public.sav": "Typology17",
    "Jan18 public.sav": "Jan18",
    "March18 public.sav": "Mar18",
    "May18 public.sav": "May18",
    "June18 public.sav": "Jun18",
    "ATP W161.sav": "W161",
    "ATP W167.sav": "W167",
}
WAVE_ORDER = list(SAV_NAMES.values())
phone = [w for w in WAVE_ORDER if w not in ("W161", "W167")]   # 2017-2018 telephone surveys
atp = ["W161", "W167"]                                         # 2025 American Trends Panel waves

found = {}
for p in sorted(SURVEY_DIR.rglob("*.sav")):
    wave = SAV_NAMES.get(p.name)
    if wave and wave not in found:
        found[wave] = p

missing = [w for w in WAVE_ORDER if w not in found]
assert not missing, f"No .sav found for waves: {missing}. Check that the zips are extracted into {SURVEY_DIR}"

pd.DataFrame({
    "wave_id": WAVE_ORDER,
    "file (relative to data/raw/survey)": [str(found[w].relative_to(SURVEY_DIR)) for w in WAVE_ORDER],
    "size, KB": [round(found[w].stat().st_size / 1024) for w in WAVE_ORDER],
}).set_index("wave_id")

                  file (relative to data/raw/survey)  size, KB
wave_id
Feb17                  Feb17-public\Feb17 public.sav       512
Apr17       Apr17-public-4.3-update\Apr17 public.sav       388
Typology17        Typology-17\Typology 17 public.sav      1063
Jan18                         Jan18\Jan18 public.sav       390
Mar18                     March18\March18 public.sav       299
May18                         May18\May18 public.sav       293
Jun18                       June18\June18 public.sav       419
W161              W161_Feb25\W161_Feb25\ATP W161.sav      1107
W167              W167_Apr25\W167_Apr25\ATP W167.sav       899

In [3]:
surveys, metas, labels = {}, {}, {}
for wave in WAVE_ORDER:
    df, meta = pyreadstat.read_sav(found[wave], apply_value_formats=False)
    surveys[wave] = df
    metas[wave] = meta
    labels[wave] = dict(zip(meta.column_names, meta.column_labels))  # variable name -> question text

def vlabels(wave, var):
    return metas[wave].variable_value_labels.get(var, {})

pd.DataFrame({w: {"rows (respondents)": len(d), "columns (variables)": d.shape[1]} for w, d in surveys.items()}).T

            rows (respondents)  columns (variables)
Feb17                     1503                  127
Apr17                     1501                  178
Typology17                5009                  163
Jan18                     1503                  168
Mar18                     1466                  108
May18                     1503                  123
Jun18                     2002                  130
W161                      5086                  144
W167                      3589                  170

The tables already have different widths, from 108 to 178 columns. These are different questionnaires.

## 2. Looking at all 9 tables

In [4]:
for w in WAVE_ORDER:
    print(f"{w}: {surveys[w].shape[0]} rows x {surveys[w].shape[1]} columns")
    display(surveys[w].head(5))

Feb17: 1503 rows x 127 columns

,psraid,sample,int_date,fcall,version,attempts,refusal,ilang,cregion,state,density,sstate,form,stimes,igender,irace,llitext0,susr,usr,scregion,qs1,q1,q1a,q2,q5af1,q5bf1,q5cf1,q5df1,q6af2,q6bf2,q6cf2,q6df2,q10a,q10b,q15af1,q15b,q15cf2,q15df1,q15ef1,q15ff1,q15gf2,q15hf2,q15if2,q16,q19,q35,q36,q37,q39,q43,q44,q45,q45vb,q45oem1,q45oem2,q45oem3,q52,q53,q54,q55,q61a,q61b,q61c,q61d,q61e,q62f1,q63f1,q64f2,q65,q66,q68f1,q69f2,q70f1,q71f2,q74,q75,q81,q82,q84a,q84bf1,q84cf1,q84df1,q84ef2,q84ff2,q84gf2,q88,q90f1,q91f2,sex,age,gen5,educ2,hisp,adults,racethn,racethn2,birth_hisp,citizen,child,relig,chr,born,attend,q92,q92a,income,reg,party,partyln,partysum,partyideo,q93,q94,ideo,hh1,hh3,ql1,ql1a,qc1,money2,money3,iphoneuse,hphoneuse,ll,cp,cellweight,weight
0,100008.0,1.0,21017.0,170207.0,2.0,4.0,0.0,1.0,2.0,17.0,4.0,17.0,2.0,4.0,2.0,1.0,1.0,S,S,2.0,NaN,2.0,1.0,2.0,NaN,NaN,NaN,NaN,2.0,2.0,1.0,1.0,2.0,1.0,NaN,2.0,2.0,NaN,NaN,NaN,2.0,2.0,1.0,3.0,4.0,1.0,2.0,3.0,1.0,1.0,1.0,NaN,,NaN,NaN,NaN,2.0,2.0,2.0,3.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,2.0,1.0,2.0,NaN,1.0,NaN,2.0,1.0,NaN,1.0,3.0,4.0,NaN,NaN,NaN,2.0,4.0,2.0,4.0,NaN,1.0,2.0,80.0,2.0,6.0,2.0,2.0,1.0,1.0,NaN,NaN,0.0,1.0,NaN,2.0,2.0,2.0,NaN,9.0,1.0,3.0,2.0,2.0,3.0,NaN,1.0,4.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,2.0,2.0,1.0,1.0,NaN,1.733333
1,100019.0,1.0,21217.0,170207.0,2.0,4.0,1.0,1.0,3.0,37.0,4.0,37.0,1.0,4.0,1.0,3.0,1.0,U,U,3.0,NaN,2.0,1.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,NaN,1.0,2.0,2.0,NaN,NaN,NaN,4.0,4.0,1.0,2.0,4.0,3.0,2.0,2.0,1.0,I DON'T THINK HE'S THE BEST MAN FOR THE JOB,11.0,NaN,NaN,2.0,2.0,3.0,3.0,1.0,1.0,1.0,1.0,1.0,3.0,3.0,NaN,1.0,2.0,2.0,NaN,1.0,NaN,1.0,NaN,1.0,1.0,4.0,4.0,4.0,2.0,NaN,NaN,NaN,3.0,3.0,NaN,2.0,70.0,3.0,8.0,2.0,2.0,1.0,1.0,NaN,NaN,0.0,5.0,NaN,NaN,3.0,2.0,NaN,7.0,1.0,2.0,NaN,2.0,4.0,NaN,2.0,3.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,2.0,2.0,1.0,1.0,NaN,1.500000
2,100020.0,1.0,21217.0,170207.0,2.0,4.0,1.0,1.0,1.0,36.0,4.0,36.0,1.0,4.0,2.0,3.0,2.0,S,S,1.0,NaN,2.0,1.0,2.0,2.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,NaN,2.0,1.0,2.0,NaN,NaN,NaN,3.0,3.0,1.0,2.0,4.0,3.0,1.0,2.0,1.0,I THINK HE IS TOO MUCH TIES WITH LARGE CORPORATIONS,41.0,NaN,NaN,2.0,2.0,3.0,3.0,1.0,1.0,1.0,1.0,1.0,2.0,3.0,NaN,1.0,2.0,2.0,NaN,1.0,NaN,1.0,NaN,1.0,1.0,4.0,2.0,4.0,2.0,NaN,NaN,NaN,3.0,2.0,NaN,2.0,69.0,3.0,8.0,2.0,2.0,1.0,1.0,NaN,NaN,0.0,2.0,NaN,2.0,2.0,1.0,3.0,8.0,1.0,3.0,2.0,2.0,3.0,NaN,2.0,4.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,2.0,2.0,1.0,1.0,NaN,1.533333
3,100021.0,1.0,20717.0,170207.0,1.0,1.0,0.0,1.0,2.0,27.0,5.0,27.0,2.0,1.0,2.0,4.0,1.0,U,U,2.0,NaN,1.0,2.0,1.0,NaN,NaN,NaN,NaN,1.0,1.0,2.0,2.0,1.0,2.0,NaN,1.0,1.0,NaN,NaN,NaN,1.0,1.0,1.0,3.0,2.0,1.0,1.0,3.0,2.0,2.0,1.0,NaN,,NaN,NaN,NaN,1.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,2.0,NaN,NaN,1.0,3.0,2.0,NaN,1.0,NaN,2.0,2.0,1.0,2.0,1.0,2.0,NaN,NaN,NaN,2.0,2.0,2.0,3.0,NaN,NaN,1.0,50.0,4.0,3.0,2.0,2.0,1.0,1.0,NaN,NaN,0.0,2.0,NaN,2.0,4.0,2.0,NaN,7.0,1.0,1.0,NaN,1.0,1.0,2.0,NaN,2.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,2.0,2.0,1.0,1.0,NaN,5.866667
4,100024.0,1.0,20717.0,170207.0,1.0,1.0,0.0,1.0,2.0,17.0,5.0,17.0,1.0,1.0,1.0,1.0,1.0,S,S,2.0,NaN,2.0,1.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,2.0,1.0,2.0,2.0,NaN,2.0,2.0,2.0,NaN,NaN,NaN,4.0,4.0,2.0,2.0,4.0,1.0,3.0,2.0,1.0,WE DON'T KNOW ANYTHING ABOUT HIM,21.0,NaN,NaN,2.0,2.0,3.0,3.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,NaN,1.0,2.0,1.0,NaN,1.0,NaN,1.0,NaN,2.0,2.0,4.0,3.0,3.0,1.0,NaN,NaN,NaN,4.0,1.0,NaN,2.0,70.0,3.0,6.0,2.0,2.0,2.0,2.0,NaN,NaN,0.0,1.0,NaN,1.0,1.0,1.0,3.0,7.0,1.0,2.0,NaN,2.0,5.0,NaN,2.0,4.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,2.0,2.0,1.0,1.0,NaN,1.700000

Apr17: 1501 rows x 178 columns

,psraid,sample,int_date,fcall,attempts,refusal,ilang,version,cregion,state,density,usr,scregion,sstate,susr,stimes,igender,irace,form,llitext0,qs1,q1,q1a,q2,q3,q11f1,q12,q13,q19f2,q20f1,q21bf2,q21df2,q25af1,q25bf1,q25cf2,q25df2,q25ef2,q26,q30f2,q31f1,q32f2m1,q32f2m2,q32f2m3,q32f2m4,q32f2m5,q32f2m6,q32f2m7,q32f2m8,q32f2m9,q32f2m10,q32f2m11,q32f2m12,q32f2oe1,q32f2oe2,q32f2oe3,q32f2oe4,q32f2oe5,q32f2oe6,q32f2oe7,q32f2oe8,q32f2oe9,q32f2oe10,q32f2oe11,q32f2oe12,q36a,q36b,q36c,q37a,q37b,q41af1,q41bf1,q41cf1,q41df1,q41ef1,q41ff1,q41gf1,q41hf2,q41if2,q41jf2,q41kf2,q41lf2,q41mf2,q41nf2,q42f1,q43f2,q46f2,q47f1,q48,q49,q50f1,q50f1oe_1,q50f1oe_2,q55f2,q56a,q56b,q56c,q56d,q57a,q57b,q57c,q57d,q61af1,q61bf1,q61cf1,q61df1,q61ef1,q61ff1,q61gf2,q61hf2,q61if2,q61jf2,q61kf2,q61lf2,q62f1,q63f2,q65f2,q66f1,q67a,q67b,q67c,q67d,q67e,q70,q71,q72,q80,q81,q82,q83,q84,q92a,q92b,q92c,q92ff1,q92gf1,q92hf2,q92if2,q95,q96,sex,age,gen5,educ2,hisp,citizen,race3m1,race3m2,race3m3,racethn,racethn2,birth_hisp,relig,chr,born,attend,income,reg,party,partyln,partysum,q98,ideo,partyideo,hh1,hh3,adults,child,ql1,ql1a,qc1,ll,cp,money2,ckinfo,iphoneuse,hphoneuse,utweight,weight
0,100005.0,1.0,40517.0,170405.0,1.0,0.0,1.0,1.0,2.0,29.0,4.0,S,2.0,29.0,S,1.0,1.0,1.0,2.0,1.0,NaN,2.0,1.0,2.0,2.0,NaN,2.0,3.0,NaN,NaN,2.0,1.0,NaN,NaN,4.0,3.0,3.0,3.0,2.0,NaN,97.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,97.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,3.0,3.0,3.0,3.0,3.0,3.0,NaN,9.0,2.0,NaN,2.0,2.0,NaN,NaN,NaN,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,3.0,3.0,2.0,2.0,3.0,NaN,9.0,2.0,NaN,1.0,1.0,1.0,1.0,1.0,NaN,9.0,9.0,1.0,9.0,NaN,NaN,NaN,1.0,1.0,1.0,NaN,NaN,1.0,1.0,3.0,NaN,2.0,72.0,2.0,6.0,2.0,NaN,2.0,NaN,NaN,2.0,2.0,NaN,1.0,NaN,2.0,2.0,5.0,1.0,3.0,2.0,2.0,NaN,4.0,3.0,2.0,2.0,2.0,0.0,2.0,1.0,NaN,1.0,0.0,NaN,NaN,1.0,2.0,1.00,2.941176
1,100010.0,1.0,40517.0,170405.0,1.0,0.0,1.0,1.0,3.0,48.0,1.0,R,3.0,48.0,R,1.0,1.0,4.0,2.0,2.0,NaN,1.0,2.0,1.0,2.0,NaN,1.0,3.0,NaN,NaN,1.0,2.0,NaN,NaN,2.0,1.0,1.0,1.0,1.0,NaN,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,3.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1.0,3.0,1.0,3.0,2.0,3.0,NaN,2.0,1.0,NaN,2.0,2.0,NaN,NaN,NaN,1.0,2.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,3.0,3.0,1.0,1.0,1.0,NaN,2.0,3.0,NaN,1.0,1.0,1.0,1.0,4.0,NaN,2.0,4.0,2.0,2.0,NaN,NaN,NaN,2.0,2.0,2.0,NaN,NaN,2.0,2.0,2.0,2.0,2.0,59.0,3.0,5.0,1.0,NaN,1.0,NaN,NaN,3.0,3.0,1.0,1.0,NaN,1.0,1.0,2.0,1.0,1.0,NaN,1.0,1.0,2.0,1.0,1.0,NaN,1.0,0.0,1.0,NaN,NaN,1.0,1.0,NaN,NaN,2.0,2.0,0.45,1.323529
2,100021.0,1.0,40517.0,170405.0,1.0,0.0,1.0,1.0,3.0,12.0,4.0,S,3.0,12.0,S,1.0,2.0,2.0,1.0,1.0,NaN,2.0,1.0,2.0,2.0,2.0,2.0,3.0,NaN,2.0,NaN,NaN,4.0,4.0,NaN,NaN,NaN,3.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,2.0,3.0,1.0,NaN,9.0,1.0,1.0,3.0,3.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,1.0,1.0,2.0,NaN,NaN,NaN,NaN,1.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,1.0,1.0,1.0,1.0,4.0,1.0,NaN,9.0,9.0,2.0,3.0,NaN,NaN,NaN,1.0,1.0,1.0,1.0,2.0,NaN,NaN,2.0,8.0,1.0,82.0,2.0,8.0,2.0,NaN,1.0,NaN,NaN,1.0,1.0,NaN,13.0,NaN,2.0,5.0,10.0,1.0,2.0,NaN,2.0,NaN,4.0,5.0,2.0,2.0,2.0,0.0,9.0,9.0,NaN,1.0,1.0,NaN,NaN,2.0,2.0,0.42,1.235294
3,100028.0,1.0,40517.0,170405.0,1.0,0.0,1.0,1.0,3.0,24.0,3.0,S,3.0,24.0,S,1.0,1.0,2.0,2.0,2.0,NaN,1.0,1.0,1.0,2.0,NaN,3.0,4.0,NaN,NaN,1.0,2.0,NaN,NaN,1.0,1.0,2.0,1.0,1.0,NaN,3.0,4.0,98.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,4.0,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,4.0,2.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1.0,2.0,3.0,2.0,2.0,2.0,NaN,2.0,1.0,NaN,2.0,1.0,NaN,NaN,NaN,1.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,1.0,1.0,NaN,2.0,4.0,NaN,2.0,1.0,4.0,2.0,3.0,NaN,2.0,3.0,1.0,3.0,NaN,NaN,NaN,1.0,2.0,1.0,NaN,NaN,1.0,2.0,2.0,8.0,2.0,62.0,3.0,5.0,2.0,NaN,1.0,NaN,NaN,1.0,1.0,NaN,1.0,NaN,2.0,4.0,6.0,1.0,1.0,NaN,1.0,1.0,2.0,1.0,3.0,3.0,3.0,0.0,1.0,NaN,NaN,1.0,1.0,NaN,NaN,2.0,2.0,1.39,4.088235
4,100037.0,1.0,40517.0,170405.0,2.0,0.0,1.0,1.0,3.0,24.0,4.0,U,3.0,24.0,U,1.0,1.0,3.0,2.0,1.0,NaN,9.0,NaN,2.0,1.0,NaN,2.0,2.0,NaN,NaN,2.0,1.0,NaN,NaN,2.0,3.0,2.0,3.0,3.0,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,3.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,3.0,1.0,1.0,2.0,1.0,NaN,2.0,2.0,NaN,1.0,2.0,NaN,NaN,NaN,1.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,3.0,2.0,1.0,1.0,2.0,NaN,1.0,2.0,NaN,3.0,3.0,2.0,4.0,2.0,NaN,1.0,5.0,1.0,2.0,NaN,NaN,NaN,1.0,1.0,1.0,NaN,NaN,1.0,2.0,2.0,9.0,1.0,70.0,3.0,8.0,2.0,NaN,1.0,NaN,NaN,1.0,1.0,NaN,1.0,NaN,2.0,5.0,8.0,1.0,1.0,NaN,1.0,2.0,3.0,2.0,2.0,2.0,2.0,0.0,1.0,NaN,NaN,1.0,1.0,NaN,NaN,2.0,2.0,0.38,1.117647

Typology17: 5009 rows x 163 columns

,mergeid,sample,int_date,phase,fcall,attempts,refusal,stimes,ilang,p1version,cregion,state,density,usr,scregion,sstate,susr,igender,irace,llitext1,llitext2,qs1,cpitext1,cpitext2,qa1,qa1a,qb2,qb3,qb4,qa12,qa14a,qa14b,qa14c,qa14d,qa14e,qa15a,qa15b,qb18a,qb18b,q25a,q25b,q25c,q25d,q25f,q25g,q25i,q25k,q25n,q25p,qa26,qa27,qb27,qb28,qb29,qa30,qb30,qb31,oftvote,qb32,qb33,qb33a,cheat,qa36a,qa36b,qa36c,qa36d,qa37a,qa37b,qa37c,qa37d,q40,qb42a,qb42b,qb42c,qb42d,qb46,q50r,q50u,q50y,q50aa,q50cc,q50ee,q50hh,qbx,qe2,qe1,qe3,employ1,employ7,qe11,q51jj,q51ll,q51mm,q51nn,q51pp,q51qq,q51rr,qb52,qb52x,qb53a,qb53b,qb53c,qb54,qb54a,qb55a,qb55b,qa62,qa77,qa77a,qa77b,qa78,qb80,qa126,qa126a,qa126b,qa127,qa128,qa129,qa143,ideoconsist,typogroups,sex,age,educ2,hisp,racecmb,racethn,racethn2,birth_hisp,usborn,marital,citizen,relig,chr,born,attend,income,inchi,reg,party,partyln,partystr,partysum,qb166,qb167,qa168,qa169,ideo,partyideo,hh1,hh3,adults,child,ql1,ql1a,qc1,ll,cp,money2,ckinfo,iphoneuse,hphoneuse,weight
0,1100009.0,1.0,61417.0,1.0,170608.0,4.0,0.0,4.0,1.0,2.0,3.0,13.0,4.0,S,3.0,13.0,S,2.0,2.0,1.0,2.0,NaN,NaN,NaN,2.0,1.0,NaN,NaN,NaN,2.0,1.0,1.0,1.0,1.0,1.0,4.0,2.0,NaN,NaN,2.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,NaN,1.0,1.0,NaN,NaN,NaN,2.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,1.0,2.0,1.0,2.0,2.0,1.0,2.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,1.0,2.0,1.0,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,NaN,2.0,NaN,1.0,1.0,NaN,1.0,1.0,2.0,2.0,-8.0,1.0,1.0,45.0,8.0,2.0,2.0,2.0,2.0,NaN,1.0,6.0,NaN,13.0,NaN,1.0,4.0,7.0,NaN,1.0,2.0,NaN,1.0,2.0,NaN,NaN,NaN,1.0,5.0,5.0,1.0,NaN,1.0,0.0,1.0,NaN,NaN,1.0,1.0,NaN,NaN,2.0,2.0,1.064516
1,1100012.0,1.0,60817.0,1.0,170608.0,1.0,0.0,1.0,1.0,1.0,2.0,18.0,1.0,R,2.0,18.0,R,2.0,4.0,2.0,1.0,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,1.0,2.0,1.0,1.0,1.0,2.0,1.0,4.0,NaN,NaN,2.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,NaN,2.0,2.0,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,2.0,1.0,2.0,1.0,2.0,2.0,1.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,NaN,2.0,2.0,NaN,2.0,NaN,2.0,2.0,4.0,4.0,1.0,2.0,7.0,1.0,54.0,3.0,2.0,1.0,1.0,1.0,NaN,1.0,1.0,NaN,1.0,NaN,1.0,1.0,6.0,NaN,1.0,1.0,NaN,1.0,1.0,NaN,NaN,1.0,NaN,1.0,1.0,3.0,3.0,3.0,0.0,1.0,NaN,NaN,1.0,1.0,NaN,NaN,2.0,2.0,4.000000
2,1100014.0,1.0,60817.0,1.0,170608.0,1.0,0.0,1.0,1.0,1.0,1.0,36.0,1.0,R,1.0,36.0,R,1.0,2.0,2.0,2.0,NaN,NaN,NaN,1.0,2.0,NaN,NaN,NaN,1.0,2.0,1.0,1.0,2.0,2.0,2.0,3.0,NaN,NaN,1.0,1.0,1.0,2.0,2.0,1.0,1.0,2.0,1.0,NaN,1.0,1.0,NaN,NaN,NaN,2.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1.0,2.0,NaN,1.0,NaN,2.0,NaN,2.0,1.0,3.0,1.0,2.0,2.0,6.0,2.0,57.0,6.0,2.0,1.0,1.0,1.0,NaN,1.0,1.0,NaN,1.0,NaN,2.0,3.0,6.0,NaN,1.0,1.0,NaN,1.0,1.0,NaN,NaN,2.0,NaN,3.0,2.0,4.0,4.0,3.0,0.0,1.0,NaN,NaN,1.0,1.0,NaN,NaN,2.0,2.0,1.612903
3,1100018.0,1.0,61417.0,1.0,170608.0,6.0,1.0,6.0,1.0,2.0,3.0,1.0,1.0,R,3.0,1.0,R,2.0,2.0,2.0,1.0,NaN,NaN,NaN,2.0,1.0,NaN,NaN,NaN,1.0,2.0,2.0,2.0,2.0,1.0,4.0,1.0,NaN,NaN,1.0,9.0,2.0,1.0,1.0,9.0,2.0,2.0,1.0,NaN,1.0,2.0,NaN,NaN,NaN,2.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0,2.0,1.0,2.0,2.0,1.0,2.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,9.0,2.0,2.0,2.0,9.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,9.0,NaN,2.0,NaN,1.0,9.0,NaN,1.0,3.0,9.0,9.0,-3.0,4.0,2.0,54.0,5.0,2.0,3.0,4.0,5.0,NaN,1.0,5.0,NaN,1.0,1.0,1.0,1.0,10.0,NaN,1.0,2.0,NaN,1.0,2.0,NaN,NaN,NaN,1.0,1.0,4.0,9.0,9.0,2.0,99.0,1.0,NaN,NaN,1.0,1.0,NaN,NaN,2.0,2.0,3.741935
4,1100019.0,1.0,60817.0,1.0,170608.0,1.0,0.0,1.0,1.0,1.0,2.0,18.0,3.0,U,2.0,18.0,U,2.0,4.0,1.0,2.0,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,1.0,3.0,3.0,2.0,2.0,2.0,2.0,4.0,NaN,NaN,1.0,2.0,5.0,2.0,2.0,5.0,1.0,1.0,2.0,NaN,2.0,1.0,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,1.0,2.0,1.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,1.0,5.0,1.0,2.0,2.0,5.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,NaN,2.0,1.0,NaN,2.0,NaN,2.0,1.0,2.0,3.0,1.0,7.0,8.0,1.0,63.0,6.0,2.0,1.0,1.0,1.0,NaN,1.0,1.0,NaN,1.0,NaN,2.0,3.0,8.0,NaN,1.0,1.0,NaN,1.0,1.0,NaN,NaN,1.0,NaN,2.0,1.0,2.0,2.0,2.0,0.0,1.0,NaN,NaN,1.0,1.0,NaN,NaN,2.0,2.0,1.258065

Jan18: 1503 rows x 168 columns

,respid,sample,int_date,fcall,attempt,refusal,ilang,cregion,state,density,usr,scregion,sstate,susr,sdensity,igender,ihisp1,irace1m1,irace1m2,irace1m3,irace1m4,oisex,oirace1m1,oirace1m2,oirace1m3,oirace1m4,oihisp1,form,qs1,timezone,phtype,llitext,qcelhisp,qdlrpres,q1,q2,q2a,q5f1,q6f1,q6f1better_oe1,q6f1better_oe2,q6f1better_oe3,q6f1worse_oe1,q6f1worse_oe2,q6f1worse_oe3,q7f2,q8f2,q11a,q11cf1,q11df2,q11ef2,q12,q12b,cheat,q13,q14,q15,q16,q28a,q28c,q28d,q28e,q28f,q30af1,q30bf1,q30df1,q30ef2,q30ff2,q30gf2,q39a,q39b,q39c,q40af1,q40bf2,q40cf2,q40df1,q40ef1,q40ff1,q40gf2,q40hf2,q41f1,q42f2,q43f1,q44f2,qa2,qa3,qa4,qa4oe_1,qa4oe_2,qa4oe_3,q45af1,q45bf1,q45cf1,q45df1,q45ef1,q45ff1,q45gf1,q45hf1,q45if1,q45nf2,q45of2,q45pf2,q45qf2,q45rf2,q45sf2,q45tf2,q45uf2,q45vf2,q45wf2,q49,q50,q53,q53a,q54,q55,q56,qj22a,qj22b,qj22d,qj22e,qj29a,qj29b,qj29e,qj29j,qj29k,qa6,qa6a,qa6b,qa7,qa7a,qa7b,qa8,q72,q73,q80,q81,q82,q90,sex,age,educ,marital,hisp,racecmb,racethn,birth_hisp,relig,chr,born,attend,income,party,partyln,partysum,ideo,partyideo,reg,hh1,hh3,adults,ql1,ql1a,qc1,ll,cp,money2,cellweight,weight
0,21.0,1.0,180110.0,180110.0,1.0,0.0,1.0,3.0,12.0,2.0,S,3.0,12.0,S,2.0,2.0,2.0,1.0,NaN,NaN,NaN,2.0,1.0,NaN,NaN,NaN,2.0,1.0,NaN,1.0,1,2.0,,,1.0,1.0,1.0,1.0,1.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,NaN,NaN,1.0,NaN,1.0,1.0,9.0,1.0,1.0,2.0,1.0,2.0,3.0,1.0,1.0,1.0,2.0,NaN,NaN,NaN,1.0,4.0,1.0,1.0,NaN,NaN,1.0,1.0,1.0,NaN,NaN,2.0,NaN,1.0,NaN,1.0,1.0,9.0,999.0,NaN,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,4.0,1.0,3.0,1.0,1.0,3.0,NaN,9.0,NaN,NaN,1.0,1.0,4.0,1.0,3.0,9.0,9.0,2.0,87.0,3.0,5.0,2.0,1.0,1.0,NaN,2.0,NaN,2.0,2.0,3.0,1.0,NaN,1.0,2.0,1.0,1.0,1.0,NaN,1.0,1.0,NaN,NaN,1.0,1.0,NaN,NaN,0.925009
1,30.0,1.0,180110.0,180110.0,1.0,0.0,1.0,1.0,34.0,5.0,S,1.0,34.0,S,5.0,2.0,2.0,1.0,NaN,NaN,NaN,2.0,1.0,NaN,NaN,NaN,2.0,2.0,NaN,1.0,1,2.0,,,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,NaN,2.0,2.0,1.0,NaN,1.0,1.0,9.0,1.0,1.0,2.0,1.0,2.0,2.0,1.0,NaN,NaN,NaN,1.0,1.0,1.0,9.0,8.0,1.0,NaN,1.0,1.0,NaN,NaN,NaN,1.0,1.0,NaN,1.0,NaN,2.0,1.0,1.0,9.0,999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,4.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,9.0,1.0,1.0,1.0,2.0,1.0,1.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,NaN,NaN,9.0,NaN,NaN,9.0,1.0,4.0,1.0,3.0,9.0,1.0,1.0,99.0,5.0,1.0,2.0,1.0,1.0,NaN,2.0,NaN,2.0,2.0,10.0,1.0,NaN,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,NaN,NaN,1.0,1.0,NaN,NaN,0.857769
2,76.0,1.0,180110.0,180110.0,1.0,0.0,1.0,2.0,17.0,1.0,S,2.0,17.0,S,1.0,1.0,2.0,1.0,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,2.0,1.0,NaN,2.0,0,2.0,,,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,1.0,NaN,1.0,9.0,1.0,1.0,1.0,2.0,9.0,1.0,2.0,1.0,2.0,1.0,1.0,NaN,NaN,NaN,2.0,8.0,5.0,1.0,NaN,NaN,1.0,1.0,1.0,NaN,NaN,1.0,NaN,1.0,NaN,2.0,NaN,9.0,999.0,NaN,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,2.0,3.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,NaN,2.0,1.0,NaN,1.0,1.0,2.0,1.0,3.0,1.0,2.0,2.0,68.0,3.0,5.0,2.0,1.0,1.0,NaN,2.0,NaN,9.0,2.0,6.0,1.0,NaN,1.0,2.0,1.0,1.0,1.0,NaN,1.0,1.0,NaN,NaN,1.0,1.0,NaN,NaN,0.953144
3,123.0,1.0,180110.0,180110.0,2.0,0.0,1.0,2.0,27.0,1.0,R,2.0,27.0,R,1.0,2.0,2.0,1.0,NaN,NaN,NaN,2.0,1.0,NaN,NaN,NaN,2.0,2.0,NaN,2.0,1,2.0,,,9.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1.0,1.0,NaN,2.0,2.0,9.0,1.0,1.0,9.0,2.0,9.0,9.0,9.0,9.0,3.0,9.0,9.0,NaN,NaN,NaN,9.0,9.0,9.0,2.0,8.0,8.0,NaN,1.0,9.0,NaN,NaN,NaN,1.0,9.0,NaN,9.0,NaN,9.0,9.0,NaN,9.0,999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,9.0,2.0,2.0,9.0,1.0,9.0,NaN,4.0,9.0,9.0,1.0,1.0,2.0,9.0,9.0,2.0,2.0,2.0,9.0,9.0,NaN,NaN,9.0,NaN,NaN,9.0,2.0,9.0,9.0,9.0,1.0,9.0,2.0,87.0,1.0,5.0,2.0,1.0,1.0,NaN,2.0,NaN,2.0,1.0,10.0,1.0,NaN,1.0,3.0,2.0,1.0,1.0,NaN,1.0,2.0,NaN,NaN,1.0,0.0,NaN,NaN,2.378639
4,216.0,1.0,180111.0,180111.0,4.0,0.0,1.0,3.0,37.0,3.0,S,3.0,37.0,S,3.0,1.0,2.0,1.0,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,2.0,1.0,NaN,1.0,1,1.0,,,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,NaN,NaN,1.0,NaN,1.0,1.0,1.0,1.0,1.0,3.0,3.0,2.0,3.0,3.0,1.0,1.0,1.0,NaN,NaN,NaN,1.0,8.0,2.0,1.0,NaN,NaN,1.0,1.0,1.0,NaN,NaN,9.0,NaN,1.0,NaN,2.0,NaN,9.0,999.0,NaN,NaN,3.0,1.0,1.0,2.0,2.0,1.0,2.0,9.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,NaN,2.0,3.0,NaN,2.0,2.0,3.0,1.0,3.0,1.0,9.0,2.0,86.0,3.0,1.0,2.0,1.0,1.0,NaN,2.0,NaN,2.0,2.0,4.0,3.0,1.0,1.0,2.0,3.0,1.0,2.0,2.0,2.0,2.0,2.0,NaN,1.0,0.0,NaN,NaN,2.378639

Mar18: 1466 rows x 108 columns

,masterid,samptype,ftcalldt,numatts,refcon,ilang,cregion,STATE,DENSITY,USR,scregion,sstate,susr,sdensity,qcendiv,igender,ihisp1,irace1m1,irace1m2,irace1m3,form,rndgender,q1,q2,q7a,q7b,q7ef1,q7ff1,q7gf1,q7hf2,q7if2,q7jf2,q12,q14,q15a,q15bf1,q15cf1,q15df2,q15ef2,q24,q25a,q25b,q26a,q26b,q27a,q27b,q27df1,q27ef1,q27ff1,q27hf2,q27if2,q40a,q40b,q40c,q40d,q40e,q40f,q40g,q41,q42,q46,q47,q48,q49,q50,q51,q52,q53,q55a,q55b,q55d,q55e,q55f,q59,q61,q63,q90,q94,q95,sex,age,educ,hisp,racecmb,racethn,birth_hisp,relig,chr,born,attend,income,reg,party,partyln,partysum,ideo,partyideo,hh1,hh3,l1,l1a,c1,LL,CP,IPHONEUSE,HPHONEUSE,cellweight,weight
0,00140838F,2.0,2018-03-08,1.0,0.0,1.0,4.0,49.0,3.0,U,4.0,49,,3.0,8.0,2.0,2.0,1.0,NaN,NaN,2.0,1.0,9.0,2.0,3.0,2.0,NaN,NaN,NaN,3.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,2.0,2.0,3.0,2.0,3.0,2.0,5.0,9.0,2.0,NaN,NaN,NaN,2.0,2.0,3.0,2.0,3.0,2.0,3.0,2.0,3.0,NaN,2.0,2.0,2.0,1.0,3.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,1.0,3.0,4.0,1.0,84.0,8.0,2.0,1.0,1.0,NaN,3.0,NaN,1.0,2.0,7.0,1.0,3.0,1.0,1.0,2.0,3.0,2.0,2.0,NaN,NaN,1.0,1.0,1.0,2.0,2.0,0.388776,0.351682
1,00163543C,2.0,2018-03-12,2.0,0.0,1.0,1.0,25.0,4.0,S,1.0,36,,5.0,2.0,2.0,2.0,2.0,NaN,NaN,1.0,2.0,2.0,2.0,2.0,3.0,3.0,4.0,2.0,NaN,NaN,NaN,3.0,3.0,2.0,1.0,1.0,NaN,NaN,4.0,2.0,3.0,3.0,2.0,1.0,2.0,1.0,1.0,3.0,NaN,NaN,3.0,2.0,3.0,2.0,3.0,2.0,2.0,NaN,2.0,2.0,1.0,1.0,1.0,4.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,33.0,8.0,2.0,1.0,1.0,NaN,10.0,NaN,NaN,5.0,6.0,1.0,3.0,2.0,2.0,4.0,3.0,1.0,NaN,NaN,NaN,2.0,0.0,1.0,3.0,3.0,0.970027,1.546664
2,00167040A,2.0,2018-03-08,2.0,0.0,1.0,2.0,18.0,2.0,S,2.0,18,,2.0,3.0,1.0,2.0,1.0,NaN,NaN,2.0,2.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,3.0,2.0,1.0,2.0,2.0,1.0,NaN,NaN,1.0,2.0,9.0,2.0,1.0,2.0,1.0,3.0,2.0,NaN,NaN,NaN,1.0,3.0,2.0,4.0,2.0,1.0,2.0,2.0,1.0,2.0,NaN,2.0,2.0,2.0,3.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,1.0,2.0,1.0,3.0,2.0,2.0,35.0,6.0,2.0,1.0,1.0,NaN,1.0,NaN,1.0,1.0,4.0,1.0,1.0,NaN,1.0,2.0,1.0,6.0,2.0,NaN,NaN,2.0,0.0,1.0,3.0,3.0,0.915026,0.959834
3,00192621L,2.0,2018-03-08,3.0,0.0,1.0,2.0,18.0,5.0,,2.0,18,,5.0,3.0,2.0,1.0,1.0,NaN,NaN,2.0,1.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,3.0,2.0,2.0,3.0,2.0,1.0,NaN,NaN,1.0,1.0,2.0,2.0,1.0,3.0,2.0,3.0,1.0,NaN,NaN,NaN,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,2.0,1.0,NaN,2.0,1.0,3.0,3.0,4.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,2.0,4.0,1.0,19.0,4.0,2.0,1.0,1.0,NaN,12.0,NaN,NaN,6.0,8.0,1.0,1.0,NaN,1.0,3.0,2.0,3.0,3.0,NaN,NaN,1.0,1.0,1.0,2.0,2.0,1.766343,2.331776
4,00242725F,2.0,2018-03-08,1.0,0.0,1.0,3.0,13.0,4.0,S,3.0,13,,4.0,5.0,1.0,2.0,1.0,NaN,NaN,1.0,2.0,2.0,1.0,2.0,4.0,4.0,3.0,1.0,NaN,NaN,NaN,3.0,1.0,2.0,1.0,1.0,NaN,NaN,2.0,3.0,1.0,4.0,2.0,3.0,3.0,2.0,1.0,2.0,NaN,NaN,2.0,3.0,4.0,3.0,2.0,2.0,2.0,1.0,NaN,2.0,1.0,2.0,3.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,4.0,2.0,2.0,72.0,2.0,2.0,1.0,1.0,NaN,12.0,NaN,NaN,2.0,1.0,3.0,3.0,1.0,1.0,2.0,3.0,1.0,NaN,NaN,NaN,2.0,0.0,1.0,3.0,3.0,2.446610,1.732105

May18: 1503 rows x 123 columns

,respid,sample,int_date,fcall,attempt,refusal,ilang,cregion,state,density,usr,scregion,sstate,susr,sdensity,igender,ihisp1,irace1m1,irace1m2,irace1m3,irace1m4,form,llitext,phtype,qs1,q1,q2,q2a,campnii,q8,q9,cheat,q20,q21,q22,q26a,q26b,q26c,q27a,q27b,q27c,compuse,license,q35,q36,q40a,q40b,q41,Q45,Q46,q47,q60a,q60b,q60c,q60d,q60ef1,q60ff1,q60gf2,q60hf2,q60if2,q62,q70,q71,q72,q73,q74,q75,worryret,slepnhis,yaganhis,smok1,smok2,bloodpr,q80af1,q80bf2,q81,q82,q83,sex,age,educ,hisp,racecmb,racethn,birth_hisp,momborn,dadborn,lan1,lan2,lan3,lan4,relig,chr,born,attend,income,employ,citizen,reg,pvote16a,party,partyln,repjob,demjob,partysum,ideo,partyideo,partysumideo,hh1,hh3,adults,empcomp,snap,anycov,homeacs,ql1,ql1a,qc1,ll,cp,money2,cellweight,weight
0,1.0,1.0,180425.0,180425.0,1.0,0.0,1.0,1.0,25.0,2.0,S,1.0,25.0,S,2.0,2.0,2.0,1.0,NaN,NaN,NaN,2.0,1.0,1,NaN,2.0,2.0,1.0,1.0,2.0,NaN,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,4.0,3.0,3.0,3.0,1.0,1.0,2.0,1.0,3.0,3.0,4.0,3.0,NaN,NaN,3.0,3.0,NaN,4.0,3.0,2.0,2.0,1.0,1.0,1.0,1.0,8.0,2.0,2.0,NaN,1.0,NaN,2.0,1.0,1.0,2.0,1.0,82.0,6.0,2.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,NaN,NaN,6.0,5.0,3.0,NaN,1.0,1.0,2.0,NaN,NaN,4.0,2.0,4.0,5.0,5.0,1.0,NaN,1.0,2.0,2.0,1.0,3.0,2.0,NaN,NaN,1.0,0.0,NaN,NaN,0.876752
1,2.0,1.0,180425.0,180425.0,1.0,0.0,1.0,3.0,48.0,5.0,U,3.0,48.0,U,5.0,2.0,1.0,1.0,NaN,NaN,NaN,1.0,1.0,0,NaN,2.0,2.0,1.0,1.0,2.0,NaN,2.0,2.0,3.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,4.0,3.0,2.0,2.0,2.0,1.0,2.0,1.0,4.0,4.0,4.0,4.0,4.0,4.0,NaN,NaN,NaN,4.0,4.0,1.0,2.0,1.0,1.0,1.0,4.0,8.0,2.0,1.0,3.0,1.0,1.0,NaN,1.0,1.0,2.0,2.0,77.0,5.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0,1.0,7.0,3.0,NaN,1.0,1.0,2.0,NaN,NaN,2.0,2.0,4.0,5.0,5.0,2.0,2.0,2.0,2.0,2.0,1.0,3.0,1.0,NaN,NaN,1.0,1.0,NaN,NaN,0.706449
2,3.0,1.0,180425.0,180425.0,1.0,0.0,1.0,3.0,24.0,4.0,S,3.0,24.0,S,4.0,2.0,2.0,1.0,NaN,NaN,NaN,2.0,2.0,0,NaN,2.0,2.0,1.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,9.0,1.0,4.0,1.0,4.0,3.0,2.0,9.0,2.0,1.0,2.0,1.0,4.0,4.0,4.0,4.0,NaN,NaN,4.0,4.0,NaN,4.0,3.0,1.0,2.0,1.0,1.0,1.0,4.0,7.0,1.0,1.0,3.0,1.0,NaN,2.0,1.0,1.0,2.0,2.0,99.0,8.0,2.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,2.0,4.0,9.0,3.0,NaN,1.0,1.0,2.0,NaN,NaN,2.0,2.0,4.0,5.0,5.0,1.0,NaN,1.0,2.0,2.0,1.0,1.0,1.0,NaN,NaN,1.0,1.0,NaN,NaN,0.336219
3,4.0,1.0,180425.0,180425.0,1.0,0.0,1.0,3.0,13.0,1.0,S,3.0,13.0,S,1.0,2.0,1.0,1.0,NaN,NaN,NaN,2.0,2.0,0,NaN,2.0,2.0,1.0,1.0,2.0,NaN,2.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0,2.0,4.0,3.0,4.0,3.0,1.0,2.0,2.0,1.0,3.0,4.0,3.0,4.0,NaN,NaN,2.0,4.0,NaN,3.0,4.0,3.0,2.0,3.0,3.0,9.0,1.0,8.0,2.0,2.0,NaN,1.0,NaN,2.0,2.0,2.0,2.0,2.0,61.0,3.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,NaN,2.0,4.0,1.0,3.0,NaN,1.0,1.0,2.0,NaN,NaN,2.0,2.0,1.0,4.0,4.0,1.0,NaN,1.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,1.0,0.0,NaN,NaN,2.531771
4,5.0,1.0,180425.0,180425.0,1.0,0.0,1.0,4.0,41.0,1.0,R,4.0,41.0,R,1.0,2.0,2.0,1.0,NaN,NaN,NaN,2.0,1.0,1,NaN,1.0,1.0,1.0,1.0,1.0,NaN,1.0,3.0,3.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,4.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,NaN,NaN,2.0,1.0,NaN,2.0,2.0,1.0,1.0,3.0,1.0,2.0,3.0,6.0,2.0,1.0,1.0,1.0,NaN,1.0,1.0,1.0,1.0,1.0,63.0,4.0,2.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,NaN,NaN,6.0,6.0,3.0,NaN,1.0,1.0,3.0,1.0,3.0,NaN,1.0,3.0,3.0,2.0,1.0,NaN,1.0,2.0,2.0,1.0,1.0,2.0,NaN,NaN,1.0,0.0,NaN,NaN,0.869301

Jun18: 2002 rows x 130 columns

,respid,sample,int_date,fcall,attempt,refusal,ilang,cregion,state,density,usr,scregion,sstate,susr,sdensity,timezone,igender,ihisp1,irace1m1,irace1m2,irace1m3,irace1m4,form,llitext,phtype,qs1,q1,q2,q6f2,q6f2_oe1,q6f2_oe2,q6f2_oe3,q7a,q7b,q7c,q7df1,q7ef2,q10a,q10b,q11,q12,campnii,q20,q21,cheat,q25f1,Q25F1_1,Q25F1_2,Q25F1_3,q26,q27,q28,q29,q30,q31,q32,q38,q39,q40,q41a,q41bf1,q41cf1,q41df1,q41ef1,q41ff1,q41gf2,q41hf2,q41if2,q41jf2,q41lf2,q42,q60af1,q60bf1,q60cf1,q60df1,q60ef1,q60ff1,q60gf1,q60jf2,q60kf2,q60lf2,q60mf2,q60nf2,q60of2,q68,q69,q82,q83,q90a,q90c,q91,q92,q93,q94,q100,q101,q102,q103,q104,sex,age,educ,hisp,racecmb,racethn,birth_hisp,relig,chr,born,attend,income,reg,party,partyln,q105,partysum,ideo,partyideo,partysumideo,hh1,hh3,adults,ql1,ql1a,qc1,ll,cp,money2,cellweight,weight
0,1.0,1.0,180605.0,180605.0,1.0,0.0,1.0,3.0,11.0,5.0,U,3.0,11.0,U,5.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,2.0,1.0,0,NaN,2.0,2.0,1.0,47.0,95.0,43.0,3.0,1.0,1.0,NaN,1.0,2.0,1.0,10.0,2.0,1.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,9.0,2.0,2.0,2.0,3.0,2.0,4.0,1.0,3.0,4.0,4.0,NaN,NaN,NaN,NaN,NaN,2.0,4.0,2.0,4.0,4.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,9.0,2.0,9.0,1.0,1.0,2.0,1.0,1.0,2.0,3.0,2.0,9.0,1.0,2.0,1.0,1.0,4.0,1.0,78.0,6.0,2.0,2.0,2.0,NaN,1.0,NaN,2.0,2.0,9.0,1.0,2.0,NaN,NaN,2.0,3.0,4.0,4.0,2.0,2.0,2.0,1.0,NaN,NaN,1.0,1.0,NaN,NaN,0.581332
1,2.0,1.0,180605.0,180605.0,1.0,0.0,1.0,3.0,10.0,4.0,S,3.0,10.0,S,4.0,1.0,2.0,2.0,1.0,NaN,NaN,NaN,1.0,1.0,1,NaN,2.0,9.0,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,NaN,1.0,9.0,12.0,13.0,3.0,1.0,NaN,1.0,9.0,99.0,NaN,NaN,9.0,2.0,2.0,9.0,2.0,1.0,NaN,2.0,3.0,4.0,9.0,2.0,9.0,9.0,2.0,3.0,NaN,NaN,NaN,NaN,NaN,2.0,4.0,9.0,9.0,9.0,4.0,9.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,3.0,9.0,1.0,2.0,2.0,2.0,2.0,2.0,3.0,2.0,2.0,2.0,9.0,2.0,1.0,78.0,4.0,2.0,1.0,1.0,NaN,1.0,NaN,2.0,4.0,2.0,1.0,3.0,1.0,3.0,1.0,2.0,3.0,1.0,2.0,2.0,2.0,2.0,1.0,NaN,1.0,0.0,NaN,NaN,1.559586
2,4.0,1.0,180605.0,180605.0,1.0,0.0,1.0,3.0,12.0,2.0,S,3.0,12.0,S,2.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,1.0,2.0,0,NaN,1.0,2.0,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,NaN,2.0,2.0,2.0,3.0,1.0,1.0,NaN,1.0,1.0,31.0,37.0,2.0,1.0,1.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,4.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,3.0,3.0,1.0,2.0,3.0,3.0,3.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,63.0,3.0,2.0,1.0,1.0,NaN,13.0,NaN,1.0,3.0,1.0,1.0,1.0,NaN,3.0,1.0,1.0,1.0,1.0,3.0,3.0,3.0,2.0,1.0,NaN,1.0,0.0,NaN,NaN,2.428216
3,6.0,1.0,180605.0,180605.0,1.0,0.0,1.0,1.0,23.0,1.0,S,1.0,23.0,S,1.0,1.0,1.0,2.0,3.0,NaN,NaN,NaN,1.0,2.0,1,NaN,1.0,1.0,NaN,NaN,NaN,NaN,4.0,1.0,4.0,1.0,NaN,1.0,2.0,7.0,1.0,3.0,1.0,NaN,1.0,1.0,33.0,NaN,NaN,2.0,1.0,2.0,2.0,1.0,9.0,NaN,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,3.0,2.0,1.0,2.0,1.0,2.0,4.0,2.0,1.0,2.0,1.0,1.0,4.0,2.0,1.0,56.0,2.0,2.0,5.0,4.0,NaN,2.0,NaN,2.0,5.0,4.0,1.0,3.0,1.0,1.0,1.0,2.0,3.0,1.0,2.0,2.0,2.0,1.0,NaN,NaN,1.0,1.0,NaN,NaN,1.026937
4,7.0,1.0,180605.0,180605.0,1.0,0.0,1.0,1.0,36.0,2.0,R,1.0,36.0,R,2.0,1.0,1.0,1.0,2.0,NaN,NaN,NaN,1.0,1.0,0,NaN,2.0,1.0,NaN,NaN,NaN,NaN,9.0,1.0,1.0,1.0,NaN,1.0,2.0,6.0,1.0,4.0,1.0,NaN,NaN,1.0,2.0,68.0,NaN,1.0,1.0,1.0,1.0,1.0,2.0,2.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1.0,1.0,1.0,2.0,1.0,9.0,9.0,2.0,3.0,3.0,NaN,9.0,9.0,4.0,1.0,99.0,9.0,9.0,9.0,9.0,NaN,99.0,9.0,NaN,9.0,10.0,9.0,9.0,9.0,NaN,9.0,9.0,9.0,9.0,9.0,9.0,2.0,9.0,9.0,NaN,1.0,1.0,NaN,NaN,0.371928

W161: 5086 rows x 144 columns

,QKEY,INTERVIEW_START_W161,INTERVIEW_END_W161,DEVICE_TYPE_W161,SVYMODE_W161,LANG_W161,FORM_W161,X_PARTYSUMFINAL_W161,SATIS_W161,YEARAHEAD_W161,POL1DT_W161,POL1DTSTR_W161,PRESWHERE_W161,DTSUCCESS_W161,QUALPRES_TRMP_MF_W161,QUALPRES_TRMP_PHY_W161,QUALPRES_TRMP_ADV_W161,QUALPRES_TRMP_ETH_W161,QUALPRES_TRMP_RSP_W161,QUALPRES_TRMP_FIRM_W161,PRES_WASH_W161,PRES_WASH_EXP_W161,PRESCAB_W161,VP2PRES_W161,VP_INFL_W161,ETHICSDJT_W161,NATPROBS_GUN_W161,NATPROBS_INFR_W161,NATPROBS_IMM_W161,NATPROBS_HC_W161,NATPROBS_MNPOL_W161,NATPROBS_AI_W161,NATPROBS_CLIM_W161,NATPROBS_DEF_W161,NATPROBS_VCRI_W161,NATPROBS_K12_W161,NATPROBS_POVTY_W161,NATPROBS_LONE_W161,NATPROBS_INFL_W161,NATPROBS_ITERR_W161,NATPROBS_COMP_W161,NATPROBS_MOR_W161,NATPROBS_SSMED_W161,NATPROBS_NTDIS_W161,NATPROBS_RAC_W161,NATPROBS_UNEM_W161,NATPROBS_DTERR_W161,NATPROBS_DRG_W161,NATPROBS_PLSYS_W161,NATPROBS_FCT_W161,NEWPRES_ACCOMP_W161,NEWPRES_SUPP_W161,NEWPRES_ACTNS_W161,PRESWITHOP_W161,OPWITHPRES_W161,ECON1_W161,ECON1B_W161,ECON_FUT_JBS_W161,ECON_FUT_PRICE_W161,ECON_FUT_ENRG_W161,ECON_FUT_HOUS_W161,ECON_FUT_HLTH_W161,FAVPOL_TRUMP_W161,FAVPOL_VANCE_W161,FAVPOL_MJOHNSON_W161,FAVPOL_JEFFRIES_W161,FAVPOL_ZUCKERBERG_W161,FAVPOL_THUNE_W161,FAVPOL_SCHUMER_W161,FAVPOL_MUSK_W161,FAVPOL_RFKJR_W161,EXCPWER_W161,EXCPWER_NAME_W161,MARIJUANA3_W161,TAXRATES400_W161,TAXRATESBUS_W161,CONF2_CAREER_W161,CONF2_APPNT_W161,FEDSTATE_STAT_W161,FEDSTATE_RGHT_W161,FEDSTATE_FED2_W161,CLRSOL_W161,PRESGRPS_BP_W161,PRESGRPS_HP_W161,PRESGRPS_WP_W161,PRESGRPS_AAP_W161,PRESGRPS_EC_W161,PRESGRPS_MEN_W161,PRESGRPS_WMN_W161,PRESGRPS_UN_W161,PRESGRPS_LGB_W161,PRESGRPS_BC_W161,PRESGRPS_MIL_W161,PRESGRPS_OLD_W161,PRESGRPS_YNG_W161,PRESGRPS_PR_W161,PRESGRPS_CHI_W161,PRESGRPS_WLTH_W161,PRESGRPS_TRANS_W161,PRESGRPS_YOU_W161,REPWORKTRMP_W161,EOFOL_W161,BIRTHCIT_APP_W161,IMMIG_DT_APP_MILBRD_W161,IMMIG_DT_APP_ASYLUM_W161,IMMIG_DT_APP_DEPORT_W161,IMMIG_DT_APP_CUTFND_W161,DEPRT_DEG_W161,JAN6PARDAPP_NONVIOL_W161,JAN6PARDAPP_VIOL_W161,JAN6PARDAPP_JB_W161,JAN6CONFCM_MOD_W161,F_METRO,F_CREGION,F_CDIVISION,F_USR_SELFID,F_AGECAT,F_GENDER,F_EDUCCAT,F_EDUCCAT2,F_HISP,F_HISP_ORIGIN,F_YEARSINUS_RECODE,F_RACECMB,F_RACETHNMOD,F_BIRTHPLACE,F_MARITAL,F_RELIG,F_BORN,F_RELIGCAT1,F_ATTENDPER,F_PARTY_FINAL,F_PARTYLN_FINAL,F_PARTYSTR_FINAL,F_PARTYLNCLOSE_FINAL,F_PARTYSUM_FINAL,F_PARTYSUMIDEO_FINAL,F_REG,F_INC_SDT1,F_IDEO,F_INTFREQ,F_VOLSUM,F_INC_TIER2,WEIGHT_W161
0,100803.0,28-Jan-2025 21:38:38,28-Jan-2025 21:48:06,3.0,1.0,9.0,1.0,1.0,2.0,NaN,1.0,1.0,1.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,1.0,NaN,1.0,NaN,NaN,1.0,1.0,3.0,1.0,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,3.0,2.0,NaN,3.0,1.0,2.0,1.0,2.0,2.0,NaN,2.0,1.0,99.0,99.0,99.0,NaN,NaN,NaN,NaN,1.0,NaN,3.0,3.0,5.0,2.0,1.0,2.0,3.0,3.0,1.0,3.0,2.0,3.0,3.0,NaN,NaN,NaN,NaN,2.0,1.0,1.0,1.0,3.0,NaN,NaN,NaN,NaN,3.0,1.0,4.0,3.0,2.0,3.0,4.0,3.0,1.0,1.0,3.0,3.0,4.0,2.0,2.0,4.0,3.0,4.0,2.0,1.0,5.0,2.0,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,NaN,1.0,NaN,1.0,1.0,1.0,9.0,2.0,4.0,1.0,3.0,1.046094
1,103379.0,29-Jan-2025 12:54:51,29-Jan-2025 13:14:08,3.0,1.0,9.0,1.0,1.0,1.0,NaN,1.0,1.0,1.0,NaN,2.0,2.0,2.0,2.0,2.0,1.0,1.0,NaN,1.0,NaN,NaN,1.0,3.0,2.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,3.0,2.0,NaN,2.0,3.0,3.0,4.0,3.0,2.0,NaN,1.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,1.0,NaN,3.0,5.0,5.0,3.0,2.0,5.0,4.0,3.0,1.0,3.0,2.0,3.0,3.0,NaN,NaN,NaN,NaN,2.0,3.0,1.0,1.0,3.0,NaN,NaN,NaN,NaN,3.0,2.0,3.0,1.0,1.0,2.0,2.0,2.0,3.0,1.0,4.0,4.0,2.0,1.0,3.0,5.0,2.0,4.0,1.0,2.0,3.0,2.0,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,NaN,1.0,NaN,1.0,1.0,1.0,9.0,2.0,5.0,2.0,3.0,0.992757
2,103538.0,28-Jan-2025 16:24:57,28-Jan-2025 16:42:25,3.0,1.0,9.0,2.0,2.0,NaN,2.0,2.0,1.0,NaN,2.0,5.0,4.0,5.0,5.0,5.0,5.0,NaN,2.0,NaN,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,3.0,1.0,1.0,99.0,1.0,3.0,4.0,4.0,NaN,2.0,2.0,2.0,3.0,4.0,3.0,NaN,3.0,4.0,NaN,NaN,NaN,NaN,3.0,2.0,4.0,4.0,NaN,2.0,1.0,1.0,1.0,1.0,3.0,4.0,3.0,3.0,2.0,NaN,NaN,NaN,NaN,1.0,3.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,2.0,2.0,1.0,2.0,3.0,NaN,3.0,3.0,2.0,4.0,3.0,4.0,1.0,3.0,4.0,2.0,1.0,1.0,4.0,8.0,3.0,4.0,1.0,1.0,5.0,2.0,NaN,1.0,1.0,1.0,1.0,1.0,12.0,NaN,3.0,5.0,3.0,2.0,NaN,3.0,2.0,3.0,1.0,9.0,3.0,2.0,2.0,3.0,1.196266
3,104727.0,30-Jan-2025 20:17:21,30-Jan-2025 20:42:28,1.0,1.0,9.0,1.0,1.0,1.0,NaN,1.0,1.0,1.0,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,1.0,NaN,NaN,1.0,3.0,2.0,1.0,1.0,1.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,2.0,2.0,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,1.0,2.0,NaN,2.0,1.0,1.0,2.0,1.0,2.0,NaN,1.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,1.0,NaN,1.0,2.0,2.0,2.0,2.0,2.0,4.0,4.0,1.0,1.0,1.0,3.0,1.0,NaN,NaN,NaN,NaN,2.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,1.0,1.0,4.0,2.0,1.0,3.0,2.0,2.0,2.0,1.0,1.0,4.0,3.0,2.0,2.0,3.0,3.0,3.0,1.0,3.0,2.0,2.0,NaN,1.0,1.0,1.0,1.0,1.0,12.0,NaN,3.0,6.0,1.0,NaN,2.0,NaN,1.0,1.0,1.0,99.0,2.0,2.0,2.0,99.0,0.927173
4,108435.0,29-Jan-2025 07:46:39,29-Jan-2025 07:59:13,1.0,1.0,9.0,2.0,1.0,NaN,1.0,1.0,1.0,NaN,1.0,2.0,2.0,3.0,2.0,2.0,1.0,NaN,1.0,NaN,1.0,3.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0,1.0,2.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0,3.0,3.0,1.0,2.0,2.0,3.0,2.0,1.0,NaN,1.0,3.0,1.0,3.0,2.0,2.0,NaN,4.0,1.0,NaN,NaN,NaN,NaN,3.0,4.0,1.0,1.0,NaN,1.0,2.0,5.0,5.0,3.0,3.0,4.0,3.0,3.0,2.0,NaN,NaN,NaN,NaN,3.0,3.0,3.0,3.0,3.0,NaN,NaN,NaN,NaN,1.0,1.0,3.0,3.0,3.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,3.0,1.0,2.0,4.0,4.0,1.0,2.0,3.0,2.0,4.0,2.0,1.0,6.0,2.0,NaN,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,4.0,1.0,NaN,2.0,NaN,1.0,1.0,1.0,9.0,2.0,2.0,2.0,3.0,0.782653

W167: 3589 rows x 170 columns

,QKEY,INTERVIEW_START_W167,INTERVIEW_END_W167,DEVICE_TYPE_W167,SVYMODE_W167,LANG_W167,FORM_W167,POL1DT_W167,POL1DTSTR_W167,LIFEFIFTY_W167,USCONF_FUT_W167,WISDOM_PPL_W167,GOVSIZE1_W167,DTCONF_ECON_W167,DTCONF_IMMI_W167,DTCONF_TRAD_W167,DTCONF_ABCN_W167,DTCONF_CLSR_W167,DTCONF_HECR_W167,DTCONF_FRGN_W167,DTCONF_HCP_W167,DTCONF_TAX_W167,DTCONF_EXEC_W167,NEW_ADMIN_ECON_W167,NEW_ADMIN_GLOB_W167,DTTRUST_W167,PRES_ETHICAL_ADMIN_W167,DEMACT_IMPD_CMN_W167,DEMACT_IMPD_PUSH_W167,DEMOFF_EFF_CMN_W167,DEMOFF_EFF_PUSH_W167,TRUMPACT_IMPD_CMN_W167,TRUMPACT_IMPD_PUSH_W167,TRUMP_EFF_CMN_W167,TRUMP_EFF_PUSH_W167,DT_REPRE_W167,ECON1_W167,ECON1B_W167,PERSFNC_W167,PERSFNCB_W167,ECONCONC_UNEM_W167,ECONCONC_PRICE_W167,ECONCONC_REAL_W167,ECONCONC_STCK_W167,ECONCONC_ENG2_W167,POLINTOL2_REP_W167,POLINTOL2_DEM_W167,GOVRESP_COL_W167,GOVRESP_INS_W167,GOVRESP_STAND_W167,GOVRESP_RET_W167,GOVRESP_EDUC_W167,GOVRESP_WIFI_W167,GOVRESP_CLEA_W167,GOVRESP_ENERG_W167,GOVRESP2_MIL_W167,GOVRESP2_BORD_W167,GOVRESP2_PARK_W167,INSTFAV_CONG_W167,INSTFAV_COURT_W167,INSTFAV_REP_W167,INSTFAV_DEM_W167,FEDCRT_IMPT_W167,FEDCRT_CONF_W167,FEDCRT_CONF_NS_W167,TARIFF_APP_W167,TRUMPAPPROV_DEI_W167,TRUMPAPPROV_DEI_NS_W167,POLSTOR_FOLL_LAW_W167,POLSTOR_FOLL_DOGE_W167,POLSTOR_FOLL_DPRT_W167,POLSTOR_FOLL_TARF_W167,POLSTOR_FOLL_PROT_W167,POLSTOR_FOLL_MEAS_W167,POLSTOR_FOLL_CUTS_W167,POLSTOR_FOLL_BORD_W167,POLSTOR_FOLL_LEGAL_W167,POLSTOR_FOLL_SEC_W167,DT_REDUCTIONS_W167,DT_RED_CARE_W167,DT_RED_RUN_W167,DT_RED_NEED_W167,DT_RED_SAV_W167,DTEOS_PRESPOW2_W167,DISCRRIM_BLACK_W167,DISCRRIM_HISP_W167,DISCRRIM_WHITE_W167,DISCRRIM_ASIAN_W167,DISCRRIM_WOM_W167,DISCRRIM_MEN_W167,DISCRRIM_TRANS_W167,DISCRRIM_IMMIGL_W167,DISCRRIM_IMMIGU_W167,DISCRRIM_NOCOLL_W167,DISCRRIM_LGBC_W167,DISCRRIM_REL_W167,DISCRRIM_RUR_W167,DISCRRIM_CIT_W167,DISCRRIM_YOUNG_W167,DISCRRIM_OLD_W167,DISCRRIM_JEW_W167,DISCRRIM_MUS_W167,DISCRRIM_EVANG_W167,DISCRRIM_ATH_W167,PF_HAPPEN_HOU_W167,PF_HAPPEN_LOSE_W167,PF_HAPPEN_RAISE_W167,PF_HAPPEN_SAVE_W167,PF_HAPPEN_MED_W167,PF_HAPPEN_FOOD_W167,PF_HAPPEN_CHILD_W167,PF_HAPPEN_AUTO_W167,PF_HAPPEN_BRRW_W167,PF_HAPPEN_VACA_W167,PF_HAPPEN_PYDY_W167,BILLSTYPICAL_W167,BILLSNOW_W167,EMERGFUND_W167,FEDCRT_PROB_W167,FEDCRT_FOL_W167,SCOTUS_RULFOL_W167,TRLYAM_TGEN_W167,TRLYAM_SGENLG_W167,TRLYAM_SGENIL_W167,IMM_ENG_RALLY_W167,IMM_ENG_ACTION_W167,IMM_ENG_POST_W167,IMM_ENG2_RALLY_W167,IMM_ENG2_ACTION_W167,IMM_ENG2_POST_W167,IMM_APP_W167,HORSE_W153,VOTESTRONG_W153,VOTEGEN24_LEAN_W153,HORSE_W156,VOTESTRONG_W156,VOTEGEN24_LEAN_W156,VOTEGEN_POST_W159,F_METRO,F_CREGION,F_CDIVISION,F_USR_SELFID,F_AGECAT,F_GENDER,F_EDUCCAT,F_EDUCCAT2,F_HISP,F_HISP_ORIGIN,F_YEARSINUS_RECODE,F_RACECMB,F_RACETHNMOD,F_BIRTHPLACE,F_MARITAL,F_RELIG,F_BORN,F_RELIGCAT1,F_ATTENDPER,F_PARTY_FINAL,F_PARTYLN_FINAL,F_PARTYSTR_FINAL,F_PARTYLNCLOSE_FINAL,F_PARTYSUM_FINAL,F_PARTYSUMIDEO_FINAL,F_REG,F_INC_SDT1,F_IDEO,F_INTFREQ,F_VOLSUM,F_INC_TIER2,WEIGHT_W167
0,100363.0,08-Apr-2025 15:12:07,08-Apr-2025 15:24:20,1.0,1.0,9.0,2.0,2.0,1.0,2.0,NaN,3.0,1.0,4.0,4.0,NaN,NaN,NaN,NaN,4.0,4.0,4.0,4.0,2.0,2.0,2.0,NaN,1.0,1.0,3.0,3.0,1.0,4.0,4.0,1.0,1.0,3.0,2.0,3.0,2.0,3.0,NaN,NaN,1.0,1.0,1.0,2.0,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3.0,3.0,3.0,3.0,1.0,NaN,4.0,4.0,NaN,4.0,NaN,NaN,NaN,NaN,NaN,3.0,3.0,3.0,4.0,3.0,4.0,NaN,NaN,2.0,2.0,1.0,NaN,NaN,NaN,NaN,2.0,3.0,2.0,2.0,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,4.0,4.0,2.0,2.0,2.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,NaN,1.0,NaN,1.0,1.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,5.0,2.0,2.0,NaN,2.0,2.0,NaN,2.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,6.0,2.0,NaN,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,4.0,2.0,NaN,2.0,NaN,2.0,3.0,1.0,9.0,3.0,2.0,1.0,2.0,1.135669
1,103379.0,08-Apr-2025 14:50:19,08-Apr-2025 15:44:18,3.0,1.0,9.0,2.0,1.0,1.0,3.0,NaN,3.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,1.0,1.0,1.0,NaN,4.0,4.0,4.0,3.0,3.0,1.0,2.0,1.0,1.0,2.0,3.0,2.0,3.0,3.0,NaN,NaN,4.0,3.0,2.0,1.0,NaN,NaN,NaN,NaN,2.0,2.0,1.0,2.0,1.0,1.0,2.0,3.0,2.0,2.0,4.0,1.0,NaN,4.0,2.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,5.0,4.0,3.0,3.0,5.0,1.0,NaN,NaN,1.0,1.0,3.0,NaN,NaN,NaN,NaN,4.0,2.0,4.0,2.0,3.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,NaN,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,2.0,1.0,1.0,NaN,1.0,1.0,NaN,1.0,1.0,3.0,5.0,2.0,4.0,1.0,2.0,3.0,2.0,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,NaN,1.0,NaN,1.0,1.0,1.0,9.0,2.0,5.0,2.0,3.0,1.169792
2,108435.0,08-Apr-2025 17:06:04,08-Apr-2025 17:29:49,1.0,1.0,9.0,1.0,1.0,1.0,1.0,1.0,NaN,1.0,1.0,1.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,1.0,1.0,NaN,1.0,2.0,5.0,4.0,3.0,3.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,3.0,2.0,2.0,2.0,NaN,NaN,3.0,1.0,2.0,2.0,1.0,2.0,NaN,NaN,NaN,NaN,1.0,1.0,1.0,2.0,2.0,2.0,4.0,2.0,5.0,NaN,2.0,1.0,NaN,2.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,2.0,3.0,1.0,NaN,NaN,3.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0,2.0,2.0,3.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,2.0,NaN,NaN,1.0,1.0,99.0,2.0,2.0,2.0,NaN,NaN,NaN,1.0,1.0,1.0,NaN,NaN,NaN,NaN,1.0,1.0,2.0,3.0,2.0,4.0,2.0,1.0,6.0,2.0,NaN,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,4.0,1.0,NaN,2.0,NaN,1.0,1.0,1.0,9.0,2.0,2.0,2.0,3.0,1.110668
3,108592.0,08-Apr-2025 19:29:44,08-Apr-2025 19:49:16,1.0,1.0,9.0,1.0,2.0,1.0,1.0,3.0,NaN,2.0,4.0,4.0,4.0,4.0,4.0,4.0,NaN,NaN,NaN,NaN,2.0,2.0,NaN,4.0,3.0,1.0,3.0,3.0,2.0,5.0,3.0,3.0,1.0,4.0,2.0,2.0,2.0,1.0,1.0,1.0,NaN,NaN,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1.0,4.0,4.0,4.0,2.0,1.0,5.0,NaN,4.0,4.0,NaN,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,4.0,2.0,2.0,NaN,NaN,1.0,99.0,99.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,NaN,NaN,1.0,1.0,1.0,2.0,1.0,1.0,NaN,1.0,1.0,5.0,2.0,1.0,NaN,2.0,1.0,NaN,2.0,1.0,2.0,3.0,2.0,4.0,2.0,2.0,4.0,2.0,NaN,1.0,2.0,2.0,1.0,3.0,1.0,2.0,1.0,2.0,2.0,NaN,1.0,NaN,2.0,4.0,1.0,5.0,4.0,2.0,2.0,2.0,1.282313
4,113274.0,08-Apr-2025 21:53:01,08-Apr-2025 22:01:26,1.0,1.0,9.0,1.0,2.0,2.0,2.0,3.0,NaN,1.0,3.0,3.0,3.0,3.0,3.0,3.0,NaN,NaN,NaN,NaN,2.0,2.0,NaN,3.0,2.0,2.0,3.0,3.0,3.0,3.0,2.0,2.0,1.0,3.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,2.0,2.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1.0,3.0,3.0,3.0,3.0,1.0,3.0,NaN,3.0,4.0,NaN,3.0,3.0,3.0,3.0,3.0,NaN,NaN,NaN,NaN,NaN,3.0,2.0,2.0,NaN,NaN,1.0,2.0,2.0,3.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,1.0,NaN,NaN,1.0,1.0,1.0,2.0,1.0,1.0,NaN,1.0,1.0,2.0,NaN,1.0,NaN,2.0,1.0,NaN,2.0,1.0,1.0,1.0,1.0,3.0,1.0,3.0,1.0,2.0,NaN,1.0,3.0,5.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,NaN,1.0,NaN,2.0,4.0,3.0,2.0,4.0,5.0,2.0,1.0,1.914414

the phone files (2017-2018) start with technical columns like `respid`, `sample`, `int_date`; the ATP files (2025) start with `QKEY` and names ending in `_W161` / `_W167`. Everything is stored as numbers.

The table holds only a number, what it means is stored in the metadata. Example: the approval question in Apr17 (`q1`):

In [5]:
print(labels["Apr17"]["q1"])
print(vlabels("Apr17", "q1"))
surveys["Apr17"]["q1"].head(8).tolist()

Q.1 Do you approve or disapprove of the way Donald Trump is handling his job as President? [IF DK ENTER AS DK. IF DEPENDS PROBE ONCE WITH:  Overall do you approve or disapprove of the way Donald Trump is handling his job as President?
{1.0: 'Approve', 2.0: 'Disapprove', 9.0: "Don't know/Refused (VOL.)"}

[2.0, 1.0, 2.0, 1.0, 9.0, 2.0, 2.0, 1.0]

## 3. The columns differ between files

In [6]:
pd.DataFrame({w: list(surveys[w].columns[:8]) for w in WAVE_ORDER})

,Feb17,Apr17,Typology17,Jan18,Mar18,May18,Jun18,W161,W167
0,psraid,psraid,mergeid,respid,masterid,respid,respid,QKEY,QKEY
1,sample,sample,sample,sample,samptype,sample,sample,INTERVIEW_START_W161,INTERVIEW_START_W167
2,int_date,int_date,int_date,int_date,ftcalldt,int_date,int_date,INTERVIEW_END_W161,INTERVIEW_END_W167
3,fcall,fcall,phase,fcall,numatts,fcall,fcall,DEVICE_TYPE_W161,DEVICE_TYPE_W167
4,version,attempts,fcall,attempt,refcon,attempt,attempt,SVYMODE_W161,SVYMODE_W167
5,attempts,refusal,attempts,refusal,ilang,refusal,refusal,LANG_W161,LANG_W167
6,refusal,ilang,refusal,ilang,cregion,ilang,ilang,FORM_W161,FORM_W167
7,ilang,version,stimes,cregion,STATE,cregion,cregion,X_PARTYSUMFINAL_W161,POL1DT_W167

In [7]:
colsets = {w: {c.lower() for c in d.columns} for w, d in surveys.items()}

common_all = set.intersection(*colsets.values())
common_phone = set.intersection(*[colsets[w] for w in phone])
union_all = set.union(*colsets.values())

print(f"Unique column names in total: {len(union_all)}")
print(f"Shared by all 9 files: {len(common_all)}")
print(f"Shared by the 7 phone files: {len(common_phone)}")
print(f"Shared between phone and ATP files: {len(common_phone & colsets['W161'])}")
print()
print("The 30 names shared by the phone files:")
print(sorted(common_phone))

Unique column names in total: 888
Shared by all 9 files: 0
Shared by the 7 phone files: 30
Shared between phone and ATP files: 0

The 30 names shared by the phone files:
['age', 'attend', 'birth_hisp', 'born', 'chr', 'cp', 'cregion', 'density', 'hh1', 'hh3', 'hisp', 'ideo', 'igender', 'ilang', 'income', 'll', 'party', 'partyideo', 'partyln', 'partysum', 'racethn', 'reg', 'relig', 'scregion', 'sex', 'sstate', 'state', 'susr', 'usr', 'weight']

Phone surveys and ATP waves share **no column names at all**, and even among the phone files only 30 columns match. This is why we need a crosswalk

### The full codebook: every variable of every file

In [8]:
rows = []
for w in WAVE_ORDER:
    d = surveys[w]
    for c in d.columns:
        rows.append({"wave": w, "variable": c, "question text": labels[w].get(c) or "",
                     "unique values": d[c].nunique(), "% missing": round(100 * d[c].isna().mean(), 1),
                     "labelled codes": len(vlabels(w, c))})
codebook = pd.DataFrame(rows)
print("Variables in total (all 9 files):", len(codebook))
codebook.groupby("wave", sort=False).size().to_frame("variables").T

Variables in total (all 9 files): 1311

wave       Feb17  Apr17  Typology17  Jan18  Mar18  May18  Jun18  W161  W167
variables    127    178         163    168    108    123    130   144   170

wave       Feb17  Apr17  Typology17  Jan18  Mar18  May18  Jun18  W161  W167
variables    127    178         163    168    108    123    130   144   170

In [9]:
pd.set_option("display.max_rows", None)
for w in WAVE_ORDER:
    print(f"\n\n\n\n================== {w}: all {surveys[w].shape[1]} variables")
    display(codebook[codebook["wave"] == w].drop(columns="wave").set_index("variable"))

================== Feb17: all 127 variables

,question text,unique values,% missing,labelled codes
variable,,,,
psraid,Unique ID,1503,0.0,0
sample,Sample type,2,0.0,4
int_date,Interview date,6,0.0,0
fcall,Date of first call to number,6,0.0,0
version,Revisions to questionnaire,2,0.0,2
attempts,Total attempts to number,8,0.0,0
refusal,Refusal Conversion,2,0.0,2
ilang,Language of interview,2,0.0,2
cregion,Final Census Region after zip/fips merges,4,0.0,4
state,Final State code after zip/fips merges,51,0.0,51
density,Final Density code after zip/fips merges,5,0.0,2
sstate,State from FIPS - sample,51,0.0,51
form,Form,2,0.0,2
stimes,Number of times to finish survey,8,0.0,0
igender,Interviewer gender,2,0.0,3
irace,Interviewer Race/Ethnicity,6,0.0,6
llitext0,Gender randomization for landline introduction,2,74.9,2
susr,Community type - sample,4,0.0,3
usr,Community type,3,0.0,3
scregion,Census region - sample,4,0.0,4
qs1,"S1. Are you under 18 years old, OR are you 18 or older?",1,25.1,3
q1,Q.1 Do you approve or disapprove of the way Donald Trump is handling his job as President? [IF DK ENTER AS DK. IF DEPENDS PROBE ONCE WITH: Overall do you approve or disapprove of the way Donald Trump is handling his job as President?,3,0.0,3
q1a,"Q.1a Do you [approve/disapprove] very strongly, or not so strongly?",3,4.7,3
q2,"Q.2 All in all, are you satisfied or dissatisfied with the way things are going in this country today?",3,0.0,3
q5af1,"Q.5aF1 Do you approve or disapprove of the way Donald Trump is handling [INSERT ITEM, RANDOMIZE] / The economy",3,50.6,3
q5bf1,"Q.5bF1 Do you approve or disapprove of the way Donald Trump is handling [INSERT ITEM, RANDOMIZE] / The threat of terrorism",3,50.6,3
q5cf1,"Q.5cF1 Do you approve or disapprove of the way Donald Trump is handling [INSERT ITEM, RANDOMIZE] / The nation's foreign policy",3,50.6,3
q5df1,"Q.5dF1 Do you approve or disapprove of the way Donald Trump is handling [INSERT ITEM, RANDOMIZE] / The nation's immigration policy",3,50.6,3
q6af2,Q.6aF2 Does Donald Trump make you feel [INSERT FIRST ITEM; RANDOMIZE] or not? / Hopeful,3,49.4,3
q6bf2,Q.6bF2 Does Donald Trump make you feel [INSERT FIRST ITEM; RANDOMIZE] or not? / Proud,3,49.4,3
q6cf2,Q.6cF2 Does Donald Trump make you feel [INSERT FIRST ITEM; RANDOMIZE] or not? / Angry,3,49.4,3
q6df2,Q.6dF2 Does Donald Trump make you feel [INSERT FIRST ITEM; RANDOMIZE] or not? / Uneasy,3,49.4,3
q10a,Q.10a Do you approve or disapprove of the job the [INSERT ITEM; RANDOMIZE] are doing? / Republican leaders in Congress,3,0.0,3
q10b,Q.10b Do you approve or disapprove of the job the [INSERT ITEM; RANDOMIZE] are doing? / Democratic leaders in Congress,3,0.0,3
q15af1,"Q.15aF1 As I read some pairs of opposite phrases, tell me which one best reflects your impression of Donald Trump so far. (First,) does Donald Trump impress you as ... / Trustworthy or NOT trustworthy",4,50.6,4
q15b,"Q.15b As I read some pairs of opposite phrases, tell me which one best reflects your impression of Donald Trump so far... / Someone who cares about people like me or someone who DOESN'T care about people like me",4,0.0,4
q15cf2,"Q.15cF2 As I read some pairs of opposite phrases, tell me which one best reflects your impression of Donald Trump so far. (First,) does Donald Trump impress you as ... / A strong leader or NOT a strong leader",4,49.4,4
q15df1,"Q.15dF2 As I read some pairs of opposite phrases, tell me which one best reflects your impression of Donald Trump so far. (First,) does Donald Trump impress you as ... / A good communicator or NOT a good communicator?",4,50.6,4
q15ef1,"Q.15eF2 As I read some pairs of opposite phrases, tell me which one best reflects your impression of Donald Trump so far. (First,) does Donald Trump impress you as ... / Able to get things done or NOT able to get things done",4,50.6,4
q15ff1,"Q.15fF1 As I read some pairs of opposite phrases, tell me which one best reflects your impression of Donald Trump so far. (First,) does Donald Trump impress you as ... / Even tempered or NOT even tempered",4,50.6,4
q15gf2,"Q.15gF2 As I read some pairs of opposite phrases, tell me which one best reflects your impression of Donald Trump so far. (First,) does Donald Trump impress you as ... / Well informed or NOT well informed",4,49.4,4
q15hf2,"Q.15hF2 As I read some pairs of opposite phrases, tell me which one best reflects your impression of Donald Trump so far. (First,) does Donald Trump impress you as ... / Keeps his promises or DOESN'T keep his promises",4,49.4,4
q15if2,"Q.15iF2 As I read some pairs of opposite phrases, tell me which one best reflects your impression of Donald Trump so far. (First,) does Donald Trump impress you as ... / A good manager or NOT a good manager",4,49.4,4
q16,Q.16 How much respect do you think Donald Trump has for this country's democratic institutions and traditions? [READ],5,0.0,5
q19,Q.19 How confident are you that Donald Trump keeps his own business interests separate from the decisions he makes as president? [READ]?,5,0.0,5
q35,"Q.35 How much, if anything, have you heard or read about the executive order signed by Donald Trump to stop refugees from entering the U.S. for 120 days and prevent people from seven majority-Muslim countries from entering the U.S...",4,0.0,4
q36,"Q.36 Overall, would you say you approve or disapprove of this policy?",3,0.0,3
q37,"Q.37 Regardless of whether you approve or disapprove of this policy, do you think the Trump administration did an excellent, good, only fair, or poor job communicating the executive order and putting it into effect?",5,0.0,5
q39,"Q.39 Do you think this executive order increases the chance of a terrorist attack on the U.S., decreases the chance of a terrorist attack on the U.S., or doesn't make much difference either way?",4,0.0,4
q43,"Q.43 How much, if anything, have you heard about Donald Trump's choice of Neil Gorsuch [PRONOUNCED: ‘Gore-sitch'] to be the next Supreme Court justice? Have you heard [READ IN ORDER]?",4,0.0,4
q44,"Q.44 From what you've seen and heard so far, do you think the Senate should or should not confirm Neil Gorsuch [PRONOUNCED: ‘Gore-sitch'] to the Supreme Court?",3,0.0,3
q45,Q.45 Why do you think he should not be confirmed? [OPEN END; PROBE FOR SPECIFIC REASONS],2,67.8,2
q45vb,Q.45 Why do you think he should not be confirmed? [VERBATIM],432,0.0,0
q45oem1,Q.45 Why do you think he should not be confirmed? [FIRST MENTION],12,67.8,11
q45oem2,Q.45 Why do you think he should not be confirmed? [SECOND MENTION],9,96.8,11
q45oem3,Q.45 Why do you think he should not be confirmed? [THIRD MENTION],4,99.5,11
q52,"Q.52 All in all, would you favor or oppose building a wall along the entire border with Mexico?",3,0.0,3
q53,"Q.53 If the U.S. builds a wall along the entire border with Mexico, do you think [RANDOMIZE Mexico or the United States] would ultimately pay for it?",4,0.0,4
q54,"Q.54 Do you think a wall along the entire border with Mexico would lead to a major reduction in illegal immigration into the U.S., a minor reduction in illegal immigration or not have much impact?",4,0.0,4
q55,"Q.55 In your opinion, how much support for extremism, if any, is there among Muslims living in the U.S.? [READ]",5,0.0,5
q61a,Q.61a How important are each of the following to the United States maintaining a strong democracy. / That the rights of people with unpopular views are protected,5,0.0,5
q61b,Q.61b How important are each of the following to the United States maintaining a strong democracy. / That national elections are open and fair,5,0.0,5
q61c,Q.61c How important are each of the following to the United States maintaining a strong democracy. / That news organizations are free to criticize political leaders,5,0.0,5
q61d,Q.61d How important are each of the following to the United States maintaining a strong democracy. / That people have the right to non-violent protest,5,0.0,5
q61e,"Q.61e How important are each of the following to the United States maintaining a strong democracy. / That there is a system of checks and balances dividing power between the President, Congress, and the courts",5,0.0,5
q62f1,"Q.62F1 How would you rate economic conditions in this country today… as excellent, good, only fair, or poor?",5,50.6,5
q63f1,"Q.63F1 A year from now, do you expect that economic conditions in the country as a whole will be better than they are at present, or worse, or just about the same as now?",4,50.6,4
q64f2,"Q.64F2 Thinking about financial regulation, which comes closer to your view [READ AND RANDOMIZE]:",3,49.4,3
q65,"Q.65 On balance, do you think having an increasing number of people of many different races, ethnic groups and nationalities in the US makes this country a better place to live, a worse place to live, or doesn't make much difference...",4,0.0,4
q66,Q.66 Which comes closer to your view — even if neither is exactly right.,3,0.0,3
q68f1,Q.68F1 Do you favor or oppose building the Keystone XL pipeline that would transport oil from Canada's oil sands region through the Midwest to refineries in Texas?,3,50.6,3
q69f2,Q.69F2 Do you favor or oppose building the Dakota Access Pipeline that would transport oil from the shale oil region in North Dakota through the Midwest?,3,49.4,3
q70f1,"Q.70F1 Do you think the U.S. has a responsibility to accept refugees into the country, or do you think the U.S. does NOT have a responsibility to do this?",3,50.6,3
q71f2,"Q.71F2 Do you think the U.S. has a responsibility to accept refugees from Syria into the country, or do you think the U.S. does NOT have a responsibility to do this?",3,49.4,3
q74,Q.74 Do you approve or disapprove of the health care law passed by Barack Obama and Congress in 2010?,3,0.0,3
q75,"Q.75 When it comes to the health care law, would you like to see Republican leaders in Congress [READ; RANDOMIZE]:?",3,58.3,3
q81,"Q.81 How concerned, if at all, are you about extremism in the name of Islam around the WORLD these days? Are you very concerned, somewhat concerned, not too concerned or not at all concerned?",5,0.0,5
q82,"Q.82 How concerned, if at all, are you about extremism in the name of Islam in the U.S.? Are you very concerned, somewhat concerned, not too concerned or not at all concerned?",5,0.0,5
q84a,"Q.84a Is your overall opinion of [INSERT NAME; RANDOMIZE; OBSERVE FORM SPLITS] very favorable, mostly favorable, mostly UNfavorable, or very unfavorable? / Donald Trump",6,0.0,7
q84bf1,"Q.84bF1 Is your overall opinion of [INSERT NAME; RANDOMIZE; OBSERVE FORM SPLITS] very favorable, mostly favorable, mostly UNfavorable, or very unfavorable? / Chuck Schumer",7,50.6,7
q84cf1,"Q.84cF1 Is your overall opinion of [INSERT NAME; RANDOMIZE; OBSERVE FORM SPLITS] very favorable, mostly favorable, mostly UNfavorable, or very unfavorable? / Paul Ryan",7,50.6,7
q84df1,"Q.84dF1 Is your overall opinion of [INSERT NAME; RANDOMIZE; OBSERVE FORM SPLITS] very favorable, mostly favorable, mostly UNfavorable, or very unfavorable? / John McCain",7,50.6,7
q84ef2,"Q.84eF2 Is your overall opinion of [INSERT NAME; RANDOMIZE; OBSERVE FORM SPLITS] very favorable, mostly favorable, mostly UNfavorable, or very unfavorable? / Nancy Pelosi",7,49.4,7
q84ff2,"Q.84ff2 Is your overall opinion of [INSERT NAME; RANDOMIZE; OBSERVE FORM SPLITS] very favorable, mostly favorable, mostly UNfavorable, or very unfavorable? / Mitch McConnell",7,49.4,7
q84gf2,"Q.84gF2 Is your overall opinion of [INSERT NAME; RANDOMIZE; OBSERVE FORM SPLITS] very favorable, mostly favorable, mostly UNfavorable, or very unfavorable? / Federal government workers",7,49.4,7
q88,Q.88 Some people think targeting and killing civilians can be justified...Other people believe...this kind of violence can never be justified. Do you personally feel that this kind of violence can often be...,5,0.0,5
q90f1,"Q.90F1 How LIKELY do you think it is that your telephone calls and e-mails are being monitored by the government? Very likely, somewhat likely, not too likely, or not at all likely?",5,50.6,5
q91f2,"Q.91F2 When law enforcement officers have arrested Muslims in the U.S. suspected of PLOTTING terrorist acts, do you think [READ; RANDOMIZE], or do you think [INSERT]?",4,55.6,4
sex,SEX. Respondent's sex [DO NOT ASK],2,0.0,2
age,AGE. What is your age?,79,0.0,2
gen5,Generation,5,0.9,6
educ2,EDUC2. What is the highest level of school you have completed or the highest degree you have received? [DO NOT READ] [INTERVIEWER NOTE: Enter code 3-HS grad if R completed training that did NOT count toward a degree],9,0.0,9
hisp,"HISP. Are you of Hispanic, Latino, or Spanish origin, such as Mexican, Puerto Rican or Cuban?",3,0.0,3
adults,# of adults in HH computed from HH1 and HH3,3,0.0,2
racethn,Race/Ethnicity,4,2.1,5
racethn2,Race/Ethnicity with nativity for Hispanics,6,0.0,6
birth_hisp,"BIRTH_HISP. Were you born in the United States, on the island of Puerto Rico, or in another country?",4,86.5,4
citizen,"CITIZEN. Are you a citizen of the United States, or not?",3,93.3,3
child,Number of children in household,9,0.0,2
relig,"RELIG. What is your present religion, if any? Are you Protestant, Roman Catholic, Mormon, Orthodox such as Greek or Russian Orthodox, Jewish, Muslim, Buddhist, Hindu, atheist, agnostic, something else, or nothing in particular?",15,0.0,15
chr,"CHR. Do you think of yourself as a Christian or not? [IF R NAMED A NON-CHRISTIAN RELIGION IN PREVIOUS QUESTION (e.g. Native American, Wiccan, Pagan, etc.), DO NOT READ (ENTER 'NO' CODE 2)]",3,94.1,3
born,"BORN. Would you describe yourself as a 'born again' or evangelical Christian, or not?",3,33.5,3
attend,"ATTEND. Aside from weddings and funerals, how often do you attend religious services... more than once a week, once a week, once or twice a month, a few times a year, seldom, or never?",7,0.0,7
q92,"Q.92 Do you personally know anyone who is Muslim, or not?",3,1.0,3
q92a,Q.92a And about how many people who are Muslim would you say you personally know [READ OPTIONS IN ORDER; REVERSE ORDER FOR HALF SAMPLE]?,5,41.4,5
income,"INCOME. Last year, that is in 2015, what was your total family income from all sources, before taxes? Just stop me when I get to the right category. [READ]",10,0.0,10
reg,REG. Which of these statements best describes you? [READ IN ORDER] [INSTRUCTION: BE SURE TO CLARIFY WHETHER RESPONDENT IS ABSOLUTELY CERTAIN THEY ARE REGISTERED...],4,0.0,4
party,"PARTY. In politics TODAY, do you consider yourself a Republican, Democrat, or independent?",6,0.0,6
partyln,PARTYLN. As of today do you lean more to the Republican Party or more to the Democratic Party?,3,60.0,3
partysum,Leaned party identification,3,0.0,3
partyideo,Party and Ideology,6,0.0,6
q93,"Q.93 If Donald Trump and the Republican leaders in Congress disagree on an issue, are you more likely to trust Trump or more likely to trust the Republican leaders in Congress?",5,61.3,5
q94,Q.94 What concerns you more? [READ AND RANDOMIZE]?,3,47.0,3
ideo,"IDEO. In general, would you describe your political views as... [READ]",6,0.0,6
hh1,"HH1. How many people, including yourself, live in your household?",9,0.0,2
hh3,"HH3. How many, including yourself, are adults, age 18 and older?",9,18.8,2
ql1,L1. Now thinking about your telephone use… Do you have a working cell phone?,3,74.9,3
ql1a,L1a. Does anyone in your household have a working cell phone?,2,97.8,3
qc1,C1. Now thinking about your telephone use… Is there at least one telephone INSIDE your home that is currently working and is not a cell phone?,3,25.1,3
money2,"MONEY2. That's the end of the interview. If you would like to be reimbursed for your cell phone minutes, we can send you $5. I will need your full name and a mailing address where we can send you the money.",2,63.3,2
money3,"MONEY3 As an alternative, we can mail you $5 in cash. I will need your full name and a mailing address where we can send you the money.",2,95.3,2
iphoneuse,Individual telephone use,3,0.0,3
hphoneuse,Household telephone use,3,0.0,3
ll,Resp has a landline,2,0.0,0
cp,Resp has a cell phone,2,0.0,0
cellweight,Weight for cell sample,174,25.1,0
weight,Final Weight,193,0.0,0

================== Apr17: all 178 variables

,question text,unique values,% missing,labelled codes
variable,,,,
psraid,Unique ID,1501,0.0,0
sample,Sample type,2,0.0,4
int_date,Interview date,7,0.0,0
fcall,Date of first call to number,5,0.0,0
attempts,Total attempts to number,9,0.0,0
refusal,Refusal Conversion,2,0.0,2
ilang,Language of interview,2,0.0,2
version,Revisions to questionnaire,3,0.0,3
cregion,Final Census Region after zip/fips merges,4,0.0,4
state,Final State code after zip/fips merges,51,0.0,51
density,Final Density code after zip/fips merges,5,0.0,2
usr,Community type,3,0.0,3
scregion,Census region - sample,4,0.0,4
sstate,State from FIPS - sample,51,0.0,51
susr,Community type - sample,4,0.0,3
stimes,Number of times to finish survey,9,0.0,0
igender,Interviewer gender,2,0.0,3
irace,Interviewer Race/Ethnicity,6,0.0,6
form,Form,2,0.0,2
llitext0,Gender randomization for landline introduction,2,75.0,2
qs1,"S1. Are you under 18 years old, OR are you 18 or older?",1,25.0,3
q1,Q.1 Do you approve or disapprove of the way Donald Trump is handling his job as President? [IF DK ENTER AS DK. IF DEPENDS PROBE ONCE WITH: Overall do you approve or disapprove of the way Donald Trump is handling his job as President?,3,0.0,3
q1a,"Q.1a Do you [approve/disapprove] very strongly, or not so strongly?",3,5.1,3
q2,"Q.2 All in all, are you satisfied or dissatisfied with the way things are going in this country today?",3,0.0,3
q3,Q.3 Do you approve or disapprove of the way Paul Ryan is handling his job as Speaker of the House?,3,0.0,3
q11f1,Q.11F1 How much confidence do you have in the future of the United States [READ IN ORDER]?,5,50.3,5
q12,"Q.12 Some people say they are basically content with the federal government, others say they are frustrated, and others say they are angry. Which of these best describes how you feel?",4,0.0,4
q13,"Q.13 How much of the time do you think you can trust the government in Washington to do what is right? Just about always, most of the time, or only some of the time?",5,0.0,5
q19f2,"Q.19F2 In making important decisions, do you think Donald Trump is [RANDOMIZE: too impulsive, too cautious], or about right?",4,64.9,4
q20f1,"Q.20F1 Overall, has Donald Trump done better than you expected as president, worse than you expected, or about as you expected?",4,50.3,4
q21bf2,"Q.21bF2 How does Donald Trump make you feel? Does he make you feel [INSERT; RANDOMIZE], or not? / happy",3,49.7,3
q21df2,"Q.21dF2 How does Donald Trump make you feel? Does he make you feel [INSERT; RANDOMIZE], or not? / worried",3,49.7,3
q25af1,"Q.25aF1 ...Please tell me whether you are very confident, somewhat confident, not too confident, or not at all confident that Trump can [INSERT ITEM; RANDOMIZE]? / Handle an international crisis",5,50.3,5
q25bf1,"Q.25bF1 ...Please tell me whether you are very confident, somewhat confident, not too confident, or not at all confident that Trump can [INSERT ITEM; RANDOMIZE]? / Manage the Executive Branch effectively",5,50.3,5
q25cf2,"Q.25cF2 ...Please tell me whether you are very confident, somewhat confident, not too confident, or not at all confident that Trump can [INSERT ITEM; RANDOMIZE]? / Work effectively with Congress",5,49.7,5
q25df2,"Q.25dF2 ...Please tell me whether you are very confident, somewhat confident, not too confident, or not at all confident that Trump can [INSERT ITEM; RANDOMIZE]? / Use military force wisely",5,49.7,5
q25ef2,"Q.25eF2 ...Please tell me whether you are very confident, somewhat confident, not too confident, or not at all confident that Trump can [INSERT ITEM; RANDOMIZE]? / Prevent major scandals in his administration?",5,49.7,5
q26,"Q.26 Would you say you trust what Donald Trump says more, about the same, or less than you trust what previous presidents said while in office?",4,0.0,4
q30f2,"Q.30F2 Compared with the Obama Administration, do you think the policies of the Trump Administration have put the United States in [READ AND RANDOMIZE OPTION 1 & 2 WITH OPTION 3 ALWAYS LAST]?",4,49.7,4
q31f1,"Q.31F1 Compared with the Obama Administration, do you think the policies of the Trump Administration have made the United States [READ AND RANDOMIZE OPTION 1 & 2 WITH OPTION 3 ALWAYS LAST]?",4,50.3,4
q32f2m1,"Q.32F2 (FIRST MENTION) What country in the world, if any, represents the greatest danger to the United States? [OPEN END; DO NOT READ; DO NOT PROBE FOR ADDITIONAL MENTIONS...]",14,49.7,14
q32f2m2,"Q.32F2 (SECOND MENTION) What country in the world, if any, represents the greatest danger to the United States? [OPEN END; DO NOT READ; DO NOT PROBE FOR ADDITIONAL MENTIONS...]",7,95.9,14
q32f2m3,"Q.32F2 (THIRD MENTION) What country in the world, if any, represents the greatest danger to the United States? [OPEN END; DO NOT READ; DO NOT PROBE FOR ADDITIONAL MENTIONS...]",6,98.9,14
q32f2m4,"Q.32F2 (FOURTH MENTION) What country in the world, if any, represents the greatest danger to the United States? [OPEN END; DO NOT READ; DO NOT PROBE FOR ADDITIONAL MENTIONS...]",5,99.6,14
q32f2m5,"Q.32F2 (FIFTH MENTION) What country in the world, if any, represents the greatest danger to the United States? [OPEN END; DO NOT READ; DO NOT PROBE FOR ADDITIONAL MENTIONS...]",1,99.9,14
q32f2m6,"Q.32F2 (SIXTH MENTION) What country in the world, if any, represents the greatest danger to the United States? [OPEN END; DO NOT READ; DO NOT PROBE FOR ADDITIONAL MENTIONS...]",1,99.9,14
q32f2m7,"Q.32F2 (SEVENTH MENTION) What country in the world, if any, represents the greatest danger to the United States? [OPEN END; DO NOT READ; DO NOT PROBE FOR ADDITIONAL MENTIONS...]",0,100.0,14
q32f2m8,"Q.32F2 (EIGHTH MENTION) What country in the world, if any, represents the greatest danger to the United States? [OPEN END; DO NOT READ; DO NOT PROBE FOR ADDITIONAL MENTIONS...]",0,100.0,14
q32f2m9,"Q.32F2 (NINTH MENTION) What country in the world, if any, represents the greatest danger to the United States? [OPEN END; DO NOT READ; DO NOT PROBE FOR ADDITIONAL MENTIONS...]",0,100.0,14
q32f2m10,"Q.32F2 (TENTH MENTION) What country in the world, if any, represents the greatest danger to the United States? [OPEN END; DO NOT READ; DO NOT PROBE FOR ADDITIONAL MENTIONS...]",0,100.0,14
q32f2m11,"Q.32F2 (ELEVENTH MENTION) What country in the world, if any, represents the greatest danger to the United States? [OPEN END; DO NOT READ; DO NOT PROBE FOR ADDITIONAL MENTIONS...]",0,100.0,14
q32f2m12,"Q.32F2 (TWELTH MENTION) What country in the world, if any, represents the greatest danger to the United States? [OPEN END; DO NOT READ; DO NOT PROBE FOR ADDITIONAL MENTIONS...]",0,100.0,14
q32f2oe1,"Q.32F2 What country in the world, if any, represents the greatest danger to the United States? [FIRST MENTION]",22,62.8,23
q32f2oe2,"Q.32F2 What country in the world, if any, represents the greatest danger to the United States? [SECOND MENTION]",6,97.2,23
q32f2oe3,"Q.32F2 What country in the world, if any, represents the greatest danger to the United States? [THIRD MENTION]",5,99.2,23
q32f2oe4,"Q.32F2 What country in the world, if any, represents the greatest danger to the United States? [FOURTH MENTION]",3,99.7,23
q32f2oe5,"Q.32F2 What country in the world, if any, represents the greatest danger to the United States? [FIFTH MENTION]",1,99.9,23
q32f2oe6,"Q.32F2 What country in the world, if any, represents the greatest danger to the United States? [SIXTH MENTION]",0,100.0,23
q32f2oe7,"Q.32F2 What country in the world, if any, represents the greatest danger to the United States? [SEVENTH MENTION]",0,100.0,23
q32f2oe8,"Q.32F2 What country in the world, if any, represents the greatest danger to the United States? [EIGHTH MENTION]",0,100.0,23
q32f2oe9,"Q.32F2 What country in the world, if any, represents the greatest danger to the United States? [NINTH MENTION]",0,100.0,23
q32f2oe10,"Q.32F2 What country in the world, if any, represents the greatest danger to the United States? [TENTH MENTION]",0,100.0,23
q32f2oe11,"Q.32F2 What country in the world, if any, represents the greatest danger to the United States? [ELEVENTH MENTION]",0,100.0,23
q32f2oe12,"Q.32F2 What country in the world, if any, represents the greatest danger to the United States? [TWELTH MENTION]",0,100.0,23
q36a,"Q.36a Is your overall opinion of [INSERT ITEM, RANDOMIZE ITEMS] very favorable, mostly favorable, mostly UNfavorable, or very unfavorable? / The Republican Party",6,0.0,7
q36b,"Q.36b Is your overall opinion of [INSERT ITEM, RANDOMIZE ITEMS] very favorable, mostly favorable, mostly UNfavorable, or very unfavorable? / The Democratic Party",7,0.0,7
q36c,"Q.36c Is your overall opinion of [INSERT ITEM, RANDOMIZE ITEMS] very favorable, mostly favorable, mostly UNfavorable, or very unfavorable? / Congress",7,0.0,7
q37a,"Q.37a Would you say the Republican Party's policies are so misguided that they threaten the nation's well-being, or wouldn't you go that far?",3,71.4,3
q37b,"Q.37b Would you say the Democratic Party's policies are so misguided that they threaten the nation's well-being, or wouldn't you go that far?",3,73.6,3
q41af1,"Q.41aF1 If you were making up the budget for the federal government this year, would you increase spending, decrease spending or keep spending the same for [INSERT...]? / Health care",4,50.3,4
q41bf1,"Q.41bF1 If you were making up the budget for the federal government this year, would you increase spending, decrease spending or keep spending the same for [INSERT...]? / Anti-terrorism defenses in the U.S.",4,50.3,4
q41cf1,"Q.41cF1 If you were making up the budget for the federal government this year, would you increase spending, decrease spending or keep spending the same for [INSERT...]? / Veterans benefits and services",4,50.3,4
q41df1,"Q.41dF1 If you were making up the budget for the federal government this year, would you increase spending, decrease spending or keep spending the same for [INSERT...]? / The State Department and American embassies",4,50.3,4
q41ef1,"Q.41eF1 If you were making up the budget for the federal government this year, would you increase spending, decrease spending or keep spending the same for [INSERT...]? / Social Security",4,50.3,4
q41ff1,"Q.41fF1 If you were making up the budget for the federal government this year, would you increase spending, decrease spending or keep spending the same for [INSERT...]? / Rebuilding highways, bridges and roads",4,50.3,4
q41gf1,"Q.41gF1 If you were making up the budget for the federal government this year, would you increase spending, decrease spending or keep spending the same for [INSERT...]? / Economic assistance to needy people in the U.S.",4,50.3,4
q41hf2,"Q.41hF2 If you were making up the budget for the federal government this year, would you increase spending, decrease spending or keep spending the same for [INSERT...]? / Scientific research",4,49.7,4
q41if2,"Q.41iF2 If you were making up the budget for the federal government this year, would you increase spending, decrease spending or keep spending the same for [INSERT...]? / Military defense",4,49.7,4
q41jf2,"Q.41jF2 If you were making up the budget for the federal government this year, would you increase spending, decrease spending or keep spending the same for [INSERT...]? / Government assistance for the unemployed",4,49.7,4
q41kf2,"Q.41kF2 If you were making up the budget for the federal government this year, would you increase spending, decrease spending or keep spending the same for [INSERT...]? / Medicare",4,49.7,4
q41lf2,"Q.41lF2 If you were making up the budget for the federal government this year, would you increase spending, decrease spending or keep spending the same for [INSERT...]? / Environmental protection",4,49.7,4
q41mf2,"Q.41mF2 If you were making up the budget for the federal government this year, would you increase spending, decrease spending or keep spending the same for [INSERT...]? / Economic assistance to needy people around the world",4,49.7,4
q41nf2,"Q.41nF2 If you were making up the budget for the federal government this year, would you increase spending, decrease spending or keep spending the same for [INSERT...]? / Education",4,49.7,4
q42f1,Q.42F1 Do you think the Trump administration is doing [READ; RANDOMIZE 1 AND 2; 3 ALWAYS LAST] to work with Democrats in Congress?,4,50.3,4
q43f2,Q.43F2 Do you think Democrats in Congress are doing [READ; RANDOMIZE 1 AND 2; 3 ALWAYS LAST] to work with the Trump administration?,4,49.7,4
q46f2,Q.46F2 Do you think that coverage of Islam (is-LAM) and Muslims by American news organizations is generally fair or unfair?,4,49.7,4
q47f1,"Q.47F1 In your own view, are the American people as a whole generally friendly, neutral, or unfriendly toward Muslim Americans?",4,50.3,4
q48,"Q.48 Do you think of Islam as part of mainstream American society, or is it not part of mainstream American society?",4,0.0,4
q49,"Q.49 Do you think there is a natural conflict between the teachings of Islam and democracy, or don't you think so?",3,0.0,3
q50f1,"Q.50F1 And just in your own words, why do you think there is a natural conflict between the teachings of Islam and democracy? [OPEN-END; RECORD VERBATIM RESPONSE; IF MORE THAN ONE MENTION RECORD UP TO THREE RESPONSES...]",2,79.1,2
q50f1oe_1,"Q50 open end - first mention - And just in your own words, why do you think there is a natural conflict between the teachings of Islam and democracy?",13,79.1,14
q50f1oe_2,"Q50 open end - second mention - And just in your own words, why do you think there is a natural conflict between the teachings of Islam and democracy?",2,99.7,14
q55f2,"Q.55F2 If you had to choose, would you rather have a smaller government providing fewer services, or a bigger government providing more services?",4,49.7,4
q56a,Q.56a The Republican Party. Do you think the Republican Party [INSERT ITEM; RANDOMIZE] or not? / Is too extreme,3,0.0,3
q56b,Q.56b The Republican Party. Do you think the Republican Party [INSERT ITEM; RANDOMIZE] or not? / Can do a good job managing the federal government,3,0.0,3
q56c,Q.56c The Republican Party. Do you think the Republican Party [INSERT ITEM; RANDOMIZE] or not? / Has good policy ideas,3,0.0,3
q56d,Q.56d The Republican Party. Do you think the Republican Party [INSERT ITEM; RANDOMIZE] or not? / Has high ethical standards,3,0.0,3
q57a,Q.57a The Democratic Party. Do you think the Democratic Party [INSERT ITEM; RANDOMIZE] or not? / Is too extreme,3,0.0,3
q57b,Q.57b The Democratic Party. Do you think the Democratic Party [INSERT ITEM; RANDOMIZE] or not? / Can do a good job managing the federal government,3,0.0,3
q57c,Q.57c The Democratic Party. Do you think the Democratic Party [INSERT ITEM; RANDOMIZE] or not? / Has good policy ideas,3,0.0,3
q57d,Q.57d The Democratic Party. Do you think the Democratic Party [INSERT ITEM; RANDOMIZE] or not? / Has high ethical standards,3,0.0,3
q61af1,Q.61aF1 Which party could do a better job of [INSERT ITEM; RANDOMIZE; OBSERVE FORM SPLITS]? / Dealing with the economy,5,50.3,5
q61bf1,Q.61bF1 Which party could do a better job of [INSERT ITEM; RANDOMIZE; OBSERVE FORM SPLITS]? / Dealing with the terrorist threat at home,5,50.3,5
q61cf1,Q.61cF1 Which party could do a better job of [INSERT ITEM; RANDOMIZE; OBSERVE FORM SPLITS]? / Dealing with the environment,5,50.3,5
q61df1,Q.61dF1 Which party could do a better job of [INSERT ITEM; RANDOMIZE; OBSERVE FORM SPLITS]? / Dealing with policies on abortion and contraception,5,50.3,5
q61ef1,Q.61eF1 Which party could do a better job of [INSERT ITEM; RANDOMIZE; OBSERVE FORM SPLITS]? / Dealing with taxes,5,50.3,5
q61ff1,Q.61fF1 Which party could do a better job of [INSERT ITEM; RANDOMIZE; OBSERVE FORM SPLITS]? / Dealing with education policy,5,50.3,5
q61gf2,Q.61gF2 Which party could do a better job of [INSERT ITEM; RANDOMIZE; OBSERVE FORM SPLITS]? / Dealing with immigration,5,49.7,5
q61hf2,Q.61hF2 Which party could do a better job of [INSERT ITEM; RANDOMIZE; OBSERVE FORM SPLITS]? / Making wise decisions about foreign policy,5,49.7,5
q61if2,Q.61iF2 Which party could do a better job of [INSERT ITEM; RANDOMIZE; OBSERVE FORM SPLITS]? / Dealing with health care,5,49.7,5
q61jf2,Q.61jF2 Which party could do a better job of [INSERT ITEM; RANDOMIZE; OBSERVE FORM SPLITS]? / Representing your views on government spending,5,49.7,5
q61kf2,Q.61kF2 Which party could do a better job of [INSERT ITEM; RANDOMIZE; OBSERVE FORM SPLITS]? / Reflecting your views about gun policy,5,49.7,5
q61lf2,Q.61lF2 Which party could do a better job of [INSERT ITEM; RANDOMIZE; OBSERVE FORM SPLITS]? / Dealing with trade agreements between the U.S and other countries,5,49.7,5
q62f1,"Q.62F1 Thinking about the Republican Party these days, do you think it is [READ AND RANDOMIZE] in its views on issues and vision for the future?",3,50.3,3
q63f2,"Q.63F2 Thinking about the Democratic Party these days, do you think it is [READ AND RANDOMIZE] in its views on issues and vision for the future?",3,49.7,3
q65f2,Q.65F2 How fair do you think our present federal tax system is? Overall would you say that our tax system is [READ IN ORDER],5,49.7,5
q66f1,"Q.66F1 Considering what you get from the federal government, do you think you pay more than your fair share of taxes, less than your fair share, or about the right amount?",4,50.3,4
q67a,"Q.67a Please tell me how much, if at all, each of the following bothers you about the federal tax system? First, [INSERT ITEM; RANDOMIZE] does this bother you a lot, some, not too much, or not at all? / The amount you pay in taxes",5,0.0,5
q67b,"Q.67b Please tell me how much, if at all, each of the following bothers you about the federal tax system? First, [INSERT ITEM; RANDOMIZE] does this bother you a lot, some, not too much, or not at all? / The complexity of the tax system",5,0.0,5
q67c,"Q.67c Please tell me how much, if at all, each of the following bothers you about the federal tax system? First, [INSERT ITEM; RANDOMIZE] does this bother you a lot, some.../ The feeling that some wealthy people don't pay their fair share",5,0.0,5
q67d,"Q.67d Please tell me how much, if at all, each of the following bothers you about the federal tax system? First, [INSERT ITEM; RANDOMIZE] does this bother you a lot, some.../ The feeling that some poor people don't pay their fair share",5,0.0,5
q67e,"Q.67e Please tell me how much, if at all, each of the following bothers you about the federal tax system? First, [INSERT ITEM; RANDOMIZE] does this bother you a lot, some.../ The feeling that some corporations don't pay their fair share",5,0.0,5
q70,"Q.70 Do you think the U.S. has a responsibility to accept refugees from Syria into the country, or do you think the U.S. does NOT have a responsibility to do this?",3,29.2,3
q71,"Q.71 In general, do you think that free trade agreements between the U.S. and other countries have been a good thing or a bad thing for the United States?",3,0.0,3
q72,"Q.72 Thinking about the financial situation of you and your family… Do you think free trade agreements have definitely helped, probably helped, probably hurt, or definitely hurt the financial situation of you and your family?",6,0.0,6
q80,"Q.80 What do you think is more important – to protect the right of Americans to own guns, OR to control gun ownership?",3,0.0,3
q81,"Q.81 In your opinion, which generally has more to do with why a person is rich [READ AND RANDOMIZE]?",4,0.0,4
q82,"Q.82 How much, if anything, have you read or heard about the U.S. conducting missile strikes against Syria in response to reports that the Syrian government used chemical weapons? Have you heard … [READ]",4,29.2,4
q83,Q.83 Do you approve or disapprove of the U.S. conducting missile strikes against Syria in response to reports that the Syrian government used chemical weapons?,3,29.2,3
q84,"Q.84 Do you think Donald Trump has a clear plan for dealing with the situation in Syria, or don’t you think so?",3,29.2,3
q92a,"Q.92a Just your impression, in the United States today, is there a lot of discrimination against [INSERT; RANDOMIZE], or not? / Muslims",3,0.0,3

================== Typology17: all 163 variables

,question text,unique values,% missing,labelled codes
variable,,,,
mergeid,Unique ID after merge,5009,0.0,0
sample,Sample type,2,0.0,4
int_date,Interview date,23,0.0,0
phase,Project phase,2,0.0,2
fcall,,19,0.0,0
attempts,,12,0.0,0
refusal,,2,0.0,0
stimes,Number of times to finish survey,12,0.0,0
ilang,Language of interview,2,0.0,2
p1version,Revisions to Phase A questionnaire,2,50.0,2
cregion,Final Census Region after zip/fips merges,4,0.0,4
state,Final State code after zip/fips merges,51,0.0,51
density,Final Density code after zip/fips merges,5,0.0,2
usr,Community type,3,0.0,3
scregion,Census region - sample,4,0.0,4
sstate,State from FIPS - sample,51,0.0,51
susr,Community type - sample,4,0.0,3
igender,Interviewer gender,2,0.0,3
irace,Interviewer Race/Ethnicity,6,0.0,6
llitext1,TEXT INSERT FOR LL INTRO,2,74.9,2
llitext2,Gender randomization for landline introduction,2,74.9,2
qs1,"S1. Are you under 18 years old, OR are you 18 or older?",1,25.1,3
cpitext1,TEXT INSERT FOR CP INTRO 1,2,25.1,2
cpitext2,TEXT INSERT FOR CP INTRO 2,2,25.1,2
qa1,Q.A1 Do you approve or disapprove of the way Donald Trump is handling his job as President? [IF DK ENTER AS DK. IF DEPENDS PROBE ONCE WITH: Overall do you approve or disapprove of the way Donald Trump is handling his job as President?...,3,50.0,3
qa1a,"Q.A1a Do you [approve/disapprove] very strongly, or not so strongly?",3,52.7,3
qb2,"Q.B2 All in all, are you satisfied or dissatisfied with the way things are going in this country today?",3,50.0,3
qb3,"Q.B3 In general, would you say life in America today is better, worse, or about the same as it was fifty years ago for people like you?",4,50.0,4
qb4,"Q.B4 Do you think the future of the next generation of Americans will be better, worse, or about the same as life today?",4,50.0,4
qa12,Q.A12 Would you prefer to live in [INSERT ITEM; RANDOMIZE]?,3,50.0,3
qa14a,"Q.A14a Next, (is/are) [INSERT ITEM, RANDOMIZE] having a positive or negative effect on the way things are going in the country these days? How about... / Labor unions",4,50.0,4
qa14b,"Q.A14b Next, (is/are) [INSERT ITEM, RANDOMIZE] having a positive or negative effect on the way things are going in the country these days? How about... / Churches and religious organizations",4,50.0,4
qa14c,"Q.A14c Next, (is/are) [INSERT ITEM, RANDOMIZE] having a positive or negative effect on the way things are going in the country these days? How about... / Colleges and universities",4,50.0,4
qa14d,"Q.A14d Next, (is/are) [INSERT ITEM, RANDOMIZE] having a positive or negative effect on the way things are going in the country these days? How about... / Banks and other financial institutions",4,50.0,4
qa14e,"Q.A14e Next, (is/are) [INSERT ITEM, RANDOMIZE] having a positive or negative effect on the way things are going in the country these days? How about... / The national news media",4,50.0,4
qa15a,"Q.A15a Would you say your overall opinion of... [INSERT ITEM; RANDOMIZE] is very favorable, mostly favorable, mostly UNfavorable, or very unfavorable? / The Republican Party",7,50.0,7
qa15b,"Q.A15b Would you say your overall opinion of... [INSERT ITEM; RANDOMIZE] is very favorable, mostly favorable, mostly UNfavorable, or very unfavorable? / The Democratic Party",7,50.0,7
qb18a,Q.B18a How well does [INSERT ITEM; RANDOMIZE] represent your values [READ IN ORDER]? / The Republican Party,5,50.0,5
qb18b,Q.B18b How well does [INSERT ITEM; RANDOMIZE] represent your values [READ IN ORDER]? / The Democratic Party,5,50.0,5
q25a,Q.25a. Government is almost always wasteful and inefficient [OR] Government often does a better job than people give it credit for,4,50.0,4
q25b,Q.25b Government regulation of business is necessary to protect the public interest [OR] Government regulation of business usually does more harm than good,4,0.0,4
q25c,Q.25c Poor people today have it easy because they can get government benefits without doing anything in return [OR] Poor people have hard lives because government benefits don't go far enough to help them live decently,4,0.0,4
q25d,"Q.25d. The government should do more to help needy Americans, even if it means going deeper into debt [OR] The government today can't afford to do much more to help the needy",4,50.0,4
q25f,Q.25f. Racial discrimination is the main reason why many black people can't get ahead these days [OR] Blacks who can't get ahead in this country are mostly responsible for their own condition,4,50.0,4
q25g,"Q.25g. Immigrants today strengthen our country because of their hard work and talents [OR] Immigrants today are a burden on our country because they take our jobs, housing and health care",4,0.0,4
q25i,Q.25i. The best way to ensure peace is through military strength [OR] Good diplomacy is the best way to ensure peace,4,50.0,4
q25k,Q.25k. Most people who want to get ahead can make it if they're willing to work hard [OR] Hard work and determination are no guarantee of success for most people,4,0.0,4
q25n,Q.25n. Business corporations make too much profit [OR] Most corporations make a fair and reasonable amount of profit,4,0.0,4
q25p,Q.25p Americans need to sacrifice some privacy and freedoms in order to be safe from terrorism [OR] Americans do NOT need to sacrifice privacy and freedoms in order to be safe from terrorism,4,50.0,4
qa26,"Q.A26 And in your view, has this country been successful more because of its [INSERT ITEM; RANDOMIZE] or more because of its [ITEM]?",3,50.0,3
qa27,"Q.A27 Thinking about your close friends, would you say [READ; READ IN REVERSE ORDER FOR 1/2 SAMPLE]? [INTERVIEWER INSTRUCTION: If necessary, define college degree as a bachelor's degree from a four-year college or university]",4,50.0,4
qb27,"Q.B27 Since Donald Trump's election, would you say you are paying [RANDOMIZE more/less, less/more] or about the same amount of attention to politics as you used to?",4,50.0,4
qb28,"Q.B28 When you talk about politics with people who have a different opinion of Donald Trump than you do, would you say you generally find it to be [READ AND RANDOMIZE]?",4,50.0,4
qb29,"Q.B29 Have you lived in or near your local community your entire life, aside from the time you may have spent away in school or college, or have you lived in other places?",4,50.0,4
qa30,"Q.A30 Thinking about the way things are going in politics today ... on the issues that matter to you would you say your side has been winning more often than it's been losing, or losing more often than it's been winning?",5,50.0,5
qb30,"Q.B30 If you had to choose, would you rather have a smaller government providing fewer services, or a bigger government providing more services?",4,50.0,4
qb31,Q.B31 Do you think U.S. involvement in the global economy [READ AND RANDOMIZE]?,4,50.0,4
oftvote,OFTVOTE How often would you say you vote...[READ IN ORDER]?,7,0.0,7
qb32,"Q.B32 How much, if at all, does it matter to you which party wins control of Congress next year? Does it matter [READ IN ORDER]?",5,50.0,5
qb33,"Q.B33 If the elections for U.S. Congress were being held TODAY, would you vote for [RANDOMIZE: 'the Republican Party's candidate' OR 'the Democratic Party's candidate'] for Congress in your district?",4,50.0,4
qb33a,"Q.B33a As of TODAY, would you LEAN more to [READ IN SAME ORDER AS Q.B33; IF NECESSARY: 'for U.S. Congress in your district']?",4,92.3,4
cheat,Congressional trial heat combined with leaners - Phase B registered voters,4,59.0,4
qa36a,Q.A36a The Republican Party. Do you think the Republican Party [INSERT ITEM; RANDOMIZE] or not? / Is too extreme,3,50.0,3
qa36b,Q.A36b The Republican Party. Do you think the Republican Party [INSERT ITEM; RANDOMIZE] or not? / Has high ethical standards,3,50.0,3
qa36c,"Q.A36c The Republican Party. Do you think the Republican Party [INSERT ITEM; RANDOMIZE] or not? / Is too willing to cut government programs, even when they work",3,50.0,3
qa36d,Q.A36d The Republican Party. Do you think the Republican Party [INSERT ITEM; RANDOMIZE] or not? / Cares about the middle class,3,50.0,3
qa37a,Q.A37a The Democratic Party. Do you think the Democratic Party [INSERT ITEM; RANDOMIZE] or not? / Is too extreme,3,50.0,3
qa37b,Q.A37b The Democratic Party. Do you think the Democratic Party [INSERT ITEM; RANDOMIZE] or not? / Has high ethical standards,3,50.0,3
qa37c,Q.A37c The Democratic Party. Do you think the Democratic Party [INSERT ITEM; RANDOMIZE] or not? / Too often sees government as the only way to solve problems,3,50.0,3
qa37d,Q.A37d The Democratic Party. Do you think the Democratic Party [INSERT ITEM; RANDOMIZE] or not? / Cares about the middle class,3,50.0,3
q40,Q.40 Would you say you follow what's going on in government and public affairs [READ]?,5,0.0,5
qb42a,"Q.B42a Is your overall opinion of [INSERT NAME; RANDOMIZE] very favorable, mostly favorable, mostly UNfavorable, or very unfavorable? / Donald Trump",6,50.0,7
qb42b,"Q.B42b Is your overall opinion of [INSERT NAME; RANDOMIZE] very favorable, mostly favorable, mostly UNfavorable, or very unfavorable? / Mike Pence",7,50.0,7
qb42c,"Q.B42c Is your overall opinion of [INSERT NAME; RANDOMIZE] very favorable, mostly favorable, mostly UNfavorable, or very unfavorable? / Barack Obama",6,50.0,7
qb42d,"Q.B42d Is your overall opinion of [INSERT NAME; RANDOMIZE] very favorable, mostly favorable, mostly UNfavorable, or very unfavorable? / Hillary Clinton",7,50.0,7
qb46,Q.B46 Do you think that Donald Trump has changed the Republican Party [RANDOMIZE: for the better/for the worse] or don't you think he has changed the Republican Party much either way?,4,50.0,4
q50r,Q.50r Stricter environmental laws and regulations cost too many jobs and hurt the economy [OR] Stricter environmental laws and regulations are worth the cost,4,0.0,4
q50u,Q.50u. Homosexuality should be accepted by society [OR] Homosexuality should be discouraged by society,4,0.0,4
q50y,Q.50y. I'm generally satisfied with the way things are going for me financially [OR] I'm not very satisfied with my financial situation,4,50.0,4
q50aa,Q.50aa It IS NOT necessary to believe in God in order to be moral and have good values [OR] It IS necessary to believe in God in order to be moral and have good values,4,0.0,4
q50cc,"Q.50cc. In foreign policy, the U.S. should take into account the interests of its allies even if it means making compromises... [OR] In foreign policy, the U.S. should follow its OWN national interests even when its allies strongly disagree",4,0.0,4
q50ee,Q.50ee. It's best for the future of our country to be active in world affairs [OR] We should pay less attention to problems overseas and concentrate on problems here at home,4,0.0,4
q50hh,Q.50hh. Our country has made the changes needed to give blacks equal rights with whites [OR] Our country needs to continue making changes to give blacks equal rights with whites,4,0.0,4
qbx,"Q.BX How big a problem, if at all, is economic inequality in this country today? Is it [READ IN ORDER]",5,50.0,5
qe2,"E.2 Are you now enrolled in school, either full or part-time, or not?",4,50.0,4
qe1,E.1 Are you now currently retired?,5,50.0,5
qe3,"E.3 [Some people who have retired do some type of work for pay.../Some students also do some type of work for pay/Some people who are disabled do some type of work for pay... ] Are you now employed full-time, part-time or not employed?",4,50.0,4
employ1,"EMPLOY1 Are you currently looking for work, or not?",3,81.3,3
employ7,"EMPLOY7 Would you prefer to be working full time, or not?",3,92.9,3
qe11,"E.11 Could your household cover expenses if you had to live ONLY off of savings for three months? (IF YES, ASK:) Could your household live off savings for six months?",4,50.0,4
q51jj,Q.51jj. Religion should be kept separate from government policies [OR] Government policies should support religious values and beliefs,4,50.0,4
q51ll,Q.51ll. The economic system in this country unfairly favors powerful interests [OR] The economic system in this country is generally fair to most Americans,4,0.0,4
q51mm,Q.51mm. I like elected officials who make compromises with people they disagree with [OR] I like elected officials who stick to their positions,4,50.0,4
q51nn,Q.51nn. The obstacles that once made it harder for women than men to get ahead are now largely gone [OR] There are still significant obstacles that make it harder for women to get ahead than men,4,0.0,4
q51pp,Q.51pp. There are clear solutions to most big issues facing the country today [OR] Most big issues facing the country today don't have clear solutions,4,50.0,4
q51qq,"Q.51qq. America's openness to people from all over the world is essential to who we are as a nation [OR] If America is too open to people from all over the world, we risk losing our identity as a nation",4,50.0,4
q51rr,Q.51rr. Voting gives people like me some say about how government runs things [OR] Voting by people like me doesn't really affect how government runs things,4,50.0,4
qb52,"Q.B52 In general, would you say people with expertise on a subject are [READ AND RANDOMIZE]?",3,50.0,3
qb52x,"Q.B52x Which do you think is the better way to improve the job situation in this country? [READ, RANDOMIZE]",3,50.0,3
qb53a,"Q.B53a Thinking about the last year...Please tell me if you have done any of the following. First, over the last year have you... / Worked or volunteered for a political candidate or campaign",3,50.0,3
qb53b,"Q.B53b Thinking about the last year...Please tell me if you have done any of the following. First, over the last year have you... / Contacted any elected official",3,50.0,3
qb53c,"Q.B53c Thinking about the last year...Please tell me if you have done any of the following. First, over the last year have you... / Contributed money to a candidate running for public office, or to a group working to elect a candidate",3,50.0,3
qb54,"Q.B54 And since the November presidential election, have you attended a political event, rally or organized protest, or have you not attended any of these types of events since then?",3,50.0,3
qb54a,"Q.B54a And would you say this has been [READ]? [IF NECESSARY: Would you say you have attended events, rallies or protests since the November election [READ]]?",5,92.3,5
qb55a,"Q.B55a [And] If a friend of yours told you they voted for [INSERT ITEM; RANDOMIZE], do you think this would... / Donald Trump",4,50.0,4
qb55b,"Q.B55b [And] If a friend of yours told you they voted for [INSERT ITEM; RANDOMIZE], do you think this would... / Hillary Clinton",4,50.0,4
qa62,Q.A62 Which of these statements best describes your opinion about the United States? [READ IN ORDER; REVERSE ORDER FOR HALF OF SAMPLE],4,50.0,4
qa77,"Q.A77 From what you've read and heard, is there solid evidence that the average temperature on earth has been getting warmer over the past few decades, or not?",4,50.0,4
qa77a,Q.A77a Do you believe that the earth is getting warmer [READ AND RANDOMIZE]?,3,63.3,3
qa77b,Q.A77b Do you think that we just don't know enough yet about whether the Earth is getting warmer or do you think it's just not happening?,3,88.1,3
qa78,Q.A78 Which is the bigger problem for the country today? [RANDOMIZE OPTIONS],3,50.0,3
qb80,"Q.B80 When it comes to the economy, which comes closer to your view? [READ AND RANDOMIZE]",3,50.0,3
qa126,"Q.A126 Do you think it is the responsibility of the federal government to make sure all Americans have health care coverage, or is that not the responsibility of the federal government?",3,50.0,3
qa126a,Q.A126a Should health insurance [READ AND RANDOMIZE]?,3,70.4,3
qa126b,Q.A126b Should the government [READ AND RANDOMIZE]?,3,80.4,3
qa127,"Q.A127 Next, all systems of justice make mistakes, but which do you think is worse: to convict an innocent person or to let a guilty person go free?",4,50.0,4
qa128,"Q.A128 Do you strongly favor, favor, oppose, or strongly oppose allowing gays and lesbians to marry legally?",5,50.0,5
qa129,"Q.A129 Do you think abortion should be [READ IN ORDER TO RANDOM HALF OF SAMPLE, IN REVERSE ORDER TO OTHER HALF OF SAMPLE]?",5,50.0,5
qa143,Q.A143 Which statement comes closer to your own views even if neither is exactly right? [READ],4,50.0,4
ideoconsist,Ideoconsist variable - Combining consCount10 and libCount10 - Phase A,21,50.0,0
typogroups,Final typology groups,9,0.0,9
sex,SEX. Respondent's sex [DO NOT ASK],2,0.0,2
age,AGE. What is your age?,81,0.0,2
educ2,EDUC2. What is the highest level of school you have completed or the highest degree you have received? [DO NOT READ] [INTERVIEWER NOTE: Enter code 3-HS grad if R completed training that did NOT count toward a degree],9,0.0,9
hisp,"HISP. Are you of Hispanic, Latino, or Spanish origin, such as Mexican, Puerto Rican or Cuban?",3,0.0,3
racecmb,Combining Race,6,0.0,6
racethn,Race/Ethnicity,4,2.1,5
racethn2,Race/Ethnicity with nativity for Hispanics,6,0.0,6
birth_hisp,"BIRTH_HISP. Were you born in the United States, on the island of Puerto Rico, or in another country?",4,88.3,4
usborn,USBORN Were you born in the United States or in another country?,4,11.7,5
marital,"MARITAL Are you currently married, living with a partner, divorced, separated, widowed, or have you never been married? [IF R SAYS 'SINGLE,' PROBE TO DETERMINE WHICH CATEGORY IS APPROPRIATE]",7,50.0,7
citizen,"CITIZEN. Are you a citizen of the United States, or not?",3,88.8,3
relig,"RELIG. What is your present religion, if any? Are you Protestant, Roman Catholic, Mormon, Orthodox such as Greek or Russian Orthodox, Jewish, Muslim, Buddhist, Hindu, atheist, agnostic, something else, or nothing in particular?",15,0.0,15
chr,"CHR. Do you think of yourself as a Christian or not? [IF R NAMED A NON-CHRISTIAN RELIGION IN PREVIOUS QUESTION (e.g. Native American, Wiccan, Pagan, etc.), DO NOT READ (ENTER 'NO' CODE 2)]",3,94.9,3
born,"BORN. Would you describe yourself as a 'born again' or evangelical Christian, or not?",3,30.4,3
attend,"ATTEND. Aside from weddings and funerals, how often do you attend religious services... more than once a week, once a week, once or twice a month, a few times a year, seldom, or never?",7,0.0,7
income,"INCOME. Last year, that is in 2016, what was your total family income from all sources, before taxes? Just stop me when I get to the right category. [READ]",10,0.0,10
inchi,INCHI And was your total 2016 family income before taxes [READ],3,87.0,3
reg,REG. Which of these statements best describes you? [READ IN ORDER] [INSTRUCTION: BE SURE TO CLARIFY WHETHER RESPONDENT IS ABSOLUTELY CERTAIN THEY ARE REGISTERED...],4,0.0,4
party,"PARTY. In politics TODAY, do you consider yourself a Republican, Democrat, or independent?",6,0.0,6
partyln,PARTYLN. As of today do you lean more to the Republican Party or more to the Democratic Party?,3,57.1,3
partystr,PARTYSTR Do you consider yourself a STRONG [Republican/Democrat] or NOT a strong [Republican/Democrat]?,3,42.9,3
partysum,Leaned party identification,3,0.0,3
qb166,"Q.B166 Thinking for a moment about people who consider themselves Democrats, which of these comes closer to your views about them? [READ; RANDOMIZE]",3,79.3,3
qb167,"Q.B167 Thinking for a moment about people who consider themselves Republicans, which of these comes closer to your views about them? [READ; RANDOMIZE]",3,74.9,3
qa168,"Q.A168 And would you say you [IF PARTY=1 consider yourself a Republican, IF PARTYLN=1 lean to the Republican Party], more because you are [INSERT ITEM, RANDOMIZE] or is it more because you are [INSERT ITEM]?",3,79.0,3
qa169,"Q.A169 And would you say you [IF PARTY=2 consider yourself a Democrat, IF PARTYLN=2 lean to the Democratic Party], more because you are [INSERT ITEM, RANDOMIZE] or is it more because you are [INSERT ITEM]?",3,75.4,3
ideo,"IDEO. In general, would you describe your political views as... [READ]",6,0.0,6
partyideo,Party and Ideology,6,0.0,6
hh1,"HH1. How many people, including yourself, live in your household?",9,0.0,2
hh3,"HH3. How many, including yourself, are adults, age 18 and older?",9,21.9,2
adults,# of adults in HH computed from HH1 and HH3,3,0.0,2
child,Number of children in household,9,0.0,2

================== Jan18: all 168 variables

,question text,unique values,% missing,labelled codes
variable,,,,
respid,Individual unique respondent identification number,1503,0.0,0
sample,Sample type,2,0.0,2
int_date,"Interview date (NOTE: Final interviewer date, adjusted for interviews that are done early in the AM)",7,0.0,0
fcall,Date of first call (NOTE: different from SRBI's standard fcall variable),7,0.0,0
attempt,Number of call attempts,9,0.0,0
refusal,Refusal conversion,2,0.0,2
ilang,Language interview conducted in,2,0.0,2
cregion,Census region based on self-reported zipcode,4,0.0,4
state,State based on self-reported zipcode,51,0.0,58
density,Density quintiles based on fips code from self-reported zipcode,5,0.0,2
usr,Urban-Suburban-Rural distinction - Landline from sample - Cell from respondent reported zip code,4,0.0,0
scregion,Sample Read-in Census region,4,0.0,4
sstate,State from sample,51,0.0,58
susr,Sample Read-in USR,4,0.0,0
sdensity,Sample Read-in Density3 code,5,0.0,2
igender,ISEX. I HEREBY ATTEST THAT THIS IS A TRUE AND HONEST INTERVIEW. INTERVIEWER GENDER:,2,0.0,2
ihisp1,"IHISP1. Are you, yourself, of Hispanic origin or descent, such as Mexican, Puerto Rican, Cuban, or some other Spanish background?",3,0.0,3
irace1m1,IRACE1. Which of the following describes your race? You can select as many as apply. (MENTION #1),5,0.0,5
irace1m2,IRACE1. Which of the following describes your race? You can select as many as apply. (MENTION #2),2,98.6,5
irace1m3,IRACE1. Which of the following describes your race? You can select as many as apply. (MENTION #3),1,99.8,5
irace1m4,IRACE1. Which of the following describes your race? You can select as many as apply. (MENTION #4),0,100.0,5
oisex,ISEX. I HEREBY ATTEST THAT THIS IS A TRUE AND HONEST INTERVIEW. INTERVIEWER GENDER:,2,0.0,2
oirace1m1,IRACE1. Which of the following describes your race? You can select as many as apply. (MENTION #1),5,0.0,5
oirace1m2,IRACE1. Which of the following describes your race? You can select as many as apply. (MENTION #2),2,98.6,5
oirace1m3,IRACE1. Which of the following describes your race? You can select as many as apply. (MENTION #3),1,99.8,5
oirace1m4,IRACE1. Which of the following describes your race? You can select as many as apply. (MENTION #4),0,100.0,5
oihisp1,"IHISP1. Are you, yourself, of Hispanic origin or descent, such as Mexican, Puerto Rican, Cuban, or some other Spanish background?",3,0.0,3
form,Form split,2,0.0,2
qs1,"S1. Are you under 18 years old, OR are you 18 or older?",1,25.0,3
timezone,Time zone,4,1.3,6
phtype,Sample Read-in Phone type,4,0.0,3
llitext,Sample Read-in LL intro code 2 (1 or 2),2,75.0,2
qcelhisp,Sample Read-in SSI 'Super Cell' demographics: Hispanic,3,0.0,2
qdlrpres,Sample Read-in Dialer Pre-screening,2,0.0,3
q1,"Q.1. All in all, are you satisfied or dissatisfied with the way things are going in this country today?",3,0.0,3
q2,Q.2. Do you approve or disapprove of the way Donald Trump is handling his job as President?,3,0.0,3
q2a,"Q.2a. Do you [approve/disapprove] very strongly, or not so strongly?",3,5.7,3
q5f1,"Q.5F1. Looking ahead, as far as you are concerned, do you think that 2018 will be better or worse than 2017?",3,49.9,3
q6f1,Q.6F1. Why do you think 2018 will be [better/worse]?,2,55.0,2
q6f1better_oe1,First mention Q.6F1 Why do you think 2018 will be better?,20,69.9,22
q6f1better_oe2,Second mention Q.6F1 Why do you think 2018 will be better?,0,100.0,22
q6f1better_oe3,Third mention Q.6F1 Why do you think 2018 will be better?,0,100.0,22
q6f1worse_oe1,First mention Q.6F1 Why do you think 2018 will be worse?,17,85.2,18
q6f1worse_oe2,Second mention Q.6F1 Why do you think 2018 will be worse?,0,100.0,18
q6f1worse_oe3,Third mention Q.6F1 Why do you think 2018 will be worse?,0,100.0,18
q7f2,"Q.7F2. In the long run, do you think Donald Trump will be a successful or unsuccessful president, or do you think it is too early to tell?",4,50.1,4
q8f2,"Q.8F2. Now thinking about Donald Trump's upcoming State of the Union address... Do you consider this year's State of the Union address to be MORE important than past years', LESS important, or about as important as past years'?",4,50.1,4
q11a,"Q11a. Thinking about some events that will occur in the coming year... Please tell me if you are especially looking forward to The 2018 mid-term Congressional elections, or not?",3,0.0,3
q11cf1,"Q11c.F1. Thinking about some events that will occur in the coming year... Please tell me if you are especially looking forward to The Winter Olympics, or not?",3,49.9,3
q11df2,"Q11d.F2. Thinking about some events that will occur in the coming year... Please tell me if you are especially looking forward to The Super Bowl, or not?",3,50.1,3
q11ef2,"Q11e.F2. Thinking about some events that will occur in the coming year... Please tell me if you are especially looking forward to The Academy Awards, or not?",3,50.1,3
q12,"Q.12. If the elections for U.S. Congress were being held TODAY, would you vote for [RANDOMIZE: 'the Republican Party's candidate' OR 'the Democratic Party's candidate'] for Congress in your district?",4,0.0,4
q12b,"Q.12b. As of TODAY, do you LEAN more to the...?",4,79.1,4
cheat,Congressional trial heat combined with leaners,4,19.2,4
q13,"Q.13. Would you like to see your representative in Congress be re-elected in the next congressional election, or not?",4,0.0,4
q14,"Q.14. Regardless of how you feel about your own representative, would you like to see most members of Congress re-elected in the next congressional election, or not?",3,0.0,3
q15,"Q.15. Will the issue of which party controls Congress, the Republicans or the Democrats, be a factor in your vote for Congress this year, or not?",3,0.0,3
q16,"Q.16. Do you think of your vote for Congress as a vote FOR Donald Trump, as a vote AGAINST Donald Trump, or isn't Donald Trump much of a factor in your vote?",4,0.0,4
q28a,"Q28a. Next, we’d like to ask you about how much help the federal government provides to some different groups. First, do you think the government does too much, not enough, or about the right amount for...Older people ?",4,0.0,4
q28c,"Q28c. Next, we’d like to ask you about how much help the federal government provides to some different groups. First, do you think the government does too much, not enough, or about the right amount for...Wealthy people ?",4,0.0,4
q28d,"Q28d. Next, we’d like to ask you about how much help the federal government provides to some different groups. First, do you think the government does too much, not enough, or about the right amount for...Poor people ?",4,0.0,4
q28e,"Q28e. Next, we’d like to ask you about how much help the federal government provides to some different groups. First, do you think the government does too much, not enough, or about the right amount for...Middle class people ?",4,0.0,4
q28f,"Q28f. Next, we’d like to ask you about how much help the federal government provides to some different groups. First, do you think the government does too much, not enough, or about the right amount for...Younger people ?",4,0.0,4
q30af1,"Q30a.F1. Are you very confident, somewhat confident, not too confident, or not at all confident that Trump can...Make wise decisions about the use of nuclear weapons ?",5,49.9,5
q30bf1,"Q30b.F1. Are you very confident, somewhat confident, not too confident, or not at all confident that Trump can...Make wise decisions about immigration policy ?",5,49.9,5
q30df1,"Q30d.F1. Are you very confident, somewhat confident, not too confident, or not at all confident that Trump can...Work effectively with Congress ?",5,49.9,5
q30ef2,"Q30e.F2. Are you very confident, somewhat confident, not too confident, or not at all confident that Trump can...Manage the Executive Branch effectively ?",5,50.1,5
q30ff2,"Q30f.F2. Are you very confident, somewhat confident, not too confident, or not at all confident that Trump can...Make good decisions about economic policy ?",5,50.1,5
q30gf2,"Q30g.F2. Are you very confident, somewhat confident, not too confident, or not at all confident that Trump can...Handle an international crisis ?",5,50.1,5
q39a,"Q39a. Is your overall opinion of Pope Francis very favorable, mostly favorable, mostly UNfavorable, or very unfavorable?",7,0.0,7
q39b,"Q39b. Is your overall opinion of Vladimir Putin [PRONOUNCED: 'POO-tin'] very favorable, mostly favorable, mostly UNfavorable, or very unfavorable?",7,0.0,7
q39c,"Q39c. Is your overall opinion of Benjamin Netanyahu [PRONOUNCED: 'neht-an YAH-hoo'] very favorable, mostly favorable, mostly UNfavorable, or very unfavorable?",7,0.0,7
q40af1,"Q40a.F1. As I read some pairs of opposite phrases, tell me which one best reflects your impression of Donald Trump. Trustworthy or NOT trustworthy?",4,49.9,4
q40bf2,"Q40b.F2. As I read some pairs of opposite phrases, tell me which one best reflects your impression of Donald Trump. Someone who cares about people like me or someone who DOESN'T care about people like me",4,50.1,4
q40cf2,"Q40c.F2. As I read some pairs of opposite phrases, tell me which one best reflects your impression of Donald Trump. A strong leader or NOT a strong leader",4,50.1,4
q40df1,"Q40d.F1. As I read some pairs of opposite phrases, tell me which one best reflects your impression of Donald Trump. A good communicator or NOT a good communicator?",4,49.9,4
q40ef1,"Q40e.F1. As I read some pairs of opposite phrases, tell me which one best reflects your impression of Donald Trump. Able to get things done or NOT able to get things done",4,49.9,4
q40ff1,"Q40f.F1. As I read some pairs of opposite phrases, tell me which one best reflects your impression of Donald Trump. Even tempered or NOT even tempered",4,49.9,4
q40gf2,"Q40g.F2. As I read some pairs of opposite phrases, tell me which one best reflects your impression of Donald Trump. Well informed or NOT well informed",4,50.1,4
q40hf2,"Q40h.F2. As I read some pairs of opposite phrases, tell me which one best reflects your impression of Donald Trump. Keeps his promises or DOESN'T keep his promises",4,50.1,4
q41f1,"Q.41F1. Do you think Trump has a responsibility to publicly release his tax returns, or does he not have this responsibility?",3,49.9,3
q42f2,Q.42F2. How confident are you that Donald Trump keeps his own business interests separate from the decisions he makes as president?,5,50.1,5
q43f1,"Q.43F1. This year, should the Democratic leaders in Washington...",3,49.9,3
q44f2,"Q.44F2. This year, should Donald Trump...",3,50.1,3
qa2,"Q.A2. Do you think Pope Francis represents a major change in direction for the Catholic Church, or don't you think so?",3,0.0,3
qa3,Q.A3. And do you see this as...?,4,44.1,4
qa4,"Q.A4. Just in your own view, what is the single most significant thing Pope Francis has done as pope?",3,79.0,3
qa4oe_1,What is the most significant thing Pope Francis has done as pope? FIRST MENTION,27,79.0,27
qa4oe_2,What is the most significant thing Pope Francis has done as pope? SECOND MENTION,13,98.1,27
qa4oe_3,What is the most significant thing Pope Francis has done as pope? THIRD MENTION,1,99.9,27
q45af1,"Q45a.F1. Improving the job situation ? (As I read from a list, tell me if you think each should be a top priority, important but lower priority, not too important or should it not be.)",5,49.9,5
q45bf1,"Q45b.F1. Reducing the budget deficit ? (As I read from a list, tell me if you think each should be a top priority, important but lower priority, not too important or should it not be.)",5,49.9,5
q45cf1,"Q45c.F1. Reducing crime ? (As I read from a list, tell me if you think each should be a top priority, important but lower priority, not too important or should it not be.)",5,49.9,5
q45df1,"Q45d.F1. Protecting the environment ? (As I read from a list, tell me if you think each should be a top priority, important but lower priority, not too important or should it not be.)",5,49.9,5
q45ef1,"Q45 e.F1. Reducing health care costs ? (As I read from a list, tell me if you think each should be a top priority, important but lower priority, not too important or should it not be.)",5,49.9,5
q45ff1,"Q45f.F1. Defending the country from future terrorist attacks ? (As I read from a list, tell me if you think each should be a top priority, important but lower priority, not too important or should it not be.)",5,49.9,5
q45gf1,"Q45g.F1. Dealing with global trade issues ? (As I read from a list, tell me if you think each should be a top priority, important but lower priority, not too important or should it not be.)",5,49.9,5
q45hf1,"Q45h.F1. Improving the educational system ? (As I read from a list, tell me if you think each should be a top priority, important but lower priority, not too important or should it not be.)",5,49.9,5
q45if1,"Q45i.F1. Reducing the influence of lobbyists and special interest groups in Washington ? (As I read from a list, tell me if you think each should be a top priority, important but lower priority, not too important or should it not be.)",5,49.9,5
q45nf2,"Q45n.F2. Dealing with the issue of immigration ? (As I read from a list, tell me if you think each should be a top priority, important but lower priority, not too important or should it not be.)",5,50.1,5
q45of2,"Q45o.F2. Strengthening the nation's economy ? (As I read from a list, tell me if you think each should be a top priority, important but lower priority, not too important or should it not be.)",5,50.1,5
q45pf2,"Q45p.F2. Dealing with global climate change ? (As I read from a list, tell me if you think each should be a top priority, important but lower priority, not too important or should it not be.)",5,50.1,5
q45qf2,"Q45q.F2. Taking steps to make the Social Security system financially sound ? (As I read from a list, tell me if you think each should be a top priority, important but lower priority, not too important or should it not be.)",5,50.1,5
q45rf2,"Q45r.F2. Dealing with the problems of poor and needy people ? (As I read from a list, tell me if you think each should be a top priority, important but lower priority, not too important or should it not be.)",5,50.1,5
q45sf2,"Q45s.F2. Strengthening the U.S. military ? (As I read from a list, tell me if you think each should be a top priority, important but lower priority, not too important or should it not be.)",5,50.1,5
q45tf2,"Q45t.F2. Taking steps to make the Medicare system financially sound ? (As I read from a list, tell me if you think each should be a top priority, important but lower priority, not too important or should it not be.)",5,50.1,5
q45uf2,"Q45u.F2. Addressing race relations in this country ? (As I read from a list, tell me if you think each should be a top priority, important but lower priority, not too important or should it not be.)",5,50.1,5
q45vf2,"Q45v.F2. Improving the country's roads, bridges and public transportation systems ? (As I read from a list, tell me if you think each should be a top priority, important but lower priority, not too important or should it not be.)",5,50.1,5
q45wf2,"Q45w.F2. Dealing with drug addiction ? (As I read from a list, tell me if you think each should be a top priority, important but lower priority, not too important or should it not be.)",5,50.1,5
q49,"Q49. As you may know, many immigrants who came illegally to the U.S. when they were children now have temporary legal status that is ending. Would you favor or oppose Congress passing a law granting them permanent legal status?",3,0.0,3
q50,"Q.50. As you may know, there is a proposal to substantially expand the wall along the U.S. border with Mexico. In general, do you favor or oppose this proposal?",3,0.0,3
q53,Q.53. Do you approve or disapprove of the tax law passed by Donald Trump and Congress last month?,3,0.0,3
q53a,"Q.53a. Do you [approve/disapprove] very strongly, or not so strongly?",3,14.2,3
q54,Q.54. How well do you feel you understand how the tax law might affect you and your family [READ]?,5,0.0,5
q55,"Q.55. Do you think the overall effect of the tax law on YOU AND YOUR FAMILY over the coming years will be mostly positive, mostly negative, or will it not affect you much either way?",4,0.0,4
q56,"Q.56. Do you think the overall effect of the tax law on THE COUNTRY AS A WHOLE over the coming years will be mostly positive, mostly negative, or will it not affect the country much either way?",4,0.0,4
qj22a,"Q.J22a. As I read some phrases, please tell me whether you think each one describes Pope Francis. Humble",4,79.0,4
qj22b,"Q.J22b. As I read some phrases, please tell me whether you think each one describes Pope Francis. Compassionate",4,79.0,4
qj22d,"Q.J22d. As I read some phrases, please tell me whether you think each one describes Pope Francis. Too liberal",4,79.0,4
qj22e,"Q.J22e. As I read some phrases, please tell me whether you think each one describes Pope Francis. Naive",4,79.0,4
qj29a,"QJ29a. How would you rate the job the pope is doing in Spreading the Catholic faith? Is he doing an excellent, good, only fair, or a poor job?",6,79.0,6
qj29b,"QJ29b. How would you rate the job the pope is doing in Addressing the sex abuse scandal in the Catholic Church? Is he doing an excellent, good, only fair, or a poor job?",6,79.0,6
qj29e,"QJ29e. How would you rate the job the pope is doing in Standing up for traditional moral values? Is he doing an excellent, good, only fair, or a poor job?",6,79.0,6
qj29j,"QJ29j. How would you rate the job the pope is doing in Addressing environmental issues? Is he doing an excellent, good, only fair, or a poor job?",6,79.0,6
qj29k,"QJ29k. How would you rate the job the pope is doing in Appointing new bishops and cardinals? Is he doing an excellent, good, only fair, or a poor job?",6,79.0,6
qa6,"Q.A6. How much, if anything, do you think Pope Francis has done to make the Catholic Church more accepting of homosexuality?",5,79.0,6
qa6a,"Q.A6a. And would you personally like to see Pope Francis do MORE to make the Catholic Church accepting of homosexuality, do LESS, or has he done about the right amount?",4,84.0,4
qa6b,"Q.A6b. And would you personally like to see Pope Francis do MORE to make the Catholic Church accepting of homosexuality, or not?",3,97.0,3
qa7,"Q.A7. How much, if anything, do you think Pope Francis has done to make the Catholic Church more accepting of divorce and remarriage?",5,79.0,6
qa7a,"Q.A7a. And would you personally like to see Pope Francis do MORE to make the Catholic Church accepting of divorce and remarriage, do LESS, or has he done about the right amount?",4,85.1,4
qa7b,"Q.A7b. And would you personally like to see Pope Francis do MORE to make the Catholic Church accepting of divorce and remarriage, or not?",3,96.5,3
qa8,"Q.A8. How much do the priests at your parish support Pope Francis? Would you say they are very supportive, somewhat supportive, not too supportive or not at all supportive of Pope Francis?",7,79.0,7
q72,"Q.72. How much, if anything, have you read or heard about the investigation into Russian involvement in the 2016 election?",4,0.0,4
q73,"Q.73. How confident, if at all, are you that the Justice Department special counsel Robert Mueller [PRONOUNCED: 'MULL-er'] will conduct a fair investigation into Russian involvement in the 2016 election?",5,0.0,5
q80,"Q.80. In the dispute between Israel and the Palestinians, which side do you sympathize with more, Israel or the Palestinians?",5,0.0,5
q81,"Q.81. Thinking about the situation in the Middle East these days, do you think Donald Trump is [RANDOMIZE: favoring Israel too much; favoring the Palestinians too much] or striking about the right balance?",4,0.0,4
q82,"Q.82. Do you think a way can be found for Israel and an independent Palestinian state to coexist peacefully with each other, or not?",4,0.0,4
q90,Q.90. Would you favor or oppose allowing more offshore oil and gas drilling in U.S. waters?,3,0.0,3
sex,SEX. [ENTER RESPONDENT'S SEX:],2,0.0,2
age,AGE. What is your age? [YEARS],77,0.0,2
educ,EDUC. What is the highest level of school you have completed or the highest degree you have received?,9,0.0,9

================== Mar18: all 108 variables

,question text,unique values,% missing,labelled codes
variable,,,,
masterid,Imported from sample file: Unique Respondent ID,1466,0.0,0
samptype,Sample type,2,0.0,2
ftcalldt,Date of first call attempt,7,0.0,0
numatts,Number of attempts,8,0.0,0
refcon,Refusal conversion flag,2,0.0,0
ilang,IN WHAT LANGUAGE WAS THIS INTERVIEW COMPLETED?,2,0.0,2
cregion,Census Bureau Region,4,0.0,4
STATE,State FIPS (2 digit),51,0.0,0
DENSITY,Density quintiles based on fips code from self-reported zipcode,5,0.0,0
USR,Urban-Suburban-Rural distinction - Landline from sample - Cell from respondent reported zip code,4,0.0,0
scregion,Sample Read-in Census region,4,0.0,4
sstate,State listed in sample,51,0.0,0
susr,Sample Read-in USR,4,0.0,0
sdensity,Sample Read-in Density3 code,5,0.0,0
qcendiv,Sample Read-in Census Division,9,0.0,9
igender,INTERVIEWER GENDER:,2,0.0,2
ihisp1,"Interviewer: Are you, yourself, of Hispanic origin or descent, such as Mexican, Puerto Rican, Cuban, or some other Spanish background?",3,0.0,3
irace1m1,Interviewer: Which of the following describes your race? You can select as many as apply. [READ LIST. RECORD UP TO FOUR RESPONSES IN ORDER MENTIONED],5,0.0,5
irace1m2,Interviewer: Which of the following describes your race? You can select as many as apply. [READ LIST. RECORD UP TO FOUR RESPONSES IN ORDER MENTIONED],3,97.1,5
irace1m3,Interviewer: Which of the following describes your race? You can select as many as apply. [READ LIST. RECORD UP TO FOUR RESPONSES IN ORDER MENTIONED],2,99.2,5
form,"Hidden from interviewer. Used for routing, randomly set only once, prior to Q1 (50/50 split).",2,0.0,2
rndgender,"Hidden from interviewer. Response text used for piping gender into the landline intro, randomly set only once, during initial call (50/50 split).",2,0.0,2
q1,"All in all, are you satisfied or dissatisfied with the way things are going in this country today?",3,0.0,3
q2,Do you approve or disapprove of the way Donald Trump is handling his job as President? [IF DK ENTER AS DK. IF DEPENDS PROBE ONCE WITH: Overall do you approve or disapprove of the way Donald Trump is handling his job as President?,3,0.0,3
q7a,"Do you think the U.S. is the BEST IN THE WORLD, above average, average or below average in its scientific achievements?",5,0.0,5
q7b,"Do you think the U.S. is the BEST IN THE WORLD, above average, average or below average in its political system?",5,0.0,5
q7ef1,"Do you think the U.S. is the BEST IN THE WORLD, above average, average or below average in its economy?",5,48.2,5
q7ff1,"Do you think the U.S. is the BEST IN THE WORLD, above average, average or below average in its health care?",5,48.2,5
q7gf1,"Do you think the U.S. is the BEST IN THE WORLD, above average, average or below average in its colleges and universities?",5,48.2,5
q7hf2,"Do you think the U.S. is the BEST IN THE WORLD, above average, average or below average in its public schools?",5,51.8,5
q7if2,"Do you think the U.S. is the BEST IN THE WORLD, above average, average or below average in its military?",5,51.8,5
q7jf2,"Do you think the U.S. is the BEST IN THE WORLD, above average, average or below average in its standard of living?",5,51.8,5
q12,How well would you say democracy is working in the United States today?,5,0.0,5
q14,"In general, how much trust and confidence do you have in the wisdom of the American people when it comes to making political decisions? A very great deal, a good deal, not very much, or none at all?",5,0.0,5
q15a,"Does who is president make a big difference, some difference or no difference for your own personal life?",4,0.0,4
q15bf1,"Does who is president make a big difference, some difference or no difference for the mood of the country?",4,48.2,4
q15cf1,"Does who is president make a big difference, some difference or no difference for national security?",4,48.2,4
q15df2,"Does who is president make a big difference, some difference or no difference for the standing of the United States in the world?",4,51.8,4
q15ef2,"Does who is president make a big difference, some difference or no difference for the health of the economy?",4,51.8,4
q24,How much respect do you think Donald Trump has for this country's democratic institutions and traditions?,5,0.0,5
q25a,"Thinking about the nation's economy How would you rate economic conditions in this country today as excellent, good, only fair, or poor?",5,0.0,5
q25b,"Thinking about the nation's economy A year from now, do you expect that economic conditions in the country as a whole will be better than they are at present, or worse, or just about the same as now?",4,0.0,4
q26a,"Thinking about your personal finances ... How would you rate your own personal financial situation? Would you say you are in excellent shape, good shape, only fair shape or poor shape financially?",5,0.0,5
q26b,"Thinking about your personal finances ... Over the course of the next year, do you think the financial situation of you and your family will improve a lot, improve some, get a little worse or get a lot worse?",6,0.0,6
q27a,"Does the availability of jobs in your area affect your household's financial situation a lot, a little, or not at all?",4,0.0,4
q27b,"Does how the stock market is doing affect your household's financial situation a lot, a little, or not at all?",4,0.0,4
q27df1,"Do prices for food and consumer goods affect your household's financial situation a lot, a little, or not at all?",4,48.2,4
q27ef1,"Does the cost of health care affect your household's financial situation a lot, a little, or not at all?",4,48.2,4
q27ff1,"Do real estate values in your area affect your household's financial situation a lot, a little, or not at all?",4,48.2,4
q27hf2,"Do gas prices affect your household's financial situation a lot, a little, or not at all?",4,51.8,4
q27if2,"Does the federal budget deficit affect your household's financial situation a lot, a little, or not at all?",4,51.8,4
q40a,"Would you say your overall opinion of the Republican Party is very favorable, mostly favorable, mostly UNfavorable, or very unfavorable?",7,0.0,7
q40b,"Would you say your overall opinion of the Democratic Party is very favorable, mostly favorable, mostly UNfavorable, or very unfavorable?",7,0.0,7
q40c,"Would you say your overall opinion of Congress is very favorable, mostly favorable, mostly UNfavorable, or very unfavorable?",7,0.0,7
q40d,"Would you say your overall opinion of the Supreme Court is very favorable, mostly favorable, mostly UNfavorable, or very unfavorable?",7,0.0,7
q40e,"Would you say your overall opinion of the federal government in Washington is very favorable, mostly favorable, mostly UNfavorable, or very unfavorable?",7,0.0,7
q40f,"Would you say your overall opinion of your STATE government is very favorable, mostly favorable, mostly UNfavorable, or very unfavorable?",7,0.0,7
q40g,"Would you say your overall opinion of your LOCAL government is very favorable, mostly favorable, mostly UNfavorable, or very unfavorable?",7,0.0,7
q41,What's your impression of people who do NOT approve of the job Donald Trump is doing as president?,3,59.4,3
q42,What's your impression of people who approve of the job Donald Trump is doing as president?,3,45.7,3
q46,"Thinking about spending on political campaigns and issues, which comes closer to your view [READ]?",3,0.0,3
q47,"In general, do you think new laws COULD BE written that would be effective in reducing the role of money in politics, OR don't you think any new laws would be effective?",3,0.0,3
q48,"How much, if anything, have you read or heard about Russian efforts to influence the 2016 presidential election?",4,0.0,4
q49,Do you think Russian efforts to influence the 2016 election [READ]?,5,0.0,5
q50,How confident are you that the Trump administration will make a serious effort to prevent Russia from influencing future U.S. elections? Are you? [READ],5,0.0,5
q51,Thinking about the U.S. invasion of Iraq in 2003 Do you think the U.S. made the right decision or the wrong decision in using military force in Iraq?,3,0.0,3
q52,"Overall, do you think the United States mostly succeeded or mostly failed in achieving its goals in Iraq?",3,0.0,3
q53,"Which would you prefer - to amend the Constitution so the candidate who receives the most total votes nationwide wins the election, or to keep the current system?",3,0.0,3
q55a,I like elected officials who make compromises with people they disagree with [OR] I like elected officials who stick to their positions,4,0.0,4
q55b,Ordinary Americans would do a better job solving the country's problems than elected officials [OR] Ordinary Americans would do no better solving the country's problems than elected officials,4,0.0,4
q55d,There are clear solutions to most big issues facing the country today [OR] Most big issues facing the country today don't have clear solutions,4,0.0,4
q55e,Most Americans demand more from the government than they are willing to pay taxes for [OR] Most Americans are willing to pay the taxes needed to fund services they expect government to provide,4,0.0,4
q55f,Many of the country's problems could be dealt with more effectively if U.S. presidents didn't have to worry so much about Congress or the courts [OR] It would be too risky to give U.S. presidents more power to deal directly with many of the,4,0.0,4
q59,Would you say the government is pretty much run by a few big interests looking out for themselves or that it is run for the benefit of all the people?,3,0.0,3
q61,"Should the U.S. Supreme Court base its rulings on its understanding of what the U.S. Constitution meant as it was originally written, or should the court base its rulings on its understanding of what the US Constitution means in current times?",4,0.0,4
q63,"And thinking about politics and elections, would you say that personally insulting political opponents is [READ]?",4,0.0,4
q90,"In general, do you think about politics as a struggle between right and wrong or don't you think about politics in this way?",3,0.0,3
q94,"Do you think senior members of the Trump administration definitely did, probably did, probably did NOT or definitely did NOT have improper contact with Russia during the 2016 presidential campaign?",5,0.0,5
q95,"How confident, if at all, are you that the Justice Department special counsel Robert Mueller [PRONOUNCED: MULL-er] will conduct a fair investigation into Russian involvement in the 2016 election [READ]?",5,0.0,5
sex,[ENTER RESPONDENT'S SEX:],2,0.0,2
age,What is your age? years,79,0.0,2
educ,What is the highest level of school you have completed or the highest degree you have received? [DO NOT READ] [INTERVIEWER NOTE: Enter code 3-HS grad if R completed training that did NOT count toward a degree],9,0.0,9
hisp,"HISP. Are you of Hispanic, Latino, or Spanish origin, such as Mexican, Puerto Rican or Cuban? Includes RACE backcodes",3,0.0,3
racecmb,Combining Race,6,0.0,6
racethn,Race-Ethnicity,5,0.0,5
birth_hisp,"Were you born in the United States, on the island of Puerto Rico, or in another country?",4,91.7,4
relig,"What is your present religion, if any? Are you Protestant, Roman Catholic, Mormon, Orthodox such as Greek or Russian Orthodox, Jewish, Muslim, Buddhist, Hindu, atheist, agnostic, something else, or nothing in particular?",15,0.0,15
chr,"Do you think of yourself as a Christian or not? [IF R NAMED A NON-CHRISTIAN RELIGION IN PREVIOUS QUESTION (e.g. Native American, Wiccan, Pagan, etc.), DO NOT READ (ENTER 'NO' CODE 2)]",3,91.4,3
born,"Would you describe yourself as a 'born again' or evangelical Christian, or not?",3,32.0,3
attend,"Aside from weddings and funerals, how often do you attend religious services... more than once a week, once a week, once or twice a month, a few times a year, seldom, or never?",7,0.0,7
income,"Last year, that is in 2017, what was your total family income from all sources, before taxes? Just stop me when I get to the right category. [READ]",10,0.0,10
reg,Which of these statements best describes you?,4,0.0,4
party,"In politics TODAY, do you consider yourself a Republican, Democrat, or independent?",6,0.0,6
partyln,As of today do you lean more to the Republican Party or more to the Democratic Party?,3,54.4,3
partysum,Leaned party identification,3,0.0,3
ideo,"In general, would you describe your political views as... [READ]",6,0.0,6
partyideo,Party and Ideology,6,0.0,6
hh1,"How many people, including yourself, live in your household?",9,0.0,2
hh3,"How many, including yourself, are adults, age 18 and older? Enter number 1-7",9,20.2,2
l1,Now thinking about your telephone use Do you have a working cell phone?,3,73.8,3
l1a,Does anyone in your household have a working cell phone?,3,98.4,3
c1,Now thinking about your telephone use Is there at least one telephone INSIDE your home that is currently working and is not a cell phone?,3,26.2,3
LL,Has a landline,2,0.0,2
CP,Has a cell phone,2,0.0,2
IPHONEUSE,Individual phone group,3,0.0,3
HPHONEUSE,Household phone group,3,0.0,3
cellweight,Final cell weight,588,26.2,0
weight,Final weight,1098,0.0,0

================== May18: all 123 variables

,question text,unique values,% missing,labelled codes
variable,,,,
respid,Individual unique respondent identification number,1503,0.0,0
sample,Sample type,2,0.0,2
int_date,"Interview date (NOTE: Final interviewer date, adjusted for interviews that are done early in the AM)",7,0.0,0
fcall,Date of first call (NOTE: different from SRBI's standard fcall variable),7,0.0,0
attempt,Number of call attempts,9,0.0,0
refusal,Refusal conversion,2,0.0,2
ilang,Language interview conducted in,2,0.0,2
cregion,Census region based on self-reported zipcode,4,0.0,4
state,State based on self-reported zipcode,51,0.0,58
density,Density quintiles based on fips code from self-reported zipcode,5,0.0,2
usr,Urban-Suburban-Rural distinction - Landline from sample - Cell from respondent reported zip code,4,0.0,0
scregion,Sample Read-in Census region,4,0.0,4
sstate,State from sample,51,0.0,58
susr,Sample Read-in USR,4,0.0,0
sdensity,Sample Read-in Density3 code,5,0.0,2
igender,ISEX. I HEREBY ATTEST THAT THIS IS A TRUE AND HONEST INTERVIEW. INTERVIEWER GENDER:,2,0.0,2
ihisp1,"IHISP1. Are you, yourself, of Hispanic origin or descent, such as Mexican, Puerto Rican, Cuban, or some other Spanish background?",3,0.0,3
irace1m1,IRACE1. Which of the following describes your race? You can select as many as apply. (MENTION #1),5,0.0,5
irace1m2,IRACE1. Which of the following describes your race? You can select as many as apply. (MENTION #2),1,99.8,5
irace1m3,IRACE1. Which of the following describes your race? You can select as many as apply. (MENTION #3),1,99.8,5
irace1m4,IRACE1. Which of the following describes your race? You can select as many as apply. (MENTION #4),0,100.0,5
form,Form split,2,0.0,2
llitext,Sample Read-in LL intro code 2 (1 or 2),2,75.0,2
phtype,Sample Read-in Phone type,4,0.0,3
qs1,"S1. Are you under 18 years old, OR are you 18 or older?",1,25.0,3
q1,"Q.1. All in all, are you satisfied or dissatisfied with the way things are going in this country today?",3,0.0,3
q2,Q.2. Do you approve or disapprove of the way Donald Trump is handling his job as President?,3,0.0,3
q2a,"Q.2a. Do you [approve/disapprove] very strongly, or not so strongly?",3,5.7,3
campnii,"CAMPNII. How closely have you followed news about candidates and election campaigns in your state and district? Have you followed it very closely, fairly closely, not too closely, or not at all closely?",5,0.0,5
q8,"Q.8. If the elections for U.S. Congress were being held TODAY, would you vote for [RANDOMIZE: 'the Republican Party's candidate' OR 'the Democratic Party's candidate'] for Congress in your district?",4,0.0,4
q9,"Q.9. As of TODAY, do you LEAN more to the [READ IN SAME ORDER AS Q.8; IF NECESSARY: 'for U.S. Congress in your district']?",4,82.5,4
cheat,Congressional trial heat combined with leaners,4,18.8,4
q20,"Q.20. Do you think the United States plays a more important and powerful role as a world leader today compared to 10 years ago, a less important role, or about as important a role as a world leader as it did 10 years ago?",4,0.0,4
q21,"Q.21. In terms of solving world problems, does the United States do too much, too little, or the right amount in helping solve world problems?",5,0.0,5
q22,"Q.22. In general, do you think that free trade agreements between the U.S. and other countries have been a good thing or a bad thing for the United States?",3,0.0,3
q26a,Q26a. Do you think the Republican Party Is too extreme or not?,3,0.0,3
q26b,Q26b. Do you think the Republican Party Has good policy ideas or not?,3,0.0,3
q26c,Q26c. Do you think the Republican Party Has high ethical standards or not?,3,0.0,3
q27a,Q27a. Do you think the Democratic Party Is too extreme or not?,3,0.0,3
q27b,Q27b. Do you think the Democratic Party Has good policy ideas or not?,3,0.0,3
q27c,Q27c. Do you think the Democratic Party Has high ethical standards or not?,3,0.0,3
compuse,"COMPUTERUSE. How often do you use a computer... never or almost never, some days, most days, or every day?",5,0.0,5
license,"LICENSE. Do you currently have a valid driver's license, or not?",3,0.0,3
q35,"Q35. Thinking about important issues facing the country today, overall, would you say you tend to agree with Donald Trump on...",5,0.0,5
q36,"Q36. Now thinking NOT about issues, but just about the way Donald Trump conducts himself as president, would you say you...",4,0.0,4
q40a,"Q40a. Is your overall opinion of Labor unions very favorable, mostly favorable, mostly UNfavorable, or very unfavorable?",7,0.0,7
q40b,"Q40b. Is your overall opinion of Business corporations very favorable, mostly favorable, mostly UNfavorable, or very unfavorable?",7,0.0,7
q41,Q.41. Do you think this reduction in union representation has been mostly good for working people or mostly bad for working people?,4,0.0,4
Q45,"Q.45. Do you think the U.S. has a responsibility to accept refugees into the country, or do you think the U.S. does NOT have a responsibility to do this?",3,0.0,3
Q46,"Q.46. If you had to choose, would you rather have a smaller government providing fewer services, or a bigger government providing more services?",4,0.0,4
q47,"Q.47 Right now, which ONE of the following do you think should be the more important priority for addressing America's energy supply... [READ]?",4,0.0,4
q60a,"Q60a. Thinking about Donald Trump's ability to handle a number of things, please tell me whether you are very confident, somewhat confident, not too confident, or not at all confident that Trump can Negotiate favorable trade agreements with other countries",5,0.0,5
q60b,"Q60b. Thinking about Donald Trump's ability to handle a number of things, please tell me whether you are very confident, somewhat confident, not too confident, or not at all confident that Trump can Make wise decisions about immigration policy ?",5,0.0,5
q60c,"Q60c. Thinking about Donald Trump's ability to handle a number of things, please tell me whether you are very confident, somewhat confident, not too confident, or not at all confident that Trump can Manage the Executive Branch effectively ?",5,0.0,5
q60d,"Q60d. Thinking about Donald Trump's ability to handle a number of things, please tell me whether you are very confident, somewhat confident, not too confident, or not at all confident that Trump can Handle an international crisis ?",5,0.0,5
q60ef1,"Q60ef1. Thinking about Donald Trump's ability to handle a number of things, please tell me whether you are very confident, somewhat confident, not too confident, or not at all confident that Trump can Make good appointments to the federal courts ?",5,50.0,5
q60ff1,"Q60ff1. Thinking about Donald Trump's ability to handle a number of things, please tell me whether you are very confident, somewhat confident, not too confident, or not at all confident that Trump can Use military force wisely ?",5,50.0,5
q60gf2,"Q60gf2. Thinking about Donald Trump's ability to handle a number of things, please tell me whether you are very confident, somewhat confident, not too confident, or not at all confident that Trump can Work effectively with Congress ?",5,50.0,5
q60hf2,"Q60hf2. Thinking about Donald Trump's ability to handle a number of things, please tell me whether you are very confident, somewhat confident, not too confident, or not at all confident that Trump can Make good decisions about economic policy ?",5,50.0,5
q60if2,"Q60i.F2. Thinking about Donald Trump's ability to handle a number of things, please tell me whether you are very confident, somewhat confident, not too confident, or not at all confident that Trump can Handle the situation with Iran ?",5,50.4,5
q62,"Q.62 Overall, how would you rate the ethical standards of top Trump administration officials--excellent, good, not good or poor?",5,0.0,5
q70,"Q.70. Do you strongly favor, favor, oppose or strongly oppose the death penalty for persons convicted of murder?",5,0.0,5
q71,"Q.71 As you may know, there are proposals to raise tariffs or fees on steel and aluminum that is imported into the United States from other countries. How much, if anything, have you read or heard about these proposals? Have you heard a lot, a little or no",4,0.0,4
q72,Q.72. Do you think that raising tariffs on steel and aluminum imports would be a good thing or a bad thing for the U.S.? [IF NECESSARY: tariffs or fees on steel and aluminum that is imported into the U.S. from other countries.],3,0.0,3
q73,"Q.73 On balance, do you think having an increasing number of people of many different races, ethnic groups and nationalities in the United States makes this country a better place to live, a worse place to live, or doesn't make much difference either way?",4,0.0,4
q74,"Q.74 How much, if anything, have you heard about the 2015 agreement on Iran's nuclear program between Iran, the United States and other nations? Have you heard a lot, a little or nothing at all?",4,0.0,4
q75,"Q.75 From what you know, do you approve or disapprove of this agreement? [IF NECESSARY: The agreement on Iran's nuclear program between Iran, the United States and other nations]",3,0.0,3
worryret,"WORRYRET. How worried are you right now about not having enough money for retirement... Very worried, moderately worried, not too worried, or not worried at all?",5,0.0,5
slepnhis,"SLEEP_NHIS. On average, how many hours of sleep do you get in a 24-hour period?",16,0.0,1
yaganhis,"YOGA_NHIS. During the PAST 12 MONTHS, did you practice Yoga for yourself?",3,0.0,3
smok1,SMOK1. The next question is about cigarette smoking. Have you smoked at least 100 cigarettes in your ENTIRE LIFE,3,0.0,3
smok2,"SMOK2. Do you NOW smoke cigarettes every day, some days, or not at all?",4,59.4,4
bloodpr,"BLOODPR. Have you EVER been told by a doctor or other health professional that you had hypertension, also called high blood pressure?",3,0.0,3
q80af1,"Q80a.F1. All things considered, which of these descriptions comes closest to your view of Russia today... Do you think Russia is [READ]?",4,50.0,4
q80bf2,"Q80b.F2. All things considered, which of these descriptions comes closest to your view of China today... Do you think China is [READ]?",4,50.0,4
q81,"Q.81 How much, if anything, have you heard about negotiations between the United States and North Korea on North Korea's nuclear program? Have you heard a lot, a little or nothing at all?",4,0.0,4
q82,"Q.82 From what you know, do you approve or disapprove of the United States negotiating directly with North Korea over the issue of its nuclear program?",3,0.0,3
q83,"Q.83 Do you think North Korea's leadership is serious about addressing international concerns about their country's nuclear enrichment program, or not?",3,0.0,3
sex,SEX. [ENTER RESPONDENT'S SEX:],2,0.0,2
age,AGE. What is your age? [YEARS],77,0.0,2
educ,EDUC. What is the highest level of school you have completed or the highest degree you have received? [----DO NOT READ----] [INTERVIEWER NOTE: Enter code 3-HS grad if R completed training that did NOT count toward a degree],9,0.0,9
hisp,"HISP. Are you of Hispanic, Latino, or Spanish origin, such as Mexican, Puerto Rican or Cuban?—Includes RACE backcodes",3,0.0,3
racecmb,Combining Race (with coding),6,0.0,6
racethn,Race-Ethnicity,5,0.0,5
birth_hisp,"BIRTH_HISP. Were you born in the United States, on the island of Puerto Rico, or in another country?",4,87.2,4
momborn,"MOM_BORN. Was your mother born on the island of Puerto Rico, in the United States, or in another country?",4,92.8,4
dadborn,"DADBORN. Was your father born on the island of Puerto Rico, in the United States, or in another country?",4,92.8,4
lan1,"LAN1. Would you say you can carry on a conversation in Spanish, both understanding and speaking -- very well, pretty well, just a little, or not at all?",4,87.2,5
lan2,"LAN2. Would you say you can read a newspaper or book in Spanish -- very well, pretty well, just a little, or not at all?",4,87.2,5
lan3,"LAN3. Would you say you can carry on a conversation in English, both understanding and speaking -- very well, pretty well, just a little, or not at all?",4,87.2,5
lan4,"LAN4. Would you say you can read a newspaper or book in English -- very well, pretty well, just a little, or not at all?",4,87.2,5
relig,"RELIG. What is your present religion, if any? Are you Protestant, Roman Catholic, Mormon, Orthodox such as Greek or Russian Orthodox, Jewish, Muslim, Buddhist, Hindu, atheist, agnostic, something else, or nothing in particular?",15,0.0,15
chr,"CHR. Do you think of yourself as a Christian or not? [IF R NAMED A NON-CHRISTIAN RELIGION IN PREVIOUS QUESTION (e.g. Native American, Wiccan, Pagan, etc.), DO NOT READ (ENTER 'No' CODE 2)]",3,91.3,3
born,"BORN. Would you describe yourself as a 'born again' or evangelical Christian, or not?",3,30.8,3
attend,"ATTEND. Aside from weddings and funerals, how often do you attend religious services... more than once a week, once a week, once or twice a month, a few times a year, seldom, or never?",7,0.0,7
income,"INCOME. Last year, that is in 2017, what was your total family income from all sources, before taxes? Just stop me when I get to the right category. [READ]",10,0.0,10
employ,"EMPLOY. Are you now employed full-time, part-time or not employed?",4,0.0,4
citizen,"CITIZEN. Are you a citizen of the United States, or not?",3,94.3,3
reg,REG. Which of these statements best describes you?,4,2.8,4
pvote16a,"PVOTE16A. In the 2016 presidential election between Donald Trump and Hillary Clinton, did things come up that kept you from voting, or did you happen to vote?",4,18.8,4
party,"PARTY. In politics TODAY, do you consider yourself a Republican, Democrat, or independent?",6,0.0,6
partyln,PARTYLN. As of today do you lean more to the Republican Party or more to the Democratic Party?,3,57.2,3
repjob,"REPJOB. How good a job is the Republican Party doing these days in standing up for its traditional positions on such things as reducing the size of government, cutting taxes and promoting conservative social values?",5,57.2,5
demjob,"DEMJOB. How good a job is the Democratic Party doing these days in standing up for its traditional positions on such things as protecting the interests of minorities, helping the poor and needy, and representing working people?",5,52.8,5
partysum,Leaned party identification,3,0.0,3
ideo,"IDEO. In general, would you describe your political views as... [READ]",6,0.0,6
partyideo,Party and Ideology,6,0.0,6
partysumideo,Party and Ideology,5,7.1,6
hh1,"HH1. How many people, including yourself, live in your household?",9,0.0,2
hh3,"HH3. How many, including yourself, are adults, age 18 and older?",9,22.7,2
adults,Adults in HH,3,0.0,3
empcomp,"EMPCOMP. At any time during 2017, did [you/anyone in your household] receive any State or Federal unemployment compensation?",3,0.0,3
snap,"SNAP. Did [you/anyone in your household] get food stamps or use a food stamp benefit card at any time during 2017? [INTERVIEWER NOTE: do not include benefits from WIC, the Women, Infants and Children Nutrition Program]",3,0.0,3
anycov,ANYCOV. Do you now have any type of health plan or health coverage?,3,0.0,3
homeacs,"HOME_ACS. Do you own your home, rent your home, or live there with another arrangement? [IF OWN WITH MORTGAGE OR RENT, PUNCH 1]",4,0.0,4
ql1,L1. Now thinking about your telephone use... Do you have a working cell phone?,3,75.0,3
ql1a,L1a. Does anyone in your household have a working cell phone?,3,98.3,3
qc1,C1. Now thinking about your telephone use... Is there at least one telephone INSIDE your home that is currently working and is not a cell phone?,3,25.0,3
ll,Resp has a landline,2,0.0,2
cp,Resp has a cell phone,2,0.0,2
money2,"MONEY2. That's the end of the interview. If you would like to be reimbursed for your cell phone minutes, we can send you $5. I will need your full name and a mailing address where we can send you the money? [INTERVIEWER NOTE: If R doe",2,25.0,2
cellweight,Final cellweight,786,25.0,0
weight,Final weight,1161,0.0,0

================== Jun18: all 130 variables

,question text,unique values,% missing,labelled codes
variable,,,,
respid,Individual unique respondent identification number,2002,0.0,0
sample,Sample type,2,0.0,2
int_date,"Interview date (NOTE: Final interviewer date, adjusted for interviews that are done early in the AM)",8,0.0,0
fcall,Date of first call (NOTE: different from SRBI's standard fcall variable),8,0.0,0
attempt,Number of call attempts,9,0.0,0
refusal,Refusal conversion,2,0.0,2
ilang,Language interview conducted in,2,0.0,2
cregion,Census region based on self-reported zipcode,4,0.0,4
state,State based on self-reported zipcode,51,0.0,58
density,Density quintiles based on fips code from self-reported zipcode,5,0.0,2
usr,Urban-Suburban-Rural distinction - Landline from sample - Cell from respondent reported zip code,4,0.0,0
scregion,Sample Read-in Census region,4,0.0,4
sstate,State from sample,51,0.0,58
susr,Sample Read-in USR,4,0.0,0
sdensity,Sample Read-in Density3 code,5,0.0,2
timezone,Time zone,4,0.9,6
igender,ISEX. I HEREBY ATTEST THAT THIS IS A TRUE AND HONEST INTERVIEW. INTERVIEWER GENDER:,2,0.0,2
ihisp1,"IHISP1. Are you, yourself, of Hispanic origin or descent, such as Mexican, Puerto Rican, Cuban, or some other Spanish background?",3,0.0,3
irace1m1,IRACE1. Which of the following describes your race? You can select as many as apply. (MENTION #1),5,0.0,5
irace1m2,IRACE1. Which of the following describes your race? You can select as many as apply. (MENTION #2),1,99.9,5
irace1m3,IRACE1. Which of the following describes your race? You can select as many as apply. (MENTION #3),0,100.0,5
irace1m4,IRACE1. Which of the following describes your race? You can select as many as apply. (MENTION #4),0,100.0,5
form,Form split,2,0.0,2
llitext,Sample Read-in LL intro code 2 (1 or 2),2,74.9,2
phtype,Sample Read-in Phone type,4,0.0,3
qs1,"S1. Are you under 18 years old, OR are you 18 or older?",1,25.1,3
q1,"Q.1. All in all, are you satisfied or dissatisfied with the way things are going in this country today?",3,0.0,3
q2,Q.2. Do you approve or disapprove of the way Donald Trump is handling his job as President?,3,0.0,3
q6f2,"Q.6F2. What do you think is the most important problem facing the country today? [RECORD VERBATIM RESPONSE. PROBE FOR CLARITY - DO NOT PROBE FOR ADDITIONAL MENTIONS. IF MORE THAN ONE MENTION, RECORD IN ORDER OF MENTION]",3,50.2,3
q6f2_oe1,Q.6F2 What do you think is the most important problem facing the country today? [FIRST MENTION],59,50.2,73
q6f2_oe2,Q.6F2 What do you think is the most important problem facing the country today? [SECOND MENTION],48,89.6,73
q6f2_oe3,Q.6F2 What do you think is the most important problem facing the country today? [THIRD MENTION],27,96.7,73
q7a,"Q7a. Please tell me how important each of the following issues is for the country... The investigation into alleged Russian involvement in the 2016 election very important, somewhat important, not too important or not at all important for the country?",5,0.0,5
q7b,"Q7b. Please tell me how important each of the following issues is for the country... The status of immigrants who came into the country illegally when they were children very important, somewhat important, not too important or not at all important for the",5,0.0,5
q7c,"Q7c. Please tell me how important each of the following issues is for the country... The outcome of the 2018 congressional elections very important, somewhat important, not too important or not at all important for the country?",5,0.0,5
q7df1,"Q7df1. Please tell me how important each of the following issues is for the country... The negotiations with North Korea over its nuclear program very important, somewhat important, not too important or not at all important for the country?",5,49.8,5
q7ef2,"Q7ef2. Please tell me how important each of the following issues is for the country... The issue of sexual assault and harassment very important, somewhat important, not too important or not at all important for the country?",5,50.2,5
q10a,Q.10a. Do you approve or disapprove of the job the Republican leaders in Congress are doing?,3,0.0,3
q10b,Q.10b. Do you approve or disapprove of the job the Democratic leaders in Congress are doing?,3,0.0,3
q11,"Q.11 Now thinking about all of the U.S. presidents during your lifetime, which ONE has done the best job as president?",17,0.0,17
q12,"Q.12 And which president, if any, would you name second?",16,5.2,17
campnii,"CAMPNII. How closely have you been following news about candidates and election campaigns in your state and district... very closely, fairly closely, not too closely, or not at all closely?",5,0.0,5
q20,"Q.20. If the elections for U.S. Congress were being held TODAY, would you vote for [RANDOMIZE: 'the Republican Party's candidate' OR 'the Democratic Party's candidate'] for Congress in your district?",4,0.0,4
q21,"Q.21. As of TODAY, do you LEAN more to the [READ IN SAME ORDER AS Q.20;]? [IF NECESSARY: for U.S. Congress in your district?]",4,83.1,4
cheat,Congressional trial heat combined with leaners,4,19.7,4
q25f1,Q.25F1. What one issue would you most like to hear the candidates in your state or district talk about this fall?,3,49.8,3
Q25F1_1,FIRST MENTION Q.25F1. What one issue would you most like to hear the candidates in your state or district talk about this fall?,86,49.8,105
Q25F1_2,SECOND MENTION Q.25F1. What one issue would you most like to hear the candidates in your state or district talk about this fall?,75,86.7,105
Q25F1_3,THIRD MENTION Q.25F1. What one issue would you most like to hear the candidates in your state or district talk about this fall?,45,95.3,105
q26,"Q.26. Would you like to see your representative in Congress be re-elected in the next congressional election, or not?",4,0.0,4
q27,"Q.27. Regardless of how you feel about your own representative, would you like to see most members of Congress re-elected in the next congressional election, or not?",3,0.0,3
q28,"Q.28. Compared to previous congressional elections, are you more enthusiastic about voting than usual, or less enthusiastic?",4,0.0,4
q29,"Q.29. Will the issue of which party controls Congress, the Republicans or the Democrats, be a factor in your vote for Congress this year, or not?",3,0.0,3
q30,"Q.30. Do you think of your vote for Congress as a vote FOR Donald Trump, as a vote AGAINST Donald Trump, or isn't Donald Trump much of a factor in your vote?",4,0.0,4
q31,"Q.31. Compared to recent Congresses, would you say THIS Congress has accomplished more, accomplished less, or accomplished about the same amount?",4,0.0,4
q32,Q.32 Who do you think is most to blame for this [READ]?,5,54.2,5
q38,"Q.38. Compared to the immigrants of the early 1900s, are TODAY'S immigrants... [READ]?",4,0.0,4
q39,Q.39. How much respect do you think Donald Trump has for this country's democratic institutions and traditions? [READ],5,0.0,5
q40,"Q.40. How confident, if at all, are you that Donald Trump keeps his own business interests separate from the decisions he makes as president? [READ]",5,0.0,5
q41a,"Q41a. Thinking about some different groups... how much respect do you think Donald Trump has for People like you ? A great deal, a fair amount, not too much or none at all?",5,0.0,5
q41bf1,"Q41bf1. Thinking about some different groups... how much respect do you think Donald Trump has for Women ? A great deal, a fair amount, not too much or none at all?",5,49.8,5
q41cf1,"Q41cf1. Thinking about some different groups... how much respect do you think Donald Trump has for Men ? A great deal, a fair amount, not too much or none at all?",5,49.8,5
q41df1,"Q41df1. Thinking about some different groups... how much respect do you think Donald Trump has for White people ? A great deal, a fair amount, not too much or none at all?",5,49.8,5
q41ef1,"Q41ef1. Thinking about some different groups... how much respect do you think Donald Trump has for Black people ? A great deal, a fair amount, not too much or none at all?",5,49.8,5
q41ff1,"Q41ff1. Thinking about some different groups... how much respect do you think Donald Trump has for Hispanic people ? A great deal, a fair amount, not too much or none at all?",5,49.8,5
q41gf2,"Q41gf2. Thinking about some different groups... how much respect do you think Donald Trump has for Veterans ? A great deal, a fair amount, not too much or none at all?",5,50.2,5
q41hf2,"Q41hf2. Thinking about some different groups... how much respect do you think Donald Trump has for Muslims ? A great deal, a fair amount, not too much or none at all?",5,50.2,5
q41if2,"Q41if2. Thinking about some different groups... how much respect do you think Donald Trump has for Evangelical Christians ? A great deal, a fair amount, not too much or none at all?",5,50.2,5
q41jf2,"Q41jf2. Thinking about some different groups... how much respect do you think Donald Trump has for Immigrants ? A great deal, a fair amount, not too much or none at all?",5,50.2,5
q41lf2,"Q41lf2. Thinking about some different groups... how much respect do you think Donald Trump has for People who voted for Hillary Clinton ? A great deal, a fair amount, not too much or none at all?",5,50.2,5
q42,"Q.42. Would you say you trust what Donald Trump says more, about the same, or less than you trusted what previous presidents said while in office?",4,0.0,4
q60af1,Q60af1. Which party could do a better job of Dealing with the economy ? The Republican Party or the Democratic Party?,5,49.8,5
q60bf1,Q60bf1. Which party could do a better job of Dealing with the terrorist threat at home ? The Republican Party or the Democratic Party?,5,49.8,5
q60cf1,Q60cf1. Which party could do a better job of Dealing with the environment ? The Republican Party or the Democratic Party?,5,49.8,5
q60df1,Q60df1. Which party could do a better job of Dealing with policies on abortion and contraception ? The Republican Party or the Democratic Party?,5,49.8,5
q60ef1,Q60ef1. Which party could do a better job of Dealing with taxes ? The Republican Party or the Democratic Party?,5,49.8,5
q60ff1,Q60ff1. Which party could do a better job of Dealing with drug addiction ? The Republican Party or the Democratic Party?,5,49.8,5
q60gf1,Q60gf1. Which party could do a better job of Dealing with issues involving race and ethnicity ? The Republican Party or the Democratic Party?,5,49.8,5
q60jf2,Q60jf2. Which party could do a better job of Dealing with immigration ? The Republican Party or the Democratic Party?,5,50.2,5
q60kf2,Q60kf2. Which party could do a better job of Making wise decisions about foreign policy ? The Republican Party or the Democratic Party?,5,50.2,5
q60lf2,Q60lf2. Which party could do a better job of Dealing with health care ? The Republican Party or the Democratic Party?,5,50.2,5
q60mf2,Q60mf2. Which party could do a better job of Dealing with the federal budget deficit ? The Republican Party or the Democratic Party?,5,50.2,5
q60nf2,Q60nf2. Which party could do a better job of Reflecting your views about gun policy ? The Republican Party or the Democratic Party?,5,50.2,5
q60of2,Q60of2. Which party could do a better job of Dealing with trade agreements between the U.S and other countries ? The Republican Party or the Democratic Party?,5,50.2,5
q68,"Q.68. If Democrats take control of Congress this fall, how concerned are you, if at all, that they will focus too much on investigating the Trump administration? [READ]",5,0.0,5
q69,"Q.69. If Republicans keep control of Congress this fall, how concerned are you, if at all, that they will not focus enough on oversight of the Trump administration? [READ]",5,0.0,5
q82,"Q82. As you may know, many immigrants who came illegally to the U.S. when they were children now have temporary legal status that may be ending. Would you favor or oppose Congress passing a law granting them permanent legal status?",3,0.0,3
q83,"Q.83. As you may know, there is a proposal to substantially expand the wall along the U.S. border with Mexico. In general, do you favor or oppose this proposal?",3,0.0,3
q90a,Q.90a Which comes closer to your view - even if neither is exactly right. Undocumented immigrants mostly fill jobs that American citizens would like to have [OR] Undocumented immigrants mostly fill jobs American citizens don’t want,4,0.0,4
q90c,Q.90c Undocumented immigrants living in the U.S. are more likely than American citizens to commit serious crimes [OR] Undocumented immigrants living in the U.S. are NO more likely than American citizens to commit serious crimes,4,0.0,4
q91,"Q.91. In your own view, do you feel that giving people who came to the U.S. illegally a way to gain legal status is like rewarding them for doing something wrong, or don't you think of it this way?",3,0.0,3
q92,Q.92. Just in general... how sympathetic would you say you are toward immigrants who are in the United States illegally?,5,0.0,5
q93,"Q.93 Do you think most of the immigrants who are now living in the United States are here legally, or are most of them here illegally?",4,0.0,4
q94,"Q.94. Should LEGAL immigration into the United States be kept at its present level, increased or decreased?",4,0.0,4
q100,Q.100. How often do you personally come in contact with immigrants who speak little or no English...[READ IN ORDER]?,5,0.0,5
q101,"Q.101. When that happens, does it bother you, or not bother you?",3,24.5,3
q102,"Q.102. How much, if anything, have you read or heard about the investigation into Russian involvement in the 2016 election? [READ]",4,0.0,4
q103,"Q.103. How confident, if at all, are you that the Justice Department special counsel Robert Mueller will conduct a fair investigation into Russian involvement in the 2016 election? [READ]",5,0.0,5
q104,"Q.104. How confident, if at all, are you that Donald Trump will handle matters related to the special counsel investigation appropriately? Very confident, somewhat confident, not too confident or not at all confident?",5,0.0,5
sex,SEX. [ENTER RESPONDENT'S SEX:],2,0.0,2
age,AGE. What is your age? [YEARS],78,0.0,2
educ,EDUC. What is the highest level of school you have completed or the highest degree you have received? [INTERVIEWER NOTE: Enter code 3-HS grad if R completed training that did NOT count toward a degree],9,0.0,9
hisp,"HISP. Are you of Hispanic, Latino, or Spanish origin, such as Mexican, Puerto Rican or Cuban?—Includes RACE backcodes",3,0.0,3
racecmb,Combining Race (with coding),6,0.0,6
racethn,Race-Ethnicity,5,0.0,5
birth_hisp,"BIRTH_HISP. Were you born in the United States, on the island of Puerto Rico, or in another country?",3,87.8,4
relig,"RELIG. What is your present religion, if any? Are you Protestant, Roman Catholic, Mormon, Orthodox such as Greek or Russian Orthodox, Jewish, Muslim, Buddhist, Hindu, atheist, agnostic, something else, or nothing in particular?",15,0.0,15
chr,"CHR. Do you think of yourself as a Christian or not? [IF R NAMED A NON-CHRISTIAN RELIGION IN PREVIOUS QUESTION (e.g. Native American, Wiccan, Pagan, etc.), DO NOT READ (ENTER 'No' CODE 2)]",3,93.6,3
born,"BORN. Would you describe yourself as a 'born again' or evangelical Christian, or not?",3,29.4,3
attend,"ATTEND. Aside from weddings and funerals, how often do you attend religious services... more than once a week, once a week, once or twice a month, a few times a year, seldom, or never?",7,0.0,7
income,"INCOME. Last year, that is in 2017, what was your total family income from all sources, before taxes? Just stop me when I get to the right category. [READ]",10,0.0,10
reg,REG. Which of these statements best describes you?,4,0.0,4
party,"PARTY. In politics TODAY, do you consider yourself a Republican, Democrat, or independent?",6,0.0,6
partyln,PARTYLN. As of today do you lean more to the Republican Party or more to the Democratic Party?,3,57.9,3
q105,Q.105 Do you think that Donald Trump has changed the Republican Party [RANDOMIZE: for the better/for the worse] or don't you think he has changed the Republican Party much either way?,4,58.2,4
partysum,Leaned party identification,3,0.0,3
ideo,"IDEO. In general, would you describe your political views as... [READ]",6,0.0,6
partyideo,Party and Ideology,6,0.0,6
partysumideo,Party and Ideology,5,8.1,6
hh1,"HH1. How many people, including yourself, live in your household?",9,0.0,2
hh3,"HH3. How many, including yourself, are adults, age 18 and older?",8,20.4,2
adults,Adults in HH,3,0.0,3
ql1,L1. Now thinking about your telephone use... Do you have a working cell phone?,3,74.9,3
ql1a,L1a. Does anyone in your household have a working cell phone?,3,97.0,3
qc1,C1. Now thinking about your telephone use... Is there at least one telephone INSIDE your home that is currently working and is not a cell phone?,3,25.1,3
ll,Resp has a landline,2,0.0,2
cp,Resp has a cell phone,2,0.0,2
money2,"MONEY2. That's the end of the interview. If you would like to be reimbursed for your cell phone minutes, we can send you $5. I will need your full name and a mailing address where we can send you the money?",2,25.1,2
cellweight,Final cellweight,976,25.1,0
weight,Final weight,1597,0.0,0

================== W161: all 144 variables

,question text,unique values,% missing,labelled codes
variable,,,,
QKEY,QKEY_W161. Unique identifier,5086,0.0,0
INTERVIEW_START_W161,INTERVIEW_START_W161. Interview start time,4908,0.0,0
INTERVIEW_END_W161,INTERVIEW_END_W161. Interview end time,4891,0.0,0
DEVICE_TYPE_W161,DEVICE_TYPE_W161. The device used in the latest access of the survey link,3,0.0,4
SVYMODE_W161,SVYMODE_W161. Mode of survey,2,0.0,2
LANG_W161,LANG_W161. Language of interview,2,0.0,2
FORM_W161,"X_FORM_W161. Flag to randomly assign panelists to one of two forms (Form 1, Form 2) and weight within form ATP source: Randomly assigned for each survey.",2,0.0,2
X_PARTYSUMFINAL_W161,"X_PARTYSUMFINAL_W161. Note: Flag to identify republicans, republican leaners and non-leaners. Source: Frame file variable F_PARTYSUM_FINAL. Same codes as F_PARTYSUM_FINAL.",3,0.0,3
SATIS_W161,"SATIS_W161. All in all, are you satisfied or dissatisfied with the way things are going in this country today?",3,49.7,3
YEARAHEAD_W161,"YEARAHEAD_W161. Looking ahead, as far as you are concerned, do you think that 2025 will be...",3,50.3,3
POL1DT_W161,POL1DT_W161. Do you approve or disapprove of the way Donald Trump is handling his job as president?,3,0.0,3
POL1DTSTR_W161,POL1DTSTR_W161. Do you approve/disapprove of the way Donald Trump is handling his job as president...,3,1.7,3
PRESWHERE_W161,PRESWHERE_W161. Would you say Donald Trump has clear goals for where he wants to lead the country?,3,49.7,3
DTSUCCESS_W161,"DTSUCCESS_W161. In the long run, do you think Donald Trump will be...",4,50.3,4
QUALPRES_TRMP_MF_W161,"QUALPRES_TRMP_MF_W161. Has the mental fitness needed to do the job // Thinking about the qualities needed to effectively serve another term as president, how confident are you that Donald Trump...",6,0.0,6
QUALPRES_TRMP_PHY_W161,"QUALPRES_TRMP_PHY_W161. Has the physical fitness needed to do the job // Thinking about the qualities needed to effectively serve another term as president, how confident are you that Donald Trump...",6,0.0,6
QUALPRES_TRMP_ADV_W161,"QUALPRES_TRMP_ADV_W161. Picks good advisors // Thinking about the qualities needed to effectively serve another term as president, how confident are you that Donald Trump...",6,0.0,6
QUALPRES_TRMP_ETH_W161,"QUALPRES_TRMP_ETH_W161. Acts ethically in office // Thinking about the qualities needed to effectively serve another term as president, how confident are you that Donald Trump...",6,0.0,6
QUALPRES_TRMP_RSP_W161,"QUALPRES_TRMP_RSP_W161. Respects the country's democratic values // Thinking about the qualities needed to effectively serve another term as president, how confident are you that Donald Trump...",6,0.0,6
QUALPRES_TRMP_FIRM_W161,"QUALPRES_TRMP_FIRM_W161. Has the leadership skills needed to do the job // Thinking about the qualities needed to effectively serve another term as president, how confident are you that Donald Trump...",6,0.0,6
PRES_WASH_W161,"PRES_WASH_W161. All in all, what effect will Donald Trump have on the way the federal government works in Washington? Will he...",4,49.7,4
PRES_WASH_EXP_W161,"PRES_WASH_EXP_W161. All in all, what effect will Donald Trump have on the way the federal government works in Washington? Will he make things...",4,50.3,4
PRESCAB_W161,"PRESCAB_W161. So far, would you say you approve or disapprove of Donald Trump's cabinet choices and other high-level appointments?",3,49.7,3
VP2PRES_W161,"VP2PRES_W161. As you may know, JD Vance is Vice President. Do you think that JD Vance is...",3,50.3,3
VP_INFL_W161,VP_INFL_W161. How much influence do you think JD Vance will have within the Trump administration?,4,50.3,4
ETHICSDJT_W161,"ETHICSDJT_W161. With Trump as president, do you think the overall level of ethics and honesty in the federal government will...",4,0.0,4
NATPROBS_GUN_W161,NATPROBS_GUN_W161. Gun violence // How much of a problem do you think each of the following are in the country today?,5,49.7,5
NATPROBS_INFR_W161,"NATPROBS_INFR_W161. Condition of roads, bridges and other infrastructure // How much of a problem do you think each of the following are in the country today?",5,49.7,5
NATPROBS_IMM_W161,NATPROBS_IMM_W161. Illegal immigration // How much of a problem do you think each of the following are in the country today?,5,49.7,5
NATPROBS_HC_W161,NATPROBS_HC_W161. The affordability of health care // How much of a problem do you think each of the following are in the country today?,5,49.7,5
NATPROBS_MNPOL_W161,NATPROBS_MNPOL_W161. The role of money in politics // How much of a problem do you think each of the following are in the country today?,5,49.7,5
NATPROBS_AI_W161,NATPROBS_AI_W161. The use of artificial intelligence (AI) // How much of a problem do you think each of the following are in the country today?,5,49.7,5
NATPROBS_CLIM_W161,NATPROBS_CLIM_W161. Climate change // How much of a problem do you think each of the following are in the country today?,5,50.3,5
NATPROBS_DEF_W161,NATPROBS_DEF_W161. The federal budget deficit // How much of a problem do you think each of the following are in the country today?,5,50.3,5
NATPROBS_VCRI_W161,NATPROBS_VCRI_W161. Violent crime // How much of a problem do you think each of the following are in the country today?,5,50.3,5
NATPROBS_K12_W161,NATPROBS_K12_W161. The quality of public K-12 schools // How much of a problem do you think each of the following are in the country today?,5,50.3,5
NATPROBS_POVTY_W161,NATPROBS_POVTY_W161. The number of Americans living in poverty // How much of a problem do you think each of the following are in the country today?,5,50.3,5
NATPROBS_LONE_W161,NATPROBS_LONE_W161. The number of Americans feeling lonely or isolated // How much of a problem do you think each of the following are in the country today?,5,50.3,5
NATPROBS_INFL_W161,NATPROBS_INFL_W161. Inflation // How much of a problem do you think each of the following are in the country today?,5,49.7,5
NATPROBS_ITERR_W161,NATPROBS_ITERR_W161. International terrorism // How much of a problem do you think each of the following are in the country today?,5,49.7,5
NATPROBS_COMP_W161,NATPROBS_COMP_W161. The ability of Democrats and Republicans to work together in Washington // How much of a problem do you think each of the following are in the country today?,5,49.7,5
NATPROBS_MOR_W161,NATPROBS_MOR_W161. The state of moral values in the country // How much of a problem do you think each of the following are in the country today?,5,49.7,5
NATPROBS_SSMED_W161,NATPROBS_SSMED_W161. The financial stability of Social Security and Medicare // How much of a problem do you think each of the following are in the country today?,5,49.7,5
NATPROBS_NTDIS_W161,NATPROBS_NTDIS_W161. The impact of natural disasters // How much of a problem do you think each of the following are in the country today?,5,49.7,5
NATPROBS_RAC_W161,NATPROBS_RAC_W161. Racism // How much of a problem do you think each of the following are in the country today?,5,50.3,5
NATPROBS_UNEM_W161,NATPROBS_UNEM_W161. Unemployment // How much of a problem do you think each of the following are in the country today?,5,50.3,5
NATPROBS_DTERR_W161,NATPROBS_DTERR_W161. Domestic terrorism // How much of a problem do you think each of the following are in the country today?,5,50.3,5
NATPROBS_DRG_W161,NATPROBS_DRG_W161. Drug addiction // How much of a problem do you think each of the following are in the country today?,5,50.3,5
NATPROBS_PLSYS_W161,NATPROBS_PLSYS_W161. The way the U.S. political system operates // How much of a problem do you think each of the following are in the country today?,5,50.3,5
NATPROBS_FCT_W161,NATPROBS_FCT_W161. Americans' level of agreement on the basic facts about issues and events // How much of a problem do you think each of the following are in the country today?,5,50.3,5
NEWPRES_ACCOMP_W161,NEWPRES_ACCOMP_W161. Thinking about Donald Trump's policies and plans for his presidency... How much of his agenda do you think he will be able to accomplish over the next four years?,6,0.0,6
NEWPRES_SUPP_W161,NEWPRES_SUPP_W161. How many of Donald Trump's policies and plans would you say you support?,6,0.0,6
NEWPRES_ACTNS_W161,NEWPRES_ACTNS_W161. Would you say the Trump administration's actions so far have been...,6,0.0,6
PRESWITHOP_W161,"PRESWITHOP_W161. This year, do you think Joe Biden should... (Form 1 only)",3,49.7,4
OPWITHPRES_W161,"OPWITHPRES_W161. This year, do you think Republican congressional leaders should... (Form 2 only)",3,50.3,4
ECON1_W161,ECON1_W161. How would you rate economic conditions in this country today?,5,0.0,5
ECON1B_W161,"ECON1B_W161. A year from now, do you expect that economic conditions in the country as a whole will be...",4,0.0,4
ECON_FUT_JBS_W161,"ECON_FUT_JBS_W161. The availability of good-paying jobs // A year from now, do you expect each of the following will be better or worse than they are now?",6,0.0,6
ECON_FUT_PRICE_W161,"ECON_FUT_PRICE_W161. The affordability of food and consumer goods // A year from now, do you expect each of the following will be better or worse than they are now?",6,0.0,6
ECON_FUT_ENRG_W161,"ECON_FUT_ENRG_W161. The affordability of gasoline and energy // A year from now, do you expect each of the following will be better or worse than they are now?",6,0.0,6
ECON_FUT_HOUS_W161,"ECON_FUT_HOUS_W161. The affordability of housing // A year from now, do you expect each of the following will be better or worse than they are now?",6,49.7,6
ECON_FUT_HLTH_W161,"ECON_FUT_HLTH_W161. The affordability of healthcare // A year from now, do you expect each of the following will be better or worse than they are now?",6,50.3,6
FAVPOL_TRUMP_W161,FAVPOL_TRUMP_W161. Donald Trump // What is your overall opinion of...,6,0.0,6
FAVPOL_VANCE_W161,FAVPOL_VANCE_W161. JD Vance // What is your overall opinion of...,6,49.7,6
FAVPOL_MJOHNSON_W161,FAVPOL_MJOHNSON_W161. Mike Johnson // What is your overall opinion of...,6,49.7,6
FAVPOL_JEFFRIES_W161,FAVPOL_JEFFRIES_W161. Hakeem Jeffries // What is your overall opinion of...,6,49.7,6
FAVPOL_ZUCKERBERG_W161,FAVPOL_ZUCKERBERG_W161. Mark Zuckerberg // What is your overall opinion of...,6,49.7,6
FAVPOL_THUNE_W161,FAVPOL_THUNE_W161. John Thune // What is your overall opinion of...,6,50.3,6
FAVPOL_SCHUMER_W161,FAVPOL_SCHUMER_W161. Chuck Schumer // What is your overall opinion of...,6,50.3,6
FAVPOL_MUSK_W161,FAVPOL_MUSK_W161. Elon Musk // What is your overall opinion of...,6,50.3,6
FAVPOL_RFKJR_W161,"FAVPOL_RFKJR_W161. Robert F. Kennedy, Jr. // What is your overall opinion of...",6,50.3,6
EXCPWER_W161,"EXCPWER_W161. Which of the following statements comes closest to your view, even if neither is exactly right?",3,49.7,3
EXCPWER_NAME_W161,"EXCPWER_NAME_W161. Which of the following statements comes closest to your view, even if neither is exactly right?",3,50.3,3
MARIJUANA3_W161,MARIJUANA3_W161. Which comes closer to your view about the use of marijuana by adults?,4,0.0,4
TAXRATES400_W161,"TAXRATES400_W161. Should tax rates on household income over $400,000 be...",6,0.0,6
TAXRATESBUS_W161,TAXRATESBUS_W161. Should tax rates on large businesses and corporations be...,6,0.0,6
CONF2_CAREER_W161,"CONF2_CAREER_W161. Career employees at government agencies who are not appointed by a president // A variety of officials work at federal government agencies. How much confidence, if any, do you have in these different groups to act in the best interest of",5,0.0,5
CONF2_APPNT_W161,"CONF2_APPNT_W161. Officials appointed by a president to oversee government agencies // A variety of officials work at federal government agencies. How much confidence, if any, do you have in these different groups to act in the best interest of the public?",5,0.0,5
FEDSTATE_STAT_W161,"FEDSTATE_STAT_W161. State governments not being willing enough to work with the federal government // How concerned, if at all, are you about each of the following?",6,0.0,6
FEDSTATE_RGHT_W161,"FEDSTATE_RGHT_W161. The rights and protections a person has might be different depending on which state they are in // How concerned, if at all, are you about each of the following?",6,0.0,6
FEDSTATE_FED2_W161,"FEDSTATE_FED2_W161. The federal government setting policies on issues that are better left to state governments // How concerned, if at all, are you about each of the following?",6,0.0,6
CLRSOL_W161,CLRSOL_W161. Which comes closer to your own view?,3,0.0,3
PRESGRPS_BP_W161,PRESGRPS_BP_W161. Black people // How do you think each of the following groups will be affected by Donald Trump taking office?,4,49.7,4
PRESGRPS_HP_W161,PRESGRPS_HP_W161. Hispanic people // How do you think each of the following groups will be affected by Donald Trump taking office?,4,49.7,4
PRESGRPS_WP_W161,PRESGRPS_WP_W161. White people // How do you think each of the following groups will be affected by Donald Trump taking office?,4,49.7,4
PRESGRPS_AAP_W161,PRESGRPS_AAP_W161. Asian people // How do you think each of the following groups will be affected by Donald Trump taking office?,4,49.7,4
PRESGRPS_EC_W161,PRESGRPS_EC_W161. Evangelical Christians // How do you think each of the following groups will be affected by Donald Trump taking office?,4,50.3,4
PRESGRPS_MEN_W161,PRESGRPS_MEN_W161. Men // How do you think each of the following groups will be affected by Donald Trump taking office?,4,50.3,4
PRESGRPS_WMN_W161,PRESGRPS_WMN_W161. Women // How do you think each of the following groups will be affected by Donald Trump taking office?,4,50.3,4
PRESGRPS_UN_W161,PRESGRPS_UN_W161. Unions // How do you think each of the following groups will be affected by Donald Trump taking office?,4,50.3,4
PRESGRPS_LGB_W161,PRESGRPS_LGB_W161. Gay and lesbian people // How do you think each of the following groups will be affected by Donald Trump taking office?,4,0.0,4
PRESGRPS_BC_W161,PRESGRPS_BC_W161. Business corporations // How do you think each of the following groups will be affected by Donald Trump taking office?,4,49.7,4
PRESGRPS_MIL_W161,PRESGRPS_MIL_W161. The military // How do you think each of the following groups will be affected by Donald Trump taking office?,4,49.7,4
PRESGRPS_OLD_W161,PRESGRPS_OLD_W161. Older people // How do you think each of the following groups will be affected by Donald Trump taking office?,4,49.7,4
PRESGRPS_YNG_W161,PRESGRPS_YNG_W161. Younger people // How do you think each of the following groups will be affected by Donald Trump taking office?,4,49.7,4
PRESGRPS_PR_W161,PRESGRPS_PR_W161. Poor people // How do you think each of the following groups will be affected by Donald Trump taking office?,4,50.3,4
PRESGRPS_CHI_W161,PRESGRPS_CHI_W161. Children // How do you think each of the following groups will be affected by Donald Trump taking office?,4,50.3,4
PRESGRPS_WLTH_W161,PRESGRPS_WLTH_W161. Wealthy people // How do you think each of the following groups will be affected by Donald Trump taking office?,4,50.3,4
PRESGRPS_TRANS_W161,PRESGRPS_TRANS_W161. Transgender people // How do you think each of the following groups will be affected by Donald Trump taking office?,4,50.3,4
PRESGRPS_YOU_W161,PRESGRPS_YOU_W161. And do you think people like yourself will...,4,0.0,4
REPWORKTRMP_W161,"REPWORKTRMP_W161. Which comes closer to your view, even if neither is exactly right? Republicans in Congress...",3,54.2,3
EOFOL_W161,"EOFOL_W161. As you may know, the Trump administration has issued a number of executive orders and actions since taking office. Would you say you have followed these executive actions...",6,0.0,6
BIRTHCIT_APP_W161,"BIRTHCIT_APP_W161. All in all, do you approve or disapprove of Trump's executive order limiting citizenship?",5,0.0,5
IMMIG_DT_APP_MILBRD_W161,"IMMIG_DT_APP_MILBRD_W161. Sending additional U.S. military forces to the U.S. border with Mexico // Thinking about the Trump administration's approach to immigration, do you approve or disapprove of the Trump administration doing each of the following?",5,0.0,5
IMMIG_DT_APP_ASYLUM_W161,"IMMIG_DT_APP_ASYLUM_W161. Suspending applications for asylum from people seeking to live in the U.S. // Thinking about the Trump administration's approach to immigration, do you approve or disapprove of the Trump administration doing each of the following?",5,0.0,5
IMMIG_DT_APP_DEPORT_W161,"IMMIG_DT_APP_DEPORT_W161. Increasing efforts to deport people who are living in the U.S. illegally // Thinking about the Trump administration's approach to immigration, do you approve or disapprove of the Trump administration doing each of the following?",5,0.0,5
IMMIG_DT_APP_CUTFND_W161,"IMMIG_DT_APP_CUTFND_W161. Cutting federal funds for cities and states if they do not help federal efforts to deport people in their communities who are in the U.S. illegally // Thinking about the Trump administration's approach to immigration, do you appro",5,0.0,5
DEPRT_DEG_W161,"DEPRT_DEG_W161. When it comes to deporting immigrants who are living in the U.S. illegally, would you say the Trump administration is doing...",4,0.0,4
JAN6PARDAPP_NONVIOL_W161,"JAN6PARDAPP_NONVIOL_W161. Do you approve or disapprove of Donald Trump pardoning people who were convicted of nonviolent crimes related to the events at the U.S. Capitol on January 6, 2021?",5,0.0,5
JAN6PARDAPP_VIOL_W161,"JAN6PARDAPP_VIOL_W161. Do you approve or disapprove of Donald Trump pardoning people who were convicted of violent crimes related to the events at the U.S. Capitol on January 6, 2021?",5,0.0,5
JAN6PARDAPP_JB_W161,"JAN6PARDAPP_JB_W161. From what you have read and heard, do you approve or disapprove of Joe Biden pardoning these committee members, staff, and police officers?",5,0.0,5
JAN6CONFCM_MOD_W161,"JAN6CONFCM_MOD_W161. And thinking back to the U.S. House committee's investigation, how confident are you that the committee's investigation into the events at the U.S. Capitol on January 6, 2021, was fair and reasonable?",5,0.0,5
F_METRO,Metropolitan area indicator,2,0.1,2
F_CREGION,Census region,4,0.1,4
F_CDIVISION,Census division,9,0.1,9
F_USR_SELFID,"Self-identified Urban, Suburban, Rural (USR)",4,0.0,4
F_AGECAT,Age category,5,0.0,5
F_GENDER,Gender,4,0.0,4
F_EDUCCAT,Education level category,4,0.0,4
F_EDUCCAT2,Education level category 2,7,0.0,7
F_HISP,Hispanic identification,3,0.0,3
F_HISP_ORIGIN,Hispanic origin,10,84.9,10
F_YEARSINUS_RECODE,Years lived in the United States (excluding Puerto Rico or other U.S. territories) - 4 category,5,0.0,5
F_RACECMB,Combining Race,6,0.0,6
F_RACETHNMOD,Race-Ethnicity,6,0.0,6
F_BIRTHPLACE,Birthplace,5,0.0,5
F_MARITAL,Marital status,7,0.0,7
F_RELIG,Religion,13,0.0,13
F_BORN,Born-again or evangelical Christian,3,37.7,3
F_RELIGCAT1,Condensed 4-way religion variable,5,0.0,5
F_ATTENDPER,Religious service attendance in person,7,0.0,7
F_PARTY_FINAL,Party,5,0.0,5
F_PARTYLN_FINAL,Party lean,3,60.1,3
F_PARTYSTR_FINAL,Party strength,3,39.9,3
F_PARTYLNCLOSE_FINAL,Party closeness among leaners,6,62.7,6
F_PARTYSUM_FINAL,Party summary,3,0.0,3
F_PARTYSUMIDEO_FINAL,Combining ideology and party identification,5,0.0,5
F_REG,Voter registration,3,0.0,3
F_INC_SDT1,Family income,10,0.0,10
F_IDEO,Ideology,6,0.0,6
F_INTFREQ,Frequency of internet use,7,0.0,7
F_VOLSUM,Volunteerism status,3,0.0,3
F_INC_TIER2,Income tier 3-way,4,0.0,4
WEIGHT_W161,Wave 161 weight,4983,0.0,0

================== W167: all 170 variables

,question text,unique values,% missing,labelled codes
variable,,,,
QKEY,QKEY_W167. QKEY. Unique identifier,3589,0.0,0
INTERVIEW_START_W167,INTERVIEW_START_W167. Interview start time,3490,0.0,0
INTERVIEW_END_W167,INTERVIEW_END_W167. Interview end time,3522,0.0,0
DEVICE_TYPE_W167,DEVICE_TYPE_W167. The device used in the latest access of the survey link,3,0.0,4
SVYMODE_W167,SVYMODE_W167. Mode of survey,2,0.0,2
LANG_W167,LANG_W167. Language of interview,2,0.0,2
FORM_W167,"X_FORM_W167. Flag to randomly assign panelists to one of two forms (Form 1, Form 2) and weight within form ATP source: Randomly assigned for each survey.",2,0.0,2
POL1DT_W167,POL1DT_W167. Do you approve or disapprove of the way Donald Trump is handling his job as president?,3,0.0,3
POL1DTSTR_W167,POL1DTSTR_W167. Do you approve/disapprove of the way Donald Trump is handling his job as president...,3,0.8,3
LIFEFIFTY_W167,"LIFEFIFTY_W167. In general, would you say life in America today is better, worse, or about the same as it was 50 years ago for people like you?",4,0.0,4
USCONF_FUT_W167,USCONF_FUT_W167. How much confidence do you have in the future of the United States?,5,49.9,5
WISDOM_PPL_W167,"WISDOM_PPL_W167. In general, how much trust and confidence do you have in the wisdom of the American people when it comes to making political decisions?",5,50.1,5
GOVSIZE1_W167,"GOVSIZE1_W167. If you had to choose, would you rather have...",3,0.0,3
DTCONF_ECON_W167,"DTCONF_ECON_W167. Make good decisions about economic policy // Thinking about Donald Trump’s ability to handle a number of things, how confident are you that Donald Trump can do each of the following?",5,0.0,5
DTCONF_IMMI_W167,"DTCONF_IMMI_W167. Make good decisions about immigration policy // Thinking about Donald Trump’s ability to handle a number of things, how confident are you that Donald Trump can do each of the following?",5,0.0,5
DTCONF_TRAD_W167,"DTCONF_TRAD_W167. Negotiate favorable trade agreements with other countries // Thinking about Donald Trump’s ability to handle a number of things, how confident are you that Donald Trump can do each of the following?",5,49.9,5
DTCONF_ABCN_W167,"DTCONF_ABCN_W167. Make good decisions about abortion policy // Thinking about Donald Trump’s ability to handle a number of things, how confident are you that Donald Trump can do each of the following?",5,49.9,5
DTCONF_CLSR_W167,"DTCONF_CLSR_W167. Bring the country closer together // Thinking about Donald Trump’s ability to handle a number of things, how confident are you that Donald Trump can do each of the following?",5,49.9,5
DTCONF_HECR_W167,"DTCONF_HECR_W167. Effectively handle a public health emergency // Thinking about Donald Trump’s ability to handle a number of things, how confident are you that Donald Trump can do each of the following?",5,49.9,5
DTCONF_FRGN_W167,"DTCONF_FRGN_W167. Make good decisions about foreign policy // Thinking about Donald Trump’s ability to handle a number of things, how confident are you that Donald Trump can do each of the following?",5,50.1,5
DTCONF_HCP_W167,"DTCONF_HCP_W167. Make good decisions about health care policy // Thinking about Donald Trump’s ability to handle a number of things, how confident are you that Donald Trump can do each of the following?",5,50.1,5
DTCONF_TAX_W167,"DTCONF_TAX_W167. Make good decisions about tax policy // Thinking about Donald Trump’s ability to handle a number of things, how confident are you that Donald Trump can do each of the following?",5,50.1,5
DTCONF_EXEC_W167,"DTCONF_EXEC_W167. Manage the Executive Branch effectively // Thinking about Donald Trump’s ability to handle a number of things, how confident are you that Donald Trump can do each of the following?",5,50.1,5
NEW_ADMIN_ECON_W167,"NEW_ADMIN_ECON_W167. Compared with the Biden administration, do you think the policies of the Trump administration are making the country's economy...",4,0.0,4
NEW_ADMIN_GLOB_W167,"NEW_ADMIN_GLOB_W167. Compared with the Biden administration, do you think the policies of the Trump administration are putting the United States in...",4,0.0,4
DTTRUST_W167,"DTTRUST_W167. Compared with what previous presidents said while in office, would you say you trust what Donald Trump says…",4,50.1,4
PRES_ETHICAL_ADMIN_W167,"PRES_ETHICAL_ADMIN_W167. Overall, how would you rate the ethical standards of top Trump administration officials?",5,49.9,5
DEMACT_IMPD_CMN_W167,DEMACT_IMPD_CMN_W167. Find areas of common ground where they can work with Donald Trump // How important is it for Democratic elected officials to do each of the following?,6,0.0,6
DEMACT_IMPD_PUSH_W167,DEMACT_IMPD_PUSH_W167. Push hard against Donald Trump’s policies when they disagree // How important is it for Democratic elected officials to do each of the following?,6,0.0,6
DEMOFF_EFF_CMN_W167,DEMOFF_EFF_CMN_W167. Finding areas of common ground where they can work with Donald Trump // And how would you rate Democratic elected officials’ efforts at each of the following?,5,0.0,5
DEMOFF_EFF_PUSH_W167,DEMOFF_EFF_PUSH_W167. Pushing hard against Donald Trump’s policies when they disagree // And how would you rate Democratic elected officials’ efforts at each of the following?,5,0.0,5
TRUMPACT_IMPD_CMN_W167,TRUMPACT_IMPD_CMN_W167. Find areas of common ground where he can work with Democratic elected officials // How important is it for Donald Trump to do each of the following?,6,0.0,6
TRUMPACT_IMPD_PUSH_W167,TRUMPACT_IMPD_PUSH_W167. Push hard for his policies regardless of whether Democratic elected officials agree // How important is it for Donald Trump to do each of the following?,6,0.0,6
TRUMP_EFF_CMN_W167,TRUMP_EFF_CMN_W167. Finding areas of common ground where he can work with Democratic elected officials // And how would you rate Donald Trump’s efforts at each of the following?,5,0.0,5
TRUMP_EFF_PUSH_W167,TRUMP_EFF_PUSH_W167. Pushing hard for his policies regardless of whether Democratic elected officials agree // And how would you rate Donald Trump’s efforts at each of the following?,5,0.0,5
DT_REPRE_W167,DT_REPRE_W167. Do you think Donald Trump should primarily focus on addressing the concerns of...,3,0.0,3
ECON1_W167,ECON1_W167. Thinking about the nation’s economy... How would you rate economic conditions in this country today?,5,0.0,5
ECON1B_W167,"ECON1B_W167. A year from now, do you expect that economic conditions in the country as a whole will be...",4,0.0,4
PERSFNC_W167,PERSFNC_W167. Thinking about your personal finances...How would you rate your own personal financial situation? Would you say you are in...,5,0.0,5
PERSFNCB_W167,"PERSFNCB_W167. A year from now, do you expect that the financial situation of you and your family will be...",4,0.0,4
ECONCONC_UNEM_W167,"ECONCONC_UNEM_W167. People who want to work being unable to find jobs // How concerned, if at all, are you personally about each of the following economic issues in the country today?",5,0.0,5
ECONCONC_PRICE_W167,"ECONCONC_PRICE_W167. The price of food and consumer goods // How concerned, if at all, are you personally about each of the following economic issues in the country today?",5,49.9,5
ECONCONC_REAL_W167,"ECONCONC_REAL_W167. The cost of housing // How concerned, if at all, are you personally about each of the following economic issues in the country today?",5,49.9,5
ECONCONC_STCK_W167,"ECONCONC_STCK_W167. How the stock market is doing // How concerned, if at all, are you personally about each of the following economic issues in the country today?",5,50.1,5
ECONCONC_ENG2_W167,"ECONCONC_ENG2_W167. The price of gasoline and energy // How concerned, if at all, are you personally about each of the following economic issues in the country today?",5,50.1,5
POLINTOL2_REP_W167,"POLINTOL2_REP_W167. In general, how comfortable do you think Republicans in this country are to freely and openly express their political views?",5,0.0,5
POLINTOL2_DEM_W167,"POLINTOL2_DEM_W167. In general, how comfortable do you think Democrats in this country are to freely and openly express their political views?",5,0.0,5
GOVRESP_COL_W167,GOVRESP_COL_W167. A college education // Do you think each of the following is something the federal government has a responsibility to provide for all Americans?,3,49.9,3
GOVRESP_INS_W167,GOVRESP_INS_W167. Health insurance // Do you think each of the following is something the federal government has a responsibility to provide for all Americans?,3,49.9,3
GOVRESP_STAND_W167,GOVRESP_STAND_W167. An adequate standard of living // Do you think each of the following is something the federal government has a responsibility to provide for all Americans?,3,49.9,3
GOVRESP_RET_W167,GOVRESP_RET_W167. Adequate income in retirement // Do you think each of the following is something the federal government has a responsibility to provide for all Americans?,3,49.9,3
GOVRESP_EDUC_W167,GOVRESP_EDUC_W167. High quality K-12 education // Do you think each of the following is something the federal government has a responsibility to provide for all Americans?,3,50.1,3
GOVRESP_WIFI_W167,GOVRESP_WIFI_W167. Access to high-speed internet // Do you think each of the following is something the federal government has a responsibility to provide for all Americans?,3,50.1,3
GOVRESP_CLEA_W167,GOVRESP_CLEA_W167. Clean air and water // Do you think each of the following is something the federal government has a responsibility to provide for all Americans?,3,50.1,3
GOVRESP_ENERG_W167,GOVRESP_ENERG_W167. Reliable energy sources // Do you think each of the following is something the federal government has a responsibility to provide for all Americans?,3,50.1,3
GOVRESP2_MIL_W167,GOVRESP2_MIL_W167. A strong military // Do you think the federal government has a responsibility to provide...,3,0.0,3
GOVRESP2_BORD_W167,GOVRESP2_BORD_W167. Secure borders // Do you think the federal government has a responsibility to provide...,3,0.0,3
GOVRESP2_PARK_W167,GOVRESP2_PARK_W167. National parks and wilderness areas // Do you think the federal government has a responsibility to provide...,3,0.0,3
INSTFAV_CONG_W167,INSTFAV_CONG_W167. Congress // Do you have a favorable or unfavorable opinion of each of the following?,5,0.0,5
INSTFAV_COURT_W167,INSTFAV_COURT_W167. The Supreme Court // Do you have a favorable or unfavorable opinion of each of the following?,5,0.0,5
INSTFAV_REP_W167,INSTFAV_REP_W167. The Republican Party // Do you have a favorable or unfavorable opinion of each of the following?,5,0.0,5
INSTFAV_DEM_W167,INSTFAV_DEM_W167. The Democratic Party // Do you have a favorable or unfavorable opinion of each of the following?,5,0.0,5
FEDCRT_IMPT_W167,FEDCRT_IMPT_W167. How important is it for judges in U.S. federal courts to be fair and impartial in how they decide cases?,6,0.0,6
FEDCRT_CONF_W167,FEDCRT_CONF_W167. How confident are you that judges in U.S. federal courts are fair and impartial in how they decide cases?,6,49.9,6
FEDCRT_CONF_NS_W167,FEDCRT_CONF_NS_W167. How confident are you that judges in U.S. federal courts are fair and impartial in how they decide cases?,7,50.1,7
TARIFF_APP_W167,TARIFF_APP_W167. Do you approve or disapprove of the Trump administration substantially increasing tariffs on goods imported from most countries that trade with the U.S.?,5,0.0,5
TRUMPAPPROV_DEI_W167,"TRUMPAPPROV_DEI_W167. Do you approve or disapprove of the Trump administration’s actions to end diversity, equity and inclusion (also known as DEI) policies in the federal government?",5,49.9,5
TRUMPAPPROV_DEI_NS_W167,"TRUMPAPPROV_DEI_NS_W167. Do you approve or disapprove of the Trump administration’s actions to end diversity, equity and inclusion (also known as DEI) policies in the federal government?",6,50.1,6
POLSTOR_FOLL_LAW_W167,POLSTOR_FOLL_LAW_W167. The Trump administration’s executive orders sanctioning several big law firms // How closely have you been following news about each of the following?,6,49.9,6
POLSTOR_FOLL_DOGE_W167,POLSTOR_FOLL_DOGE_W167. The actions of the Trump administration’s Department of Government Efficiency (DOGE) team // How closely have you been following news about each of the following?,6,49.9,6
POLSTOR_FOLL_DPRT_W167,POLSTOR_FOLL_DPRT_W167. Deportations of people who are living in the U.S. illegally // How closely have you been following news about each of the following?,6,49.9,6
POLSTOR_FOLL_TARF_W167,POLSTOR_FOLL_TARF_W167. The Trump administration’s tariffs // How closely have you been following news about each of the following?,6,49.9,6
POLSTOR_FOLL_PROT_W167,POLSTOR_FOLL_PROT_W167. Protests against Tesla car dealerships and owners // How closely have you been following news about each of the following?,6,49.9,6
POLSTOR_FOLL_MEAS_W167,POLSTOR_FOLL_MEAS_W167. Measles outbreaks around the country // How closely have you been following news about each of the following?,6,50.1,6
POLSTOR_FOLL_CUTS_W167,POLSTOR_FOLL_CUTS_W167. Cuts to federal government agencies and departments // How closely have you been following news about each of the following?,6,50.1,6
POLSTOR_FOLL_BORD_W167,POLSTOR_FOLL_BORD_W167. Security along the U.S. border with Mexico // How closely have you been following news about each of the following?,6,50.1,6
POLSTOR_FOLL_LEGAL_W167,POLSTOR_FOLL_LEGAL_W167. Legal challenges to Trump administration actions // How closely have you been following news about each of the following?,6,50.1,6
POLSTOR_FOLL_SEC_W167,"POLSTOR_FOLL_SEC_W167. Some Trump administration communications related to national security taking place on unofficial messaging platforms, such as Signal or Gmail // How closely have you been following news about each of the following?",6,50.1,6
DT_REDUCTIONS_W167,"DT_REDUCTIONS_W167. As you may know, the Trump administration has been ordering cuts to federal departments and agencies. From what you’ve read and heard, do you approve or disapprove of the cuts the administration is making?",5,0.0,5
DT_RED_CARE_W167,"DT_RED_CARE_W167. When it comes to cuts the Trump administration is making to federal departments and agencies, do you think the administration’s approach is...",4,49.9,4
DT_RED_RUN_W167,"DT_RED_RUN_W167. When it comes to cuts the Trump administration is making to federal departments and agencies, do you think the administration’s approach will...",4,49.9,4
DT_RED_NEED_W167,"DT_RED_NEED_W167. When it comes to cuts the Trump administration is making to federal departments and agencies, do you think the administration’s approach will...",4,50.1,4
DT_RED_SAV_W167,"DT_RED_SAV_W167. When it comes to cuts the Trump administration is making to federal departments and agencies, would you say that the Trump administration’s approach will...",4,50.1,4
DTEOS_PRESPOW2_W167,"DTEOS_PRESPOW2_W167. As you may know, Donald Trump has used a number of executive orders to set policy in the first few months of his presidency. Do you think Trump is doing...",5,0.0,5
DISCRRIM_BLACK_W167,DISCRRIM_BLACK_W167. Black people // Please tell us how much discrimination there is against each of these groups in our society today.,5,49.9,5
DISCRRIM_HISP_W167,DISCRRIM_HISP_W167. Hispanic people // Please tell us how much discrimination there is against each of these groups in our society today.,5,49.9,5
DISCRRIM_WHITE_W167,DISCRRIM_WHITE_W167. White people // Please tell us how much discrimination there is against each of these groups in our society today.,5,49.9,5
DISCRRIM_ASIAN_W167,DISCRRIM_ASIAN_W167. Asian people // Please tell us how much discrimination there is against each of these groups in our society today.,5,49.9,5
DISCRRIM_WOM_W167,DISCRRIM_WOM_W167. Women // Please tell us how much discrimination there is against each of these groups in our society today.,5,50.1,5
DISCRRIM_MEN_W167,DISCRRIM_MEN_W167. Men // Please tell us how much discrimination there is against each of these groups in our society today.,5,50.1,5
DISCRRIM_TRANS_W167,DISCRRIM_TRANS_W167. People who are transgender // Please tell us how much discrimination there is against each of these groups in our society today.,5,50.1,5
DISCRRIM_IMMIGL_W167,DISCRRIM_IMMIGL_W167. Immigrants who are legally in the U.S. // Please tell us how much discrimination there is against each of these groups in our society today.,5,50.1,5
DISCRRIM_IMMIGU_W167,DISCRRIM_IMMIGU_W167. Immigrants who are illegally in the U.S. // Please tell us how much discrimination there is against each of these groups in our society today.,5,50.1,5
DISCRRIM_NOCOLL_W167,DISCRRIM_NOCOLL_W167. People who did not go to college // Please tell us how much discrimination there is against each of these groups in our society today.,5,50.1,5
DISCRRIM_LGBC_W167,DISCRRIM_LGBC_W167. People who are gay or lesbian // Please tell us how much discrimination there is against each of these groups in our society today.,5,49.9,5
DISCRRIM_REL_W167,DISCRRIM_REL_W167. People who are religious // Please tell us how much discrimination there is against each of these groups in our society today.,5,49.9,5
DISCRRIM_RUR_W167,DISCRRIM_RUR_W167. People who live in rural areas // Please tell us how much discrimination there is against each of these groups in our society today.,5,49.9,5
DISCRRIM_CIT_W167,DISCRRIM_CIT_W167. People who live in cities // Please tell us how much discrimination there is against each of these groups in our society today.,5,49.9,5
DISCRRIM_YOUNG_W167,DISCRRIM_YOUNG_W167. Younger people // Please tell us how much discrimination there is against each of these groups in our society today.,5,49.9,5
DISCRRIM_OLD_W167,DISCRRIM_OLD_W167. Older people // Please tell us how much discrimination there is against each of these groups in our society today.,5,49.9,5
DISCRRIM_JEW_W167,DISCRRIM_JEW_W167. Jews // Please tell us how much discrimination there is against each of these groups in our society today.,5,50.1,5
DISCRRIM_MUS_W167,DISCRRIM_MUS_W167. Muslims // Please tell us how much discrimination there is against each of these groups in our society today.,5,50.1,5
DISCRRIM_EVANG_W167,DISCRRIM_EVANG_W167. Evangelical Christians // Please tell us how much discrimination there is against each of these groups in our society today.,5,50.1,5
DISCRRIM_ATH_W167,DISCRRIM_ATH_W167. Atheists // Please tell us how much discrimination there is against each of these groups in our society today.,5,50.1,5
PF_HAPPEN_HOU_W167,"PF_HAPPEN_HOU_W167. Had problems paying your rent or mortgage // In the past year, have any of the following happened to you?",3,50.1,3
PF_HAPPEN_LOSE_W167,"PF_HAPPEN_LOSE_W167. Been laid off or lost your job // In the past year, have any of the following happened to you?",3,50.1,3
PF_HAPPEN_RAISE_W167,"PF_HAPPEN_RAISE_W167. Gotten a pay raise at your current job or gotten a better job // In the past year, have any of the following happened to you?",3,50.1,3
PF_HAPPEN_SAVE_W167,"PF_HAPPEN_SAVE_W167. Been able to save money for the future // In the past year, have any of the following happened to you?",3,50.1,3
PF_HAPPEN_MED_W167,"PF_HAPPEN_MED_W167. Had trouble getting or paying for medical care for yourself or your family // In the past year, have any of the following happened to you?",3,50.1,3
PF_HAPPEN_FOOD_W167,"PF_HAPPEN_FOOD_W167. Gotten food from a food bank or food pantry // In the past year, have any of the following happened to you?",3,49.9,3
PF_HAPPEN_CHILD_W167,"PF_HAPPEN_CHILD_W167. Had trouble paying for childcare // In the past year, have any of the following happened to you?",3,49.9,3
PF_HAPPEN_AUTO_W167,"PF_HAPPEN_AUTO_W167. Had problems paying for your daily transportation costs // In the past year, have any of the following happened to you?",3,49.9,3
PF_HAPPEN_BRRW_W167,"PF_HAPPEN_BRRW_W167. Borrowed money from friends and family // In the past year, have any of the following happened to you?",3,49.9,3
PF_HAPPEN_VACA_W167,"PF_HAPPEN_VACA_W167. Gone on a vacation // In the past year, have any of the following happened to you?",3,49.9,3
PF_HAPPEN_PYDY_W167,"PF_HAPPEN_PYDY_W167. Taken out a payday or other short-term loan // In the past year, have any of the following happened to you?",3,49.9,3

## 4. Where Trump approval lives

### First: everything that mentions Trump

In [10]:
rows = []
for w in WAVE_ORDER:
    for c, l in labels[w].items():
        if l and "trump" in l.lower():
            rows.append({"wave": w, "variable": c, "question text": l})
trump_vars = pd.DataFrame(rows)
print(trump_vars.groupby("wave", sort=False).size().to_frame("variables that mention Trump").T)
trump_vars.set_index("wave")

wave                          Feb17  Apr17  Typology17  Jan18  Mar18  May18  \
variables that mention Trump     25     16           6     23      6     14

wave                          Jun18  W161  W167
variables that mention Trump     20    45    51

,variable,question text
wave,,
Feb17,q1,Q.1 Do you approve or disapprove of the way Donald Trump is handling his job as President? [IF DK ENTER AS DK. IF DEPENDS PROBE ONCE WITH: Overall do you approve or disapprove of the way Donald Trump is handling his job as President?
Feb17,q5af1,"Q.5aF1 Do you approve or disapprove of the way Donald Trump is handling [INSERT ITEM, RANDOMIZE] / The economy"
Feb17,q5bf1,"Q.5bF1 Do you approve or disapprove of the way Donald Trump is handling [INSERT ITEM, RANDOMIZE] / The threat of terrorism"
Feb17,q5cf1,"Q.5cF1 Do you approve or disapprove of the way Donald Trump is handling [INSERT ITEM, RANDOMIZE] / The nation's foreign policy"
Feb17,q5df1,"Q.5dF1 Do you approve or disapprove of the way Donald Trump is handling [INSERT ITEM, RANDOMIZE] / The nation's immigration policy"
Feb17,q6af2,Q.6aF2 Does Donald Trump make you feel [INSERT FIRST ITEM; RANDOMIZE] or not? / Hopeful
Feb17,q6bf2,Q.6bF2 Does Donald Trump make you feel [INSERT FIRST ITEM; RANDOMIZE] or not? / Proud
Feb17,q6cf2,Q.6cF2 Does Donald Trump make you feel [INSERT FIRST ITEM; RANDOMIZE] or not? / Angry
Feb17,q6df2,Q.6dF2 Does Donald Trump make you feel [INSERT FIRST ITEM; RANDOMIZE] or not? / Uneasy
Feb17,q15af1,"Q.15aF1 As I read some pairs of opposite phrases, tell me which one best reflects your impression of Donald Trump so far. (First,) does Donald Trump impress you as ... / Trustworthy or NOT trustworthy"
Feb17,q15b,"Q.15b As I read some pairs of opposite phrases, tell me which one best reflects your impression of Donald Trump so far... / Someone who cares about people like me or someone who DOESN'T care about people like me"
Feb17,q15cf2,"Q.15cF2 As I read some pairs of opposite phrases, tell me which one best reflects your impression of Donald Trump so far. (First,) does Donald Trump impress you as ... / A strong leader or NOT a strong leader"
Feb17,q15df1,"Q.15dF2 As I read some pairs of opposite phrases, tell me which one best reflects your impression of Donald Trump so far. (First,) does Donald Trump impress you as ... / A good communicator or NOT a good communicator?"
Feb17,q15ef1,"Q.15eF2 As I read some pairs of opposite phrases, tell me which one best reflects your impression of Donald Trump so far. (First,) does Donald Trump impress you as ... / Able to get things done or NOT able to get things done"
Feb17,q15ff1,"Q.15fF1 As I read some pairs of opposite phrases, tell me which one best reflects your impression of Donald Trump so far. (First,) does Donald Trump impress you as ... / Even tempered or NOT even tempered"
Feb17,q15gf2,"Q.15gF2 As I read some pairs of opposite phrases, tell me which one best reflects your impression of Donald Trump so far. (First,) does Donald Trump impress you as ... / Well informed or NOT well informed"
Feb17,q15hf2,"Q.15hF2 As I read some pairs of opposite phrases, tell me which one best reflects your impression of Donald Trump so far. (First,) does Donald Trump impress you as ... / Keeps his promises or DOESN'T keep his promises"
Feb17,q15if2,"Q.15iF2 As I read some pairs of opposite phrases, tell me which one best reflects your impression of Donald Trump so far. (First,) does Donald Trump impress you as ... / A good manager or NOT a good manager"
Feb17,q16,Q.16 How much respect do you think Donald Trump has for this country's democratic institutions and traditions? [READ]
Feb17,q19,Q.19 How confident are you that Donald Trump keeps his own business interests separate from the decisions he makes as president? [READ]?
Feb17,q35,"Q.35 How much, if anything, have you heard or read about the executive order signed by Donald Trump to stop refugees from entering the U.S. for 120 days and prevent people from seven majority-Muslim countries from entering the U.S..."
Feb17,q37,"Q.37 Regardless of whether you approve or disapprove of this policy, do you think the Trump administration did an excellent, good, only fair, or poor job communicating the executive order and putting it into effect?"
Feb17,q43,"Q.43 How much, if anything, have you heard about Donald Trump's choice of Neil Gorsuch [PRONOUNCED: ‘Gore-sitch'] to be the next Supreme Court justice? Have you heard [READ IN ORDER]?"
Feb17,q84a,"Q.84a Is your overall opinion of [INSERT NAME; RANDOMIZE; OBSERVE FORM SPLITS] very favorable, mostly favorable, mostly UNfavorable, or very unfavorable? / Donald Trump"
Feb17,q93,"Q.93 If Donald Trump and the Republican leaders in Congress disagree on an issue, are you more likely to trust Trump or more likely to trust the Republican leaders in Congress?"
Apr17,q1,Q.1 Do you approve or disapprove of the way Donald Trump is handling his job as President? [IF DK ENTER AS DK. IF DEPENDS PROBE ONCE WITH: Overall do you approve or disapprove of the way Donald Trump is handling his job as President?
Apr17,q19f2,"Q.19F2 In making important decisions, do you think Donald Trump is [RANDOMIZE: too impulsive, too cautious], or about right?"
Apr17,q20f1,"Q.20F1 Overall, has Donald Trump done better than you expected as president, worse than you expected, or about as you expected?"
Apr17,q21bf2,"Q.21bF2 How does Donald Trump make you feel? Does he make you feel [INSERT; RANDOMIZE], or not? / happy"
Apr17,q21df2,"Q.21dF2 How does Donald Trump make you feel? Does he make you feel [INSERT; RANDOMIZE], or not? / worried"
Apr17,q25af1,"Q.25aF1 ...Please tell me whether you are very confident, somewhat confident, not too confident, or not at all confident that Trump can [INSERT ITEM; RANDOMIZE]? / Handle an international crisis"
Apr17,q25bf1,"Q.25bF1 ...Please tell me whether you are very confident, somewhat confident, not too confident, or not at all confident that Trump can [INSERT ITEM; RANDOMIZE]? / Manage the Executive Branch effectively"
Apr17,q25cf2,"Q.25cF2 ...Please tell me whether you are very confident, somewhat confident, not too confident, or not at all confident that Trump can [INSERT ITEM; RANDOMIZE]? / Work effectively with Congress"
Apr17,q25df2,"Q.25dF2 ...Please tell me whether you are very confident, somewhat confident, not too confident, or not at all confident that Trump can [INSERT ITEM; RANDOMIZE]? / Use military force wisely"
Apr17,q25ef2,"Q.25eF2 ...Please tell me whether you are very confident, somewhat confident, not too confident, or not at all confident that Trump can [INSERT ITEM; RANDOMIZE]? / Prevent major scandals in his administration?"
Apr17,q26,"Q.26 Would you say you trust what Donald Trump says more, about the same, or less than you trust what previous presidents said while in office?"
Apr17,q30f2,"Q.30F2 Compared with the Obama Administration, do you think the policies of the Trump Administration have put the United States in [READ AND RANDOMIZE OPTION 1 & 2 WITH OPTION 3 ALWAYS LAST]?"
Apr17,q31f1,"Q.31F1 Compared with the Obama Administration, do you think the policies of the Trump Administration have made the United States [READ AND RANDOMIZE OPTION 1 & 2 WITH OPTION 3 ALWAYS LAST]?"
Apr17,q42f1,Q.42F1 Do you think the Trump administration is doing [READ; RANDOMIZE 1 AND 2; 3 ALWAYS LAST] to work with Democrats in Congress?
Apr17,q43f2,Q.43F2 Do you think Democrats in Congress are doing [READ; RANDOMIZE 1 AND 2; 3 ALWAYS LAST] to work with the Trump administration?
Apr17,q84,"Q.84 Do you think Donald Trump has a clear plan for dealing with the situation in Syria, or don’t you think so?"
Typology17,qa1,Q.A1 Do you approve or disapprove of the way Donald Trump is handling his job as President? [IF DK ENTER AS DK. IF DEPENDS PROBE ONCE WITH: Overall do you approve or disapprove of the way Donald Trump is handling his job as President?...
Typology17,qb27,"Q.B27 Since Donald Trump's election, would you say you are paying [RANDOMIZE more/less, less/more] or about the same amount of attention to politics as you used to?"
Typology17,qb28,"Q.B28 When you talk about politics with people who have a different opinion of Donald Trump than you do, would you say you generally find it to be [READ AND RANDOMIZE]?"
Typology17,qb42a,"Q.B42a Is your overall opinion of [INSERT NAME; RANDOMIZE] very favorable, mostly favorable, mostly UNfavorable, or very unfavorable? / Donald Trump"
Typology17,qb46,Q.B46 Do you think that Donald Trump has changed the Republican Party [RANDOMIZE: for the better/for the worse] or don't you think he has changed the Republican Party much either way?
Typology17,qb55a,"Q.B55a [And] If a friend of yours told you they voted for [INSERT ITEM; RANDOMIZE], do you think this would... / Donald Trump"
Jan18,q2,Q.2. Do you approve or disapprove of the way Donald Trump is handling his job as President?
Jan18,q7f2,"Q.7F2. In the long run, do you think Donald Trump will be a successful or unsuccessful president, or do you think it is too early to tell?"
Jan18,q8f2,"Q.8F2. Now thinking about Donald Trump's upcoming State of the Union address... Do you consider this year's State of the Union address to be MORE important than past years', LESS important, or about as important as past years'?"
Jan18,q16,"Q.16. Do you think of your vote for Congress as a vote FOR Donald Trump, as a vote AGAINST Donald Trump, or isn't Donald Trump much of a factor in your vote?"
Jan18,q30af1,"Q30a.F1. Are you very confident, somewhat confident, not too confident, or not at all confident that Trump can...Make wise decisions about the use of nuclear weapons ?"
Jan18,q30bf1,"Q30b.F1. Are you very confident, somewhat confident, not too confident, or not at all confident that Trump can...Make wise decisions about immigration policy ?"
Jan18,q30df1,"Q30d.F1. Are you very confident, somewhat confident, not too confident, or not at all confident that Trump can...Work effectively with Congress ?"
Jan18,q30ef2,"Q30e.F2. Are you very confident, somewhat confident, not too confident, or not at all confident that Trump can...Manage the Executive Branch effectively ?"
Jan18,q30ff2,"Q30f.F2. Are you very confident, somewhat confident, not too confident, or not at all confident that Trump can...Make good decisions about economic policy ?"
Jan18,q30gf2,"Q30g.F2. Are you very confident, somewhat confident, not too confident, or not at all confident that Trump can...Handle an international crisis ?"
Jan18,q40af1,"Q40a.F1. As I read some pairs of opposite phrases, tell me which one best reflects your impression of Donald Trump. Trustworthy or NOT trustworthy?"
Jan18,q40bf2,"Q40b.F2. As I read some pairs of opposite phrases, tell me which one best reflects your impression of Donald Trump. Someone who cares about people like me or someone who DOESN'T care about people like me"
Jan18,q40cf2,"Q40c.F2. As I read some pairs of opposite phrases, tell me which one best reflects your impression of Donald Trump. A strong leader or NOT a strong leader"
Jan18,q40df1,"Q40d.F1. As I read some pairs of opposite phrases, tell me which one best reflects your impression of Donald Trump. A good communicator or NOT a good communicator?"
Jan18,q40ef1,"Q40e.F1. As I read some pairs of opposite phrases, tell me which one best reflects your impression of Donald Trump. Able to get things done or NOT able to get things done"
Jan18,q40ff1,"Q40f.F1. As I read some pairs of opposite phrases, tell me which one best reflects your impression of Donald Trump. Even tempered or NOT even tempered"
Jan18,q40gf2,"Q40g.F2. As I read some pairs of opposite phrases, tell me which one best reflects your impression of Donald Trump. Well informed or NOT well informed"
Jan18,q40hf2,"Q40h.F2. As I read some pairs of opposite phrases, tell me which one best reflects your impression of Donald Trump. Keeps his promises or DOESN'T keep his promises"
Jan18,q41f1,"Q.41F1. Do you think Trump has a responsibility to publicly release his tax returns, or does he not have this responsibility?"
Jan18,q42f2,Q.42F2. How confident are you that Donald Trump keeps his own business interests separate from the decisions he makes as president?
Jan18,q44f2,"Q.44F2. This year, should Donald Trump..."
Jan18,q53,Q.53. Do you approve or disapprove of the tax law passed by Donald Trump and Congress last month?
Jan18,q81,"Q.81. Thinking about the situation in the Middle East these days, do you think Donald Trump is [RANDOMIZE: favoring Israel too much; favoring the Palestinians too much] or striking about the right balance?"
Mar18,q2,Do you approve or disapprove of the way Donald Trump is handling his job as President? [IF DK ENTER AS DK. IF DEPENDS PROBE ONCE WITH: Overall do you approve or disapprove of the way Donald Trump is handling his job as President?
Mar18,q24,How much respect do you think Donald Trump has for this country's democratic institutions and traditions?
Mar18,q41,What's your impression of people who do NOT approve of the job Donald Trump is doing as president?
Mar18,q42,What's your impression of people who approve of the job Donald Trump is doing as president?
Mar18,q50,How confident are you that the Trump administration will make a serious effort to prevent Russia from influencing future U.S. elections? Are you? [READ]
Mar18,q94,"Do you think senior members of the Trump administration definitely did, probably did, probably did NOT or definitely did NOT have improper contact with Russia during the 2016 presidential campaign?"
May18,q2,Q.2. Do you approve or disapprove of the way Donald Trump is handling his job as President?
May18,q35,"Q35. Thinking about important issues facing the country today, overall, would you say you tend to agree with Donald Trump on..."
May18,q36,"Q36. Now thinking NOT about issues, but just about the way Donald Trump conducts himself as president, would you say you..."
May18,q60a,"Q60a. Thinking about Donald Trump's ability to handle a number of things, please tell me whether you are very confident, somewhat confident, not too confident, or not at all confident that Trump can Negotiate favorable trade agreements with other countries"
May18,q60b,"Q60b. Thinking about Donald Trump's ability to handle a number of things, please tell me whether you are very confident, somewhat confident, not too confident, or not at all confident that Trump can Make wise decisions about immigration policy ?"
May18,q60c,"Q60c. Thinking about Donald Trump's ability to handle a number of things, please tell me whether you are very confident, somewhat confident, not too confident, or not at all confident that Trump can Manage the Executive Branch effectively ?"
May18,q60d,"Q60d. Thinking about Donald Trump's ability to handle a number of things, please tell me whether you are very confident, somewhat confident, not too confident, or not at all confident that Trump can Handle an international crisis ?"
May18,q60ef1,"Q60ef1. Thinking about Donald Trump's ability to handle a number of things, please tell me whether you are very confident, somewhat confident, not too confident, or not at all confident that Trump can Make good appointments to the federal courts ?"
May18,q60ff1,"Q60ff1. Thinking about Donald Trump's ability to handle a number of things, please tell me whether you are very confident, somewhat confident, not too confident, or not at all confident that Trump can Use military force wisely ?"
May18,q60gf2,"Q60gf2. Thinking about Donald Trump's ability to handle a number of things, please tell me whether you are very confident, somewhat confident, not too confident, or not at all confident that Trump can Work effectively with Congress ?"
May18,q60hf2,"Q60hf2. Thinking about Donald Trump's ability to handle a number of things, please tell me whether you are very confident, somewhat confident, not too confident, or not at all confident that Trump can Make good decisions about economic policy ?"
May18,q60if2,"Q60i.F2. Thinking about Donald Trump's ability to handle a number of things, please tell me whether you are very confident, somewhat confident, not too confident, or not at all confident that Trump can Handle the situation with Iran ?"
May18,q62,"Q.62 Overall, how would you rate the ethical standards of top Trump administration officials--excellent, good, not good or poor?"
May18,pvote16a,"PVOTE16A. In the 2016 presidential election between Donald Trump and Hillary Clinton, did things come up that kept you from voting, or did you happen to vote?"
Jun18,q2,Q.2. Do you approve or disapprove of the way Donald Trump is handling his job as President?
Jun18,q30,"Q.30. Do you think of your vote for Congress as a vote FOR Donald Trump, as a vote AGAINST Donald Trump, or isn't Donald Trump much of a factor in your vote?"
Jun18,q39,Q.39. How much respect do you think Donald Trump has for this country's democratic institutions and traditions? [READ]
Jun18,q40,"Q.40. How confident, if at all, are you that Donald Trump keeps his own business interests separate from the decisions he makes as president? [READ]"
Jun18,q41a,"Q41a. Thinking about some different groups... how much respect do you think Donald Trump has for People like you ? A great deal, a fair amount, not too much or none at all?"
Jun18,q41bf1,"Q41bf1. Thinking about some different groups... how much respect do you think Donald Trump has for Women ? A great deal, a fair amount, not too much or none at all?"
Jun18,q41cf1,"Q41cf1. Thinking about some different groups... how much respect do you think Donald Trump has for Men ? A great deal, a fair amount, not too much or none at all?"
Jun18,q41df1,"Q41df1. Thinking about some different groups... how much respect do you think Donald Trump has for White people ? A great deal, a fair amount, not too much or none at all?"
Jun18,q41ef1,"Q41ef1. Thinking about some different groups... how much respect do you think Donald Trump has for Black people ? A great deal, a fair amount, not too much or none at all?"
Jun18,q41ff1,"Q41ff1. Thinking about some different groups... how much respect do you think Donald Trump has for Hispanic people ? A great deal, a fair amount, not too much or none at all?"
Jun18,q41gf2,"Q41gf2. Thinking about some different groups... how much respect do you think Donald Trump has for Veterans ? A great deal, a fair amount, not too much or none at all?"
Jun18,q41hf2,"Q41hf2. Thinking about some different groups... how much respect do you think Donald Trump has for Muslims ? A great deal, a fair amount, not too much or none at all?"
Jun18,q41if2,"Q41if2. Thinking about some different groups... how much respect do you think Donald Trump has for Evangelical Christians ? A great deal, a fair amount, not too much or none at all?"
Jun18,q41jf2,"Q41jf2. Thinking about some different groups... how much respect do you think Donald Trump has for Immigrants ? A great deal, a fair amount, not too much or none at all?"
Jun18,q41lf2,"Q41lf2. Thinking about some different groups... how much respect do you think Donald Trump has for People who voted for Hillary Clinton ? A great deal, a fair amount, not too much or none at all?"
Jun18,q42,"Q.42. Would you say you trust what Donald Trump says more, about the same, or less than you trusted what previous presidents said while in office?"
Jun18,q68,"Q.68. If Democrats take control of Congress this fall, how concerned are you, if at all, that they will focus too much on investigating the Trump administration? [READ]"
Jun18,q69,"Q.69. If Republicans keep control of Congress this fall, how concerned are you, if at all, that they will not focus enough on oversight of the Trump administration? [READ]"
Jun18,q104,"Q.104. How confident, if at all, are you that Donald Trump will handle matters related to the special counsel investigation appropriately? Very confident, somewhat confident, not too confident or not at all confident?"
Jun18,q105,Q.105 Do you think that Donald Trump has changed the Republican Party [RANDOMIZE: for the better/for the worse] or don't you think he has changed the Republican Party much either way?
W161,POL1DT_W161,POL1DT_W161. Do you approve or disapprove of the way Donald Trump is handling his job as president?

There are many, but they are different questions: approval of Trump on specific issues (economy, tariffs, immigration...), opinions about his policies, about people who approve or disapprove of him, and so on.

In [11]:
def question_key(text):
    words = re.sub(r"[^a-z0-9 ]", " ", text.lower()).split()
    while words and (words[0] in ("q", "qa") or any(ch.isdigit() for ch in words[0])):
        words.pop(0)
    return " ".join(words[:12])

trump_vars["key"] = trump_vars["question text"].map(question_key)
in_waves = trump_vars.groupby("key")["wave"].nunique().sort_values(ascending=False)
in_waves.head(6).to_frame("in how many files")

                                                                           in how many files
key
do you approve or disapprove of the way donald trump is handling                           9
how much respect do you think donald trump has for this country                            3
as i read some pairs of opposite phrases tell me which one                                 2
do you think of your vote for congress as a vote for                                       2
do you think that donald trump has changed the republican party randomize                  2
would you say you trust what donald trump says more about the                              2

Only the **overall job approval** question ("Do you approve or disapprove of the way Donald Trump is handling his job as President?") is asked in all of them; the next most common Trump question appears in only a few files. The issue-specific questions are different in every survey. This is why we use overall job approval as the benchmark: it is the only Trump measure that can be followed from wave to wave.

### The approval question

In [12]:
rows = []
for w in WAVE_ORDER:
    for c, l in labels[w].items():
        if l and "trump" in l.lower() and "handling his job" in l.lower():
            rows.append({"wave": w, "variable": c, "question text": l[:110]})
approval_candidates = pd.DataFrame(rows)
approval_candidates

,wave,variable,question text
0,Feb17,q1,Q.1 Do you approve or disapprove of the way Donald Trump is handling his job as President? [IF DK ENTER AS DK.
1,Apr17,q1,Q.1 Do you approve or disapprove of the way Donald Trump is handling his job as President? [IF DK ENTER AS DK.
2,Typology17,qa1,Q.A1 Do you approve or disapprove of the way Donald Trump is handling his job as President? [IF DK ENTER AS DK
3,Jan18,q2,Q.2. Do you approve or disapprove of the way Donald Trump is handling his job as President?
4,Mar18,q2,Do you approve or disapprove of the way Donald Trump is handling his job as President? [IF DK ENTER AS DK. IF
5,May18,q2,Q.2. Do you approve or disapprove of the way Donald Trump is handling his job as President?
6,Jun18,q2,Q.2. Do you approve or disapprove of the way Donald Trump is handling his job as President?
7,W161,POL1DT_W161,POL1DT_W161. Do you approve or disapprove of the way Donald Trump is handling his job as president?
8,W161,POL1DTSTR_W161,POL1DTSTR_W161. Do you approve/disapprove of the way Donald Trump is handling his job as president...
9,W167,POL1DT_W167,POL1DT_W167. Do you approve or disapprove of the way Donald Trump is handling his job as president?
10,W167,POL1DTSTR_W167,POL1DTSTR_W167. Do you approve/disapprove of the way Donald Trump is handling his job as president...

In some files the approval question is `q1`, in others it is `q2`

In [13]:
rows = []
for w in ["Feb17", "Apr17", "Jan18", "Mar18", "May18", "Jun18"]:
    rows.append({"wave": w, "q1": labels[w].get("q1", "")[:75], "q2": labels[w].get("q2", "")[:75]})
pd.DataFrame(rows).set_index("wave")

,q1,q2
wave,,
Feb17,Q.1 Do you approve or disapprove of the way Donald Trump is handling his jo,"Q.2 All in all, are you satisfied or dissatisfied with the way things are g"
Apr17,Q.1 Do you approve or disapprove of the way Donald Trump is handling his jo,"Q.2 All in all, are you satisfied or dissatisfied with the way things are g"
Jan18,"Q.1. All in all, are you satisfied or dissatisfied with the way things are",Q.2. Do you approve or disapprove of the way Donald Trump is handling his j
Mar18,"All in all, are you satisfied or dissatisfied with the way things are going",Do you approve or disapprove of the way Donald Trump is handling his job as
May18,"Q.1. All in all, are you satisfied or dissatisfied with the way things are",Q.2. Do you approve or disapprove of the way Donald Trump is handling his j
Jun18,"Q.1. All in all, are you satisfied or dissatisfied with the way things are",Q.2. Do you approve or disapprove of the way Donald Trump is handling his j

In Feb17 and Apr17 approval is `q1`, but in all 2018 files `q1` is "satisfied with the direction of the country" and approval is `q2`. If we merged by column name, we would mix two different questions.

## 5. How the answers are coded

In [14]:
APPROVAL_VAR = {}
for w in WAVE_ORDER:
    hits = approval_candidates[(approval_candidates["wave"] == w) &
                               approval_candidates["question text"].str.contains("approve or disapprove")]
    assert len(hits) == 1, (w, hits)
    APPROVAL_VAR[w] = hits["variable"].iloc[0]
APPROVAL_VAR

{'Feb17': 'q1',
 'Apr17': 'q1',
 'Typology17': 'qa1',
 'Jan18': 'q2',
 'Mar18': 'q2',
 'May18': 'q2',
 'Jun18': 'q2',
 'W161': 'POL1DT_W161',
 'W167': 'POL1DT_W167'}

In [15]:
tab = pd.DataFrame({w: surveys[w][APPROVAL_VAR[w]].value_counts(dropna=False) for w in WAVE_ORDER}).T
tab.columns = ["not asked (NaN)" if pd.isna(c) else int(c) for c in tab.columns]
tab = tab.fillna(0).astype(int)
print("Code labels in the files:")
print("  phone (Apr17):", vlabels("Apr17", APPROVAL_VAR["Apr17"]))
print("  ATP (W161):   ", vlabels("W161", APPROVAL_VAR["W161"]))
tab

Code labels in the files:
  phone (Apr17): {1.0: 'Approve', 2.0: 'Disapprove', 9.0: "Don't know/Refused (VOL.)"}
  ATP (W161):    {1.0: 'Approve', 2.0: 'Disapprove', 99.0: "Don't know/Refused/Web blank"}

               1     2    9  99  not asked (NaN)
Feb17        572   861   70   0                0
Apr17        606   819   76   0                0
Typology17   985  1385  134   0             2505
Jan18        563   854   86   0                0
Mar18        595   796   75   0                0
May18        614   804   85   0                0
Jun18        823  1072  107   0                0
W161        2273  2726    0  87                0
W167        1384  2178    0  27                0

In Typology17, 2,505 respondents have NaN

## 6. Date formats

In [16]:
rows = []
for w in WAVE_ORDER:
    for c, l in labels[w].items():
        if l and any(k in l.lower() for k in ["interview date", "interview start", "first call"]):
            rows.append({"wave": w, "variable": c, "label": l[:60], "dtype": str(surveys[w][c].dtype),
                         "first values": surveys[w][c].dropna().iloc[:2].tolist()})
date_candidates = pd.DataFrame(rows)
date_candidates

,wave,variable,label,dtype,first values
0,Feb17,int_date,Interview date,float64,"[21017.0, 21217.0]"
1,Feb17,fcall,Date of first call to number,float64,"[170207.0, 170207.0]"
2,Apr17,int_date,Interview date,float64,"[40517.0, 40517.0]"
3,Apr17,fcall,Date of first call to number,float64,"[170405.0, 170405.0]"
4,Typology17,int_date,Interview date,float64,"[61417.0, 60817.0]"
5,Jan18,int_date,"Interview date (NOTE: Final interviewer date, adjusted for i",float64,"[180110.0, 180110.0]"
6,Jan18,fcall,Date of first call (NOTE: different from SRBI's standard fca,float64,"[180110.0, 180110.0]"
7,Mar18,ftcalldt,Date of first call attempt,object,"[2018-03-08, 2018-03-12]"
8,May18,int_date,"Interview date (NOTE: Final interviewer date, adjusted for i",float64,"[180425.0, 180425.0]"
9,May18,fcall,Date of first call (NOTE: different from SRBI's standard fca,float64,"[180425.0, 180425.0]"
10,Jun18,int_date,"Interview date (NOTE: Final interviewer date, adjusted for i",float64,"[180605.0, 180605.0]"
11,Jun18,fcall,Date of first call (NOTE: different from SRBI's standard fca,float64,"[180605.0, 180605.0]"
12,W161,INTERVIEW_START_W161,INTERVIEW_START_W161. Interview start time,object,"[28-Jan-2025 21:38:38, 29-Jan-2025 12:54:51]"
13,W167,INTERVIEW_START_W167,INTERVIEW_START_W167. Interview start time,object,"[08-Apr-2025 15:12:07, 08-Apr-2025 14:50:19]"

Most files have both an interview date (`int_date`) and the date of the first call (`fcall`). **March18 has only the date of the first call** (`ftcalldt`), and the ATP files have an interview start time as text.

In [17]:
DATE_VAR = {}
for w in WAVE_ORDER:
    cand = date_candidates[date_candidates["wave"] == w]
    interview = cand[cand["label"].str.contains("Interview date|Interview start", case=False)]
    DATE_VAR[w] = (interview if len(interview) else cand)["variable"].iloc[0]
DATE_VAR

{'Feb17': 'int_date',
 'Apr17': 'int_date',
 'Typology17': 'int_date',
 'Jan18': 'int_date',
 'Mar18': 'ftcalldt',
 'May18': 'int_date',
 'Jun18': 'int_date',
 'W161': 'INTERVIEW_START_W161',
 'W167': 'INTERVIEW_START_W167'}

The 2017 and 2018 dates are just numbers (`40517`, `180110`). We try two hypotheses on each of them: **MMDDYY** (with the leading zero missing, so `40517` -> `040517`) and **YYMMDD**, and see which one gives sensible dates for a file named e.g. `Apr17`:

In [18]:
def try_format(s, fmt):
    txt = s.dropna().astype("int64").astype(str).str.zfill(6) 
    return pd.to_datetime(txt, format=fmt, errors="coerce")

rows = []
for w in WAVE_ORDER:
    s = surveys[w][DATE_VAR[w]]
    if s.dtype == "float64":         
        for fmt, name in [("%m%d%y", "MMDDYY"), ("%y%m%d", "YYMMDD")]:
            d = try_format(s, fmt)
            rows.append({"wave": w, "raw example": int(s.iloc[0]), "format tried": name,
                         "not parsed": int(d.isna().sum()), "earliest": d.min(), "latest": d.max()})
pd.DataFrame(rows).set_index("wave")

            raw example format tried  not parsed   earliest     latest
wave
Feb17             21017       MMDDYY           0 2017-02-07 2017-02-12
Feb17             21017       YYMMDD           0 2002-07-17 2002-12-17
Apr17             40517       MMDDYY           0 2017-04-05 2017-04-11
Apr17             40517       YYMMDD           0 2004-05-17 2004-11-17
Typology17        61417       MMDDYY           0 2017-06-08 2017-07-09
Typology17        61417       YYMMDD        2210 2006-08-17 2007-09-17
Jan18            180110       MMDDYY        1503        NaT        NaT
Jan18            180110       YYMMDD           0 2018-01-10 2018-01-16
May18            180425       MMDDYY        1503        NaT        NaT
May18            180425       YYMMDD           0 2018-04-25 2018-05-01
Jun18            180605       MMDDYY        2002        NaT        NaT
Jun18            180605       YYMMDD           0 2018-06-05 2018-06-12

Only one hypothesis works for each file:
- 2017 files (Feb17, Apr17, Typology17): **MMDDYY**. `40517` is 05.04.2017. With YYMMDD we would get dates in 2002-2007, and for Typology17 more than half of the values would not parse at all.
- 2018 files (Jan18, May18, Jun18): **YYMMDD**. `180110` is 10.01.2018. With MMDDYY the month would be 18, which does not exist, so nothing parses.
- March18: the first-call date is already a proper date.
- ATP: a string like `'28-Jan-2025 21:38:38'`.

In [19]:
DATE_FMT = {"Feb17": "mddyy", "Apr17": "mddyy", "Typology17": "mddyy",
            "Jan18": "yymmdd", "Mar18": "date", "May18": "yymmdd", "Jun18": "yymmdd",
            "W161": "atp", "W167": "atp"}

def parse_dates(s, fmt):
    if fmt in ("mddyy", "yymmdd"):
        txt = s.dropna().astype("int64").astype(str).str.zfill(6)      # 40517 -> "040517"
        out = pd.to_datetime(txt, format="%m%d%y" if fmt == "mddyy" else "%y%m%d")
    elif fmt == "date":
        out = pd.to_datetime(s.dropna())                               # already a date
    elif fmt == "atp":
        out = pd.to_datetime(s.dropna(), format="%d-%b-%Y %H:%M:%S")   # '28-Jan-2025 21:38:38'
    return out.reindex(s.index).dt.normalize()                         # drop the time of day

rows = []
for w in WAVE_ORDER:
    parsed = parse_dates(surveys[w][DATE_VAR[w]], DATE_FMT[w])
    rows.append({"wave": w, "variable": DATE_VAR[w], "format": DATE_FMT[w],
                 "earliest": parsed.min().date(), "latest": parsed.max().date(),
                 "field days": (parsed.max() - parsed.min()).days})
pd.DataFrame(rows).set_index("wave")

                        variable  format    earliest      latest  field days
wave
Feb17                   int_date   mddyy  2017-02-07  2017-02-12           5
Apr17                   int_date   mddyy  2017-04-05  2017-04-11           6
Typology17              int_date   mddyy  2017-06-08  2017-07-09          31
Jan18                   int_date  yymmdd  2018-01-10  2018-01-16           6
Mar18                   ftcalldt    date  2018-03-07  2018-03-13           6
May18                   int_date  yymmdd  2018-04-25  2018-05-01           6
Jun18                   int_date  yymmdd  2018-06-05  2018-06-12           7
W161        INTERVIEW_START_W161     atp  2025-01-27  2025-02-02           6
W167        INTERVIEW_START_W167     atp  2025-04-07  2025-04-13           6

Every wave lasted 5-7 days, except Typology17: its field period is 31 days.

## 7. Typology-17: the approval question was not asked to everyone

The file has a phase variable (Phase A / Phase B).

In [20]:
ty = surveys["Typology17"].copy()
ty["date"] = parse_dates(ty["int_date"], "mddyy")
ty["asked approval question (qa1)"] = ty["qa1"].notna()
ty["phase"] = ty["phase"].map(vlabels("Typology17", "phase"))

print(pd.crosstab(ty["phase"], ty["asked approval question (qa1)"]))
print()
print(ty.groupby("phase")["date"].agg(["min", "max", "count"]))

asked approval question (qa1)  False  True
phase
Phase A                            0   2504
Phase B                         2505      0

               min        max  count
phase
Phase A 2017-06-08 2017-06-18   2504
Phase B 2017-06-27 2017-07-09   2505

The approval question was asked **only in Phase A** (June 8-18, 2017, 2,504 respondents). Phase B (June 27 - July 9) never received it. The topline PDF says the same: the question is labelled "ASK ALL PHASE A". So for approval we will keep only respondents with a non-empty `qa1`.

## 8. Weights

In [21]:
rows = []
for w in WAVE_ORDER:
    for c in surveys[w].columns:
        if "weight" in c.lower():
            rows.append({"wave": w, "variable": c, "label": (labels[w].get(c) or "")[:60]})
pd.DataFrame(rows).set_index("wave")

               variable                   label
wave
Feb17        cellweight  Weight for cell sample
Feb17            weight            Final Weight
Apr17          utweight      Untruncated weight
Apr17            weight            Final Weight
Typology17       weight   Final combined weight
Jan18        cellweight        Final cellweight
Jan18            weight            Final weight
Mar18        cellweight       Final cell weight
Mar18            weight            Final weight
May18        cellweight        Final cellweight
May18            weight            Final weight
Jun18        cellweight        Final cellweight
Jun18            weight            Final weight
W161        WEIGHT_W161         Wave 161 weight
W167        WEIGHT_W167         Wave 167 weight

Some phone files have several weights, and we want the **final** one: it is called `weight` in the phone files and `WEIGHT_W161` / `WEIGHT_W167` in ATP.

In [22]:
WEIGHT_VAR = {w: ("weight" if w in phone else f"WEIGHT_{w}") for w in WAVE_ORDER}

pd.DataFrame({
    w: {"variable": WEIGHT_VAR[w], "label": labels[w][WEIGHT_VAR[w]][:25], "n": len(surveys[w]),
        "sum of weights": round(surveys[w][WEIGHT_VAR[w]].sum()),
        "min": round(surveys[w][WEIGHT_VAR[w]].min(), 2),
        "max": round(surveys[w][WEIGHT_VAR[w]].max(), 2)}
    for w in WAVE_ORDER
}).T

,variable,label,n,sum of weights,min,max
Feb17,weight,Final Weight,1503,4852,1.0,7.67
Apr17,weight,Final Weight,1501,4319,1.0,6.68
Typology17,weight,Final combined weight,5009,16254,1.0,8.45
Jan18,weight,Final weight,1503,1503,0.3,2.38
Mar18,weight,Final weight,1466,1466,0.23,2.94
May18,weight,Final weight,1503,1503,0.34,2.53
Jun18,weight,Final weight,2002,2002,0.31,2.43
W161,WEIGHT_W161,Wave 161 weight,5086,5086,0.16,3.5
W167,WEIGHT_W167,Wave 167 weight,3589,3589,0.13,2.72

The weight scales differ. In 2017 the sums are 4,852 / 4,319 / 16,254, while in 2018 and 2025 the sum of weights equals the number of respondents. So we will compute percentages **within each wave**, and if waves are ever pooled, weights must first be rescaled within each wave (for example divided by the wave's mean weight, so that the mean is 1).

## 9. The "how strongly" follow-up question

After the approval question there is a follow-up: "very strongly or not so strongly?". In the tables above it comes right after the main question (`q1` -> `q1a`, `q2` -> `q2a`, `POL1DT` -> `POL1DTSTR`)

In [23]:
STRENGTH_VAR = {}
for w in WAVE_ORDER:
    cols = list(surveys[w].columns)
    STRENGTH_VAR[w] = None
    for c in cols[cols.index(APPROVAL_VAR[w]) + 1:]:
        codes = " ".join(str(v).lower() for v in vlabels(w, c).values())
        if "very strongly" in codes and "not so strongly" in codes:
            STRENGTH_VAR[w] = c
            break

pd.DataFrame([{"wave": w, "approval": APPROVAL_VAR[w], "follow-up": STRENGTH_VAR[w],
               "question text": (labels[w].get(STRENGTH_VAR[w]) or "-")[:75]} for w in WAVE_ORDER]).set_index("wave")

,approval,follow-up,question text
wave,,,
Feb17,q1,q1a,"Q.1a Do you [approve/disapprove] very strongly, or not so strongly?"
Apr17,q1,q1a,"Q.1a Do you [approve/disapprove] very strongly, or not so strongly?"
Typology17,qa1,qa1a,"Q.A1a Do you [approve/disapprove] very strongly, or not so strongly?"
Jan18,q2,q2a,"Q.2a. Do you [approve/disapprove] very strongly, or not so strongly?"
Mar18,q2,None,-
May18,q2,q2a,"Q.2a. Do you [approve/disapprove] very strongly, or not so strongly?"
Jun18,q2,None,-
W161,POL1DT_W161,POL1DTSTR_W161,POL1DTSTR_W161. Do you approve/disapprove of the way Donald Trump is handli
W167,POL1DT_W167,POL1DTSTR_W167,POL1DTSTR_W167. Do you approve/disapprove of the way Donald Trump is handli

The follow-up question exists in 7 of the 9 files. **Mar18 and Jun18 do not have it**, so approval strength will be missing for those two waves.

In [43]:
for w in WAVE_ORDER:
    if STRENGTH_VAR[w]:
        print(w, STRENGTH_VAR[w], vlabels(w, STRENGTH_VAR[w]))

Feb17 q1a {1.0: 'Very strongly', 2.0: 'Not so strongly', 9.0: "Don't know/Refused (VOL.)"}
Apr17 q1a {1.0: 'Very strongly', 2.0: 'Not so strongly', 9.0: "Don't know/Refused (VOL.)"}
Typology17 qa1a {1.0: 'Very strongly', 2.0: 'Not so strongly', 9.0: "Don't know/Refused (VOL.)"}
Jan18 q2a {1.0: 'Very strongly', 2.0: 'Not so strongly', 9.0: "(VOL) Don't know/Refused"}
May18 q2a {1.0: 'Very strongly', 2.0: 'Not so strongly', 9.0: "(VOL) Don't know/Refused"}
W161 POL1DTSTR_W161 {1.0: 'Very strongly', 2.0: 'Not so strongly', 99.0: "Don't know/Refused/Web blank"}
W167 POL1DTSTR_W167 {1.0: 'Very strongly', 2.0: 'Not so strongly', 99.0: "Don't know/Refused/Web blank"}

## 10. Party, ideology, education, age, gender

In [24]:
def find_vars(pattern):
    return pd.DataFrame({w: [", ".join(c for c in surveys[w].columns if re.match(pattern, c, re.I))]
                         for w in WAVE_ORDER}, index=["variables found"]).T

def describe(wave, pattern, cut=22):
    rows = [{"variable": c, "question text": (labels[wave].get(c) or "")[:70],
             "codes": {k: s[:cut] for k, s in vlabels(wave, c).items()}}
            for c in surveys[wave].columns if re.match(pattern, c, re.I)]
    return pd.DataFrame(rows).set_index("variable")

def show_choice(varmap, cut=28):
    return pd.DataFrame([{"wave": w, "variable": v, "question text": (labels[w].get(v) or "")[:55],
                          "codes": {k: s[:cut] for k, s in vlabels(w, v).items()}}
                         for w, v in varmap.items()]).set_index("wave")

In [25]:
rows = []
for w in WAVE_ORDER:
    for c, l in labels[w].items():
        if l and "unique" in l.lower():
            rows.append({"wave": w, "variable": c, "question text": l[:70], "all values different": surveys[w][c].is_unique})
id_candidates = pd.DataFrame(rows).set_index("wave")
ID_VAR = id_candidates["variable"].to_dict()
id_candidates

,variable,question text,all values different
wave,,,
Feb17,psraid,Unique ID,True
Apr17,psraid,Unique ID,True
Typology17,mergeid,Unique ID after merge,True
Jan18,respid,Individual unique respondent identification number,True
Mar18,masterid,Imported from sample file: Unique Respondent ID,True
May18,respid,Individual unique respondent identification number,True
Jun18,respid,Individual unique respondent identification number,True
W161,QKEY,QKEY_W161. Unique identifier,True
W167,QKEY,QKEY_W167. QKEY. Unique identifier,True

One ID variable per file, and all its values are different, so it identifies a respondent within a wave. The names are again different (`psraid`, `respid`, `masterid`, `mergeid`, `QKEY`).

In [26]:
find_vars(r"(f_)?party")

                                                                                                           variables found
Feb17                                                                                  party, partyln, partysum, partyideo
Apr17                                                                                  party, partyln, partysum, partyideo
Typology17                                                                   party, partyln, partystr, partysum, partyideo
Jan18                                                                                  party, partyln, partysum, partyideo
Mar18                                                                                  party, partyln, partysum, partyideo
May18                                                                    party, partyln, partysum, partyideo, partysumideo
Jun18                                                                    party, partyln, partysum, partyideo, partysumideo
W161        F_PARTY_FINAL, F_PARTYLN_FINAL, F_PARTYSTR_FINAL, F_PARTYLNCLOSE_FINAL, F_PARTYSUM_FINAL, F_PARTYSUMIDEO_FINAL
W167        F_PARTY_FINAL, F_PARTYLN_FINAL, F_PARTYSTR_FINAL, F_PARTYLNCLOSE_FINAL, F_PARTYSUM_FINAL, F_PARTYSUMIDEO_FINAL

In [27]:
print("Apr17 (phone):")
display(describe("Apr17", r"(f_)?party"))
print("W161 (ATP):")
display(describe("W161", r"(f_)?party"))

Apr17 (phone):

,question text,codes
variable,,
party,"PARTY. In politics TODAY, do you consider yourself a Republican, Democ","{1.0: 'Republican', 2.0: 'Democrat', 3.0: 'Independent', 4.0: 'No preference (VOL.)', 5.0: 'Other party (VOL.)', 9.0: 'Don't know/Refused (VO'}"
partyln,PARTYLN. As of today do you lean more to the Republican Party or more,"{1.0: 'Republican', 2.0: 'Democrat', 9.0: 'Other/Don't know/Refus'}"
partysum,Leaned party identification,"{1.0: 'Rep/lean Rep', 2.0: 'Dem/lean Dem', 9.0: 'DK/Ref-no lean'}"
partyideo,Party and Ideology,"{1.0: 'Cons Rep', 2.0: 'Mod-Lib Rep', 3.0: 'Ind', 4.0: 'Cons-Mod Dem', 5.0: 'Lib Dem', 9.0: 'DK/Ref to party or ide'}"

W161 (ATP):

,question text,codes
variable,,
F_PARTY_FINAL,Party,"{1.0: 'Republican', 2.0: 'Democrat', 3.0: 'Independent', 4.0: 'Something else', 99.0: 'Refused'}"
F_PARTYLN_FINAL,Party lean,"{1.0: 'The Republican Party', 2.0: 'The Democratic Party', 99.0: 'Refused'}"
F_PARTYSTR_FINAL,Party strength,"{1.0: 'Strongly', 2.0: 'Not strongly', 99.0: 'Refused'}"
F_PARTYLNCLOSE_FINAL,Party closeness among leaners,"{1.0: 'Extremely close', 2.0: 'Very close', 3.0: 'Somewhat close', 4.0: 'Not too close', 5.0: 'Not at all close', 99.0: 'Refused'}"
F_PARTYSUM_FINAL,Party summary,"{1.0: 'Rep/Lean Rep', 2.0: 'Dem/Lean Dem', 9.0: 'DK/Refused/No lean'}"
F_PARTYSUMIDEO_FINAL,Combining ideology and party identification,"{1.0: 'Conservative Rep/Lean', 2.0: 'Moderate/Liberal Rep/L', 3.0: 'Moderate/Conservative ', 4.0: 'Liberal Dem/Lean', 9.0: 'Refused either F_IDEO '}"

So `party` is the plain party question, `partyln` is the follow-up "which party do you lean to", `partystr` is strength, `partyideo` mixes party with ideology, and `partysum` (`F_PARTYSUM_FINAL` in ATP) is the **summary that puts leaners together with Republicans/Democrats**. That is what we need to split respondents into Rep/Dem. Let's check its text and codes in every file:

In [28]:
PARTY_VAR = {w: ("F_PARTYSUM_FINAL" if w in atp else "partysum") for w in WAVE_ORDER}
show_choice(PARTY_VAR)

,variable,question text,codes
wave,,,
Feb17,partysum,Leaned party identification,"{1.0: 'Rep/lean Rep', 2.0: 'Dem/lean Dem', 9.0: 'DK/Ref-no lean'}"
Apr17,partysum,Leaned party identification,"{1.0: 'Rep/lean Rep', 2.0: 'Dem/lean Dem', 9.0: 'DK/Ref-no lean'}"
Typology17,partysum,Leaned party identification,"{1.0: 'Rep/lean Rep', 2.0: 'Dem/lean Dem', 9.0: 'DK/Ref-no lean'}"
Jan18,partysum,Leaned party identification,"{1.0: 'Rep/lean Rep', 2.0: 'Dem/lean Dem', 9.0: 'DK/Ref-no lean'}"
Mar18,partysum,Leaned party identification,"{1.0: 'Rep/lean Rep', 2.0: 'Dem/lean Dem', 9.0: 'DK/Ref-no lean'}"
May18,partysum,Leaned party identification,"{1.0: 'Rep/lean Rep', 2.0: 'Dem/lean Dem', 9.0: 'DK/Ref-no lean'}"
Jun18,partysum,Leaned party identification,"{1.0: 'Rep/lean Rep', 2.0: 'Dem/lean Dem', 9.0: 'DK/Ref-no lean'}"
W161,F_PARTYSUM_FINAL,Party summary,"{1.0: 'Rep/Lean Rep', 2.0: 'Dem/Lean Dem', 9.0: 'DK/Refused/No lean'}"
W167,F_PARTYSUM_FINAL,Party summary,"{1.0: 'Rep/Lean Rep', 2.0: 'Dem/Lean Dem', 9.0: 'DK/Refused/No lean'}"

The codes are the same everywhere: 1 = Rep/lean Rep, 2 = Dem/lean Dem, 9 = other/DK. Only the variable names differ.

**Ideology.**

In [29]:
find_vars(r"(f_)?ideo")

              variables found
Feb17                    ideo
Apr17                    ideo
Typology17  ideoconsist, ideo
Jan18                    ideo
Mar18                    ideo
May18                    ideo
Jun18                    ideo
W161                   F_IDEO
W167                   F_IDEO

Let's see what these are (Apr17, Typology17 and W161 as examples):

In [30]:
print("Apr17 (phone):")
display(describe("Apr17", r".*ideo"))
print("Typology17:")
display(describe("Typology17", r"ideo"))
print("W161 (ATP):")
display(describe("W161", r".*ideo"))

Apr17 (phone):

,question text,codes
variable,,
ideo,"IDEO. In general, would you describe your political views as... [READ]","{1.0: 'Very conservative', 2.0: 'Conservative', 3.0: 'Moderate', 4.0: 'Liberal', 5.0: 'Very liberal', 9.0: 'Don't know/Refused (VO'}"
partyideo,Party and Ideology,"{1.0: 'Cons Rep', 2.0: 'Mod-Lib Rep', 3.0: 'Ind', 4.0: 'Cons-Mod Dem', 5.0: 'Lib Dem', 9.0: 'DK/Ref to party or ide'}"

Typology17:

,question text,codes
variable,,
ideoconsist,Ideoconsist variable - Combining consCount10 and libCount10 - Phase A,{}
ideo,"IDEO. In general, would you describe your political views as... [READ]","{1.0: 'Very conservative', 2.0: 'Conservative', 3.0: 'Moderate', 4.0: 'Liberal', 5.0: 'Very liberal', 9.0: 'Don't know/Refused (VO'}"

W161 (ATP):

,question text,codes
variable,,
F_PARTYSUMIDEO_FINAL,Combining ideology and party identification,"{1.0: 'Conservative Rep/Lean', 2.0: 'Moderate/Liberal Rep/L', 3.0: 'Moderate/Conservative ', 4.0: 'Liberal Dem/Lean', 9.0: 'Refused either F_IDEO '}"
F_IDEO,Ideology,"{1.0: 'Very conservative', 2.0: 'Conservative', 3.0: 'Moderate', 4.0: 'Liberal', 5.0: 'Very liberal', 99.0: 'Refused'}"

`ideo` (phone) and `F_IDEO` (ATP) are the plain ideology question. The others either combine ideology with party (`partyideo`, `partysumideo`, `F_PARTYSUMIDEO_FINAL`) or are an index made for the Typology study (`ideoconsist`), so we do not use them.

In [31]:
IDEO_VAR = {w: ("F_IDEO" if w in atp else "ideo") for w in WAVE_ORDER}
show_choice(IDEO_VAR)

,variable,question text,codes
wave,,,
Feb17,ideo,"IDEO. In general, would you describe your political vie","{1.0: 'Very conservative', 2.0: 'Conservative', 3.0: 'Moderate', 4.0: 'Liberal', 5.0: 'Very liberal', 9.0: 'Don't know/Refused (VOL.)'}"
Apr17,ideo,"IDEO. In general, would you describe your political vie","{1.0: 'Very conservative', 2.0: 'Conservative', 3.0: 'Moderate', 4.0: 'Liberal', 5.0: 'Very liberal', 9.0: 'Don't know/Refused (VOL.)'}"
Typology17,ideo,"IDEO. In general, would you describe your political vie","{1.0: 'Very conservative', 2.0: 'Conservative', 3.0: 'Moderate', 4.0: 'Liberal', 5.0: 'Very liberal', 9.0: 'Don't know/Refused (VOL.)'}"
Jan18,ideo,"IDEO. In general, would you describe your political vie","{1.0: 'Very conservative', 2.0: 'Conservative', 3.0: 'Moderate', 4.0: 'Liberal [OR]', 5.0: 'Very liberal', 9.0: '(VOL) Don't know/Refused'}"
Mar18,ideo,"In general, would you describe your political views as.","{1.0: 'Very conservative', 2.0: 'Conservative', 3.0: 'Moderate', 4.0: 'Liberal [OR]', 5.0: 'Very liberal', 9.0: '[VOL. DO NOT READ] Don''t kn'}"
May18,ideo,"IDEO. In general, would you describe your political vie","{1.0: 'Very conservative', 2.0: 'Conservative', 3.0: 'Moderate', 4.0: 'Liberal [OR]', 5.0: 'Very liberal', 9.0: '(VOL) Don't know/Refused'}"
Jun18,ideo,"IDEO. In general, would you describe your political vie","{1.0: 'Very conservative', 2.0: 'Conservative', 3.0: 'Moderate', 4.0: 'Liberal [OR]', 5.0: 'Very liberal', 9.0: '(VOL) Don't know/Refused'}"
W161,F_IDEO,Ideology,"{1.0: 'Very conservative', 2.0: 'Conservative', 3.0: 'Moderate', 4.0: 'Liberal', 5.0: 'Very liberal', 99.0: 'Refused'}"
W167,F_IDEO,Ideology,"{1.0: 'Very conservative', 2.0: 'Conservative', 3.0: 'Moderate', 4.0: 'Liberal', 5.0: 'Very liberal', 99.0: 'Refused'}"

Codes 1-5 mean the same in all files (very conservative ... very liberal). The DK code differs again: 9 in phone files, 99 in ATP.

**Education.**

In [32]:
find_vars(r"(f_)?educ")

                  variables found
Feb17                       educ2
Apr17                       educ2
Typology17                  educ2
Jan18                        educ
Mar18                        educ
May18                        educ
Jun18                        educ
W161        F_EDUCCAT, F_EDUCCAT2
W167        F_EDUCCAT, F_EDUCCAT2

In [33]:
EDUC_VAR = {w: ("F_EDUCCAT" if w in atp else ("educ" if "educ" in surveys[w].columns else "educ2")) for w in WAVE_ORDER}
show_choice(EDUC_VAR, cut=20)

,variable,question text,codes
wave,,,
Feb17,educ2,EDUC2. What is the highest level of school you have com,"{1.0: 'Less than high schoo', 2.0: 'High school incomple', 3.0: 'High school graduate', 4.0: 'Some college, no deg', 5.0: 'Two year associate d', 6.0: 'Four year college or', 7.0: 'Some postgraduate or', 8.0: 'Postgraduate or prof', 9.0: 'Don't know/Refused ('}"
Apr17,educ2,EDUC2. What is the highest level of school you have com,"{1.0: 'Less than high schoo', 2.0: 'High school incomple', 3.0: 'High school graduate', 4.0: 'Some college, no deg', 5.0: 'Two year associate d', 6.0: 'Four year college or', 7.0: 'Some postgraduate or', 8.0: 'Postgraduate or prof', 9.0: 'Don't know/Refused ('}"
Typology17,educ2,EDUC2. What is the highest level of school you have com,"{1.0: 'Less than high schoo', 2.0: 'High school incomple', 3.0: 'High school graduate', 4.0: 'Some college, no deg', 5.0: 'Two year associate d', 6.0: 'Four year college or', 7.0: 'Some postgraduate or', 8.0: 'Postgraduate or prof', 9.0: 'Don't know/Refused'}"
Jan18,educ,EDUC. What is the highest level of school you have comp,"{1.0: 'Less than high schoo', 2.0: 'High school incomple', 3.0: 'High school graduate', 4.0: 'Some college, no deg', 5.0: 'Two year associate d', 6.0: 'Four year college or', 7.0: 'Some postgraduate or', 8.0: 'Postgraduate or prof', 9.0: '(VOL) Don't know/Ref'}"
Mar18,educ,What is the highest level of school you have completed,"{1.0: 'Less than high schoo', 2.0: 'High school incomple', 3.0: 'High school graduate', 4.0: 'Some college, no deg', 5.0: 'Two year associate d', 6.0: 'Four year college or', 7.0: 'Some postgraduate or', 8.0: 'Postgraduate or prof', 9.0: 'Don''t know/Refused '}"
May18,educ,EDUC. What is the highest level of school you have comp,"{1.0: 'Less than high schoo', 2.0: 'High school incomple', 3.0: 'High school graduate', 4.0: 'Some college, no deg', 5.0: 'Two year associate d', 6.0: 'Four year college or', 7.0: 'Some postgraduate or', 8.0: 'Postgraduate or prof', 9.0: '(VOL) Don't know/Ref'}"
Jun18,educ,EDUC. What is the highest level of school you have comp,"{1.0: 'Less than high schoo', 2.0: 'High school incomple', 3.0: 'High school graduate', 4.0: 'Some college, no deg', 5.0: 'Two year associate d', 6.0: 'Four year college or', 7.0: 'Some postgraduate or', 8.0: 'Postgraduate or prof', 9.0: '(VOL) Don't know/Ref'}"
W161,F_EDUCCAT,Education level category,"{1.0: 'College graduate+', 2.0: 'Some College', 3.0: 'H.S. graduate or les', 99.0: 'Refused'}"
W167,F_EDUCCAT,Education level category,"{1.0: 'College graduate+', 2.0: 'Some College', 3.0: 'H.S. graduate or les', 99.0: 'Refused'}"

Phone files have 8 education levels (in the variable `educ`, or `educ2` in the 2017 files), ATP has only 3 groups (`F_EDUCCAT`). To compare them we will have to collapse the 8 levels into the same 3 groups.

**Age and gender.**

In [34]:
print("Age variables:")
display(find_vars(r"(f_)?age"))
print("Gender variables:")
display(find_vars(r"(sex|f_gender)"))
print("Phone age (Apr17), exact number:", surveys["Apr17"]["age"].describe().round(1).to_dict())
print("ATP age (W161), categories only:", vlabels("W161", "F_AGECAT"))
print("Phone gender:", vlabels("Apr17", "sex"))
print("ATP gender:  ", vlabels("W161", "F_GENDER"))

Age variables:

           variables found
Feb17                  age
Apr17                  age
Typology17             age
Jan18                  age
Mar18                  age
May18                  age
Jun18                  age
W161              F_AGECAT
W167              F_AGECAT

Gender variables:

           variables found
Feb17                  sex
Apr17                  sex
Typology17             sex
Jan18                  sex
Mar18                  sex
May18                  sex
Jun18                  sex
W161              F_GENDER
W167              F_GENDER

Phone age (Apr17), exact number: {'count': 1501.0, 'mean': 50.5, 'std': 18.8, 'min': 18.0, '25%': 34.0, '50%': 52.0, '75%': 65.0, 'max': 99.0}
ATP age (W161), categories only: {1.0: '18-29', 2.0: '30-49', 3.0: '50-64', 4.0: '65+', 99.0: 'Refused'}
Phone gender: {1.0: 'Male', 2.0: 'Female'}
ATP gender:   {1.0: 'A man', 2.0: 'A woman', 3.0: 'In some other way', 99.0: 'Refused'}

Phone files have exact age, ATP only age categories (18-29, 30-49, 50-64, 65+), so exact age will have to be converted into the same groups. Gender has one extra category in ATP ("in some other way").

In [35]:
AGE_VAR = {w: ("F_AGECAT" if w in atp else "age") for w in WAVE_ORDER}
GENDER_VAR = {w: ("F_GENDER" if w in atp else "sex") for w in WAVE_ORDER}

## 11. Survey mode

How were people interviewed? Phone files have a sample type variable (`sample`, or `samptype` in March18), ATP has `SVYMODE`:

In [36]:
MODE_VAR = {}
rows = []
for w in WAVE_ORDER:
    var = [c for c in ["sample", "samptype", f"SVYMODE_{w}"] if c in surveys[w].columns][0]
    MODE_VAR[w] = var
    counts = surveys[w][var].map(vlabels(w, var)).value_counts().to_dict()
    rows.append({"wave": w, "variable": var, "n": len(surveys[w]), "breakdown": counts})
pd.DataFrame(rows).set_index("wave")

                variable     n                              breakdown
wave
Feb17             sample  1503        {'Cell': 1126, 'Landline': 377}
Apr17             sample  1501        {'Cell': 1126, 'Landline': 375}
Typology17        sample  5009       {'Cell': 3754, 'Landline': 1255}
Jan18             sample  1503  {'Cell phone': 1127, 'Landline': 376}
Mar18           samptype  1466  {'Cell Phone': 1082, 'Landline': 384}
May18             sample  1503  {'Cell phone': 1127, 'Landline': 376}
Jun18             sample  2002  {'Cell phone': 1500, 'Landline': 502}
W161        SVYMODE_W161  5086             {'Web': 4893, 'CATI': 193}
W167        SVYMODE_W167  3589             {'Web': 3465, 'CATI': 124}

For the 2017–2018 surveys, all respondents were interviewed by telephone, although the raw files distinguish landline and cell-phone samples. Since we only need a broad collection-method indicator, the combined dataset stores these waves as phone_rdd. For ATP waves, where respondents may answer either online or by phone, we retain SVYMODE.

## 12. A draft crosswalk and what the merging code will need to do

Everything we chose above can be collected into one table: for every wave, which raw variable plays which role

In [37]:
crosswalk = pd.DataFrame({
    "id": ID_VAR, "approval": APPROVAL_VAR, "strength": STRENGTH_VAR, "weight": WEIGHT_VAR,
    "date": DATE_VAR, "date format": DATE_FMT, "party": PARTY_VAR, "ideology": IDEO_VAR,
    "education": EDUC_VAR, "age": AGE_VAR, "gender": GENDER_VAR, "mode": MODE_VAR,
})
crosswalk.index.name = "wave"
crosswalk

,id,approval,strength,weight,date,date format,party,ideology,education,age,gender,mode
wave,,,,,,,,,,,,
Feb17,psraid,q1,q1a,weight,int_date,mddyy,partysum,ideo,educ2,age,sex,sample
Apr17,psraid,q1,q1a,weight,int_date,mddyy,partysum,ideo,educ2,age,sex,sample
Typology17,mergeid,qa1,qa1a,weight,int_date,mddyy,partysum,ideo,educ2,age,sex,sample
Jan18,respid,q2,q2a,weight,int_date,yymmdd,partysum,ideo,educ,age,sex,sample
Mar18,masterid,q2,None,weight,ftcalldt,date,partysum,ideo,educ,age,sex,samptype
May18,respid,q2,q2a,weight,int_date,yymmdd,partysum,ideo,educ,age,sex,sample
Jun18,respid,q2,None,weight,int_date,yymmdd,partysum,ideo,educ,age,sex,sample
W161,QKEY,POL1DT_W161,POL1DTSTR_W161,WEIGHT_W161,INTERVIEW_START_W161,atp,F_PARTYSUM_FINAL,F_IDEO,F_EDUCCAT,F_AGECAT,F_GENDER,SVYMODE_W161
W167,QKEY,POL1DT_W167,POL1DTSTR_W167,WEIGHT_W167,INTERVIEW_START_W167,atp,F_PARTYSUM_FINAL,F_IDEO,F_EDUCCAT,F_AGECAT,F_GENDER,SVYMODE_W167

The same 4 columns from every file, side by side (first 3 rows), show why the crosswalk is needed. Same content, different names and codes:

In [38]:
for w in WAVE_ORDER:
    print("===", w)
    display(surveys[w][[APPROVAL_VAR[w], WEIGHT_VAR[w], DATE_VAR[w], PARTY_VAR[w]]].head(3))

=== Feb17

    q1    weight  int_date  partysum
0  2.0  1.733333   21017.0       2.0
1  2.0  1.500000   21217.0       2.0
2  2.0  1.533333   21217.0       2.0

=== Apr17

    q1    weight  int_date  partysum
0  2.0  2.941176   40517.0       2.0
1  1.0  1.323529   40517.0       1.0
2  2.0  1.235294   40517.0       2.0

=== Typology17

   qa1    weight  int_date  partysum
0  2.0  1.064516   61417.0       2.0
1  1.0  4.000000   60817.0       1.0
2  1.0  1.612903   60817.0       1.0

=== Jan18

    q2    weight  int_date  partysum
0  1.0  0.925009  180110.0       1.0
1  1.0  0.857769  180110.0       1.0
2  1.0  0.953144  180110.0       1.0

=== Mar18

    q2    weight    ftcalldt  partysum
0  2.0  0.351682  2018-03-08       1.0
1  2.0  1.546664  2018-03-12       2.0
2  1.0  0.959834  2018-03-08       1.0

=== May18

    q2    weight  int_date  partysum
0  2.0  0.876752  180425.0       2.0
1  2.0  0.706449  180425.0       2.0
2  2.0  0.336219  180425.0       2.0

=== Jun18

    q2    weight  int_date  partysum
0  2.0  0.581332  180605.0       2.0
1  9.0  1.559586  180605.0       1.0
2  2.0  2.428216  180605.0       1.0

=== W161

   POL1DT_W161  WEIGHT_W161  INTERVIEW_START_W161  F_PARTYSUM_FINAL
0          1.0     1.046094  28-Jan-2025 21:38:38               1.0
1          1.0     0.992757  29-Jan-2025 12:54:51               1.0
2          2.0     1.196266  28-Jan-2025 16:24:57               2.0

=== W167

   POL1DT_W167  WEIGHT_W167  INTERVIEW_START_W167  F_PARTYSUM_FINAL
0          2.0     1.135669  08-Apr-2025 15:12:07               2.0
1          1.0     1.169792  08-Apr-2025 14:50:19               1.0
2          1.0     1.110668  08-Apr-2025 17:06:04               1.0

### Why only these columns?

Every file has 108-178 columns, and we keep 10 or 11 of them (10 in Mar18 and Jun18, which have no "how strongly" follow-up).

In [39]:
roles = {"id": ID_VAR, "approval": APPROVAL_VAR, "strength": STRENGTH_VAR, "weight": WEIGHT_VAR, "date": DATE_VAR,
         "party": PARTY_VAR, "ideology": IDEO_VAR, "education": EDUC_VAR, "age": AGE_VAR, "gender": GENDER_VAR,
         "mode": MODE_VAR}
role_of = {(w, var): role for role, m in roles.items() for w, var in m.items() if var}
codebook["role"] = [role_of.get((w, v), "") for w, v in zip(codebook["wave"], codebook["variable"])]

kept_summary = codebook.groupby("wave", sort=False).agg(total=("variable", "size"), kept=("role", lambda r: int((r != "").sum())))
kept_summary["dropped"] = kept_summary["total"] - kept_summary["kept"]
kept_summary["% kept"] = (100 * kept_summary["kept"] / kept_summary["total"]).round(1)
kept_summary.T

wave     Feb17  Apr17  Typology17  Jan18  Mar18  May18  Jun18   W161   W167
total    127.0  178.0       163.0  168.0  108.0  123.0  130.0  144.0  170.0
kept      11.0   11.0        11.0   11.0   10.0   11.0   10.0   11.0   11.0
dropped  116.0  167.0       152.0  157.0   98.0  112.0  120.0  133.0  159.0
% kept     8.7    6.2         6.7    6.5    9.3    8.9    7.7    7.6    6.5

The kept variables, with their question text (this is the full list of what goes into the merged dataset):

In [40]:
codebook[codebook["role"] != ""][["wave", "role", "variable", "question text"]].set_index("wave")

,role,variable,question text
wave,,,
Feb17,id,psraid,Unique ID
Feb17,mode,sample,Sample type
Feb17,date,int_date,Interview date
Feb17,approval,q1,Q.1 Do you approve or disapprove of the way Donald Trump is handling his job as President? [IF DK ENTER AS DK. IF DEPENDS PROBE ONCE WITH: Overall do you approve or disapprove of the way Donald Trump is handling his job as President?
Feb17,strength,q1a,"Q.1a Do you [approve/disapprove] very strongly, or not so strongly?"
Feb17,gender,sex,SEX. Respondent's sex [DO NOT ASK]
Feb17,age,age,AGE. What is your age?
Feb17,education,educ2,EDUC2. What is the highest level of school you have completed or the highest degree you have received? [DO NOT READ] [INTERVIEWER NOTE: Enter code 3-HS grad if R completed training that did NOT count toward a degree]
Feb17,party,partysum,Leaned party identification
Feb17,ideology,ideo,"IDEO. In general, would you describe your political views as... [READ]"
Feb17,weight,weight,Final Weight
Apr17,id,psraid,Unique ID
Apr17,mode,sample,Sample type
Apr17,date,int_date,Interview date
Apr17,approval,q1,Q.1 Do you approve or disapprove of the way Donald Trump is handling his job as President? [IF DK ENTER AS DK. IF DEPENDS PROBE ONCE WITH: Overall do you approve or disapprove of the way Donald Trump is handling his job as President?
Apr17,strength,q1a,"Q.1a Do you [approve/disapprove] very strongly, or not so strongly?"
Apr17,gender,sex,SEX. Respondent's sex [DO NOT ASK]
Apr17,age,age,AGE. What is your age?
Apr17,education,educ2,EDUC2. What is the highest level of school you have completed or the highest degree you have received? [DO NOT READ] [INTERVIEWER NOTE: Enter code 3-HS grad if R completed training that did NOT count toward a degree]
Apr17,party,partysum,Leaned party identification
Apr17,ideology,ideo,"IDEO. In general, would you describe your political views as... [READ]"
Apr17,weight,weight,Final Weight
Typology17,id,mergeid,Unique ID after merge
Typology17,mode,sample,Sample type
Typology17,date,int_date,Interview date
Typology17,approval,qa1,Q.A1 Do you approve or disapprove of the way Donald Trump is handling his job as President? [IF DK ENTER AS DK. IF DEPENDS PROBE ONCE WITH: Overall do you approve or disapprove of the way Donald Trump is handling his job as President?...
Typology17,strength,qa1a,"Q.A1a Do you [approve/disapprove] very strongly, or not so strongly?"
Typology17,gender,sex,SEX. Respondent's sex [DO NOT ASK]
Typology17,age,age,AGE. What is your age?
Typology17,education,educ2,EDUC2. What is the highest level of school you have completed or the highest degree you have received? [DO NOT READ] [INTERVIEWER NOTE: Enter code 3-HS grad if R completed training that did NOT count toward a degree]
Typology17,party,partysum,Leaned party identification
Typology17,ideology,ideo,"IDEO. In general, would you describe your political views as... [READ]"
Typology17,weight,weight,Final combined weight
Jan18,id,respid,Individual unique respondent identification number
Jan18,mode,sample,Sample type
Jan18,date,int_date,"Interview date (NOTE: Final interviewer date, adjusted for interviews that are done early in the AM)"
Jan18,approval,q2,Q.2. Do you approve or disapprove of the way Donald Trump is handling his job as President?
Jan18,strength,q2a,"Q.2a. Do you [approve/disapprove] very strongly, or not so strongly?"
Jan18,gender,sex,SEX. [ENTER RESPONDENT'S SEX:]
Jan18,age,age,AGE. What is your age? [YEARS]
Jan18,education,educ,EDUC. What is the highest level of school you have completed or the highest degree you have received?
Jan18,party,partysum,Leaned party identification
Jan18,ideology,ideo,"IDEO. In general, would you describe your political views as..."
Jan18,weight,weight,Final weight
Mar18,id,masterid,Imported from sample file: Unique Respondent ID
Mar18,mode,samptype,Sample type
Mar18,date,ftcalldt,Date of first call attempt
Mar18,approval,q2,Do you approve or disapprove of the way Donald Trump is handling his job as President? [IF DK ENTER AS DK. IF DEPENDS PROBE ONCE WITH: Overall do you approve or disapprove of the way Donald Trump is handling his job as President?
Mar18,gender,sex,[ENTER RESPONDENT'S SEX:]
Mar18,age,age,What is your age? years
Mar18,education,educ,What is the highest level of school you have completed or the highest degree you have received? [DO NOT READ] [INTERVIEWER NOTE: Enter code 3-HS grad if R completed training that did NOT count toward a degree]
Mar18,party,partysum,Leaned party identification
Mar18,ideology,ideo,"In general, would you describe your political views as... [READ]"
Mar18,weight,weight,Final weight
May18,id,respid,Individual unique respondent identification number
May18,mode,sample,Sample type
May18,date,int_date,"Interview date (NOTE: Final interviewer date, adjusted for interviews that are done early in the AM)"
May18,approval,q2,Q.2. Do you approve or disapprove of the way Donald Trump is handling his job as President?
May18,strength,q2a,"Q.2a. Do you [approve/disapprove] very strongly, or not so strongly?"
May18,gender,sex,SEX. [ENTER RESPONDENT'S SEX:]
May18,age,age,AGE. What is your age? [YEARS]
May18,education,educ,EDUC. What is the highest level of school you have completed or the highest degree you have received? [----DO NOT READ----] [INTERVIEWER NOTE: Enter code 3-HS grad if R completed training that did NOT count toward a degree]
May18,party,partysum,Leaned party identification
May18,ideology,ideo,"IDEO. In general, would you describe your political views as... [READ]"
May18,weight,weight,Final weight
Jun18,id,respid,Individual unique respondent identification number
Jun18,mode,sample,Sample type
Jun18,date,int_date,"Interview date (NOTE: Final interviewer date, adjusted for interviews that are done early in the AM)"
Jun18,approval,q2,Q.2. Do you approve or disapprove of the way Donald Trump is handling his job as President?
Jun18,gender,sex,SEX. [ENTER RESPONDENT'S SEX:]
Jun18,age,age,AGE. What is your age? [YEARS]
Jun18,education,educ,EDUC. What is the highest level of school you have completed or the highest degree you have received? [INTERVIEWER NOTE: Enter code 3-HS grad if R completed training that did NOT count toward a degree]
Jun18,party,partysum,Leaned party identification
Jun18,ideology,ideo,"IDEO. In general, would you describe your political views as... [READ]"
Jun18,weight,weight,Final weight
W161,id,QKEY,QKEY_W161. Unique identifier
W161,date,INTERVIEW_START_W161,INTERVIEW_START_W161. Interview start time
W161,mode,SVYMODE_W161,SVYMODE_W161. Mode of survey
W161,approval,POL1DT_W161,POL1DT_W161. Do you approve or disapprove of the way Donald Trump is handling his job as president?
W161,strength,POL1DTSTR_W161,POL1DTSTR_W161. Do you approve/disapprove of the way Donald Trump is handling his job as president...
W161,age,F_AGECAT,Age category
W161,gender,F_GENDER,Gender
W161,education,F_EDUCCAT,Education level category
W161,party,F_PARTYSUM_FINAL,Party summary
W161,ideology,F_IDEO,Ideology
W161,weight,WEIGHT_W161,Wave 161 weight
W167,id,QKEY,QKEY_W167. QKEY. Unique identifier
W167,date,INTERVIEW_START_W167,INTERVIEW_START_W167. Interview start time
W167,mode,SVYMODE_W167,SVYMODE_W167. Mode of survey
W167,approval,POL1DT_W167,POL1DT_W167. Do you approve or disapprove of the way Donald Trump is handling his job as president?
W167,strength,POL1DTSTR_W167,POL1DTSTR_W167. Do you approve/disapprove of the way Donald Trump is handling his job as president...
W167,age,F_AGECAT,Age category
W167,gender,F_GENDER,Gender
W167,education,F_EDUCCAT,Education level category
W167,party,F_PARTYSUM_FINAL,Party summary
W167,ideology,F_IDEO,Ideology
W167,weight,WEIGHT_W167,Wave 167 weight

**Why not all the other columns?**

In [41]:
codebook["name"] = codebook["variable"].str.lower()
waves_per_name = codebook.groupby("name")["wave"].nunique()

print("Different column names in all files together:", len(waves_per_name))
print("Names that exist in only ONE file:", int((waves_per_name == 1).sum()))
print("Names that exist in 2 or more files:", int((waves_per_name >= 2).sum()))
print("Names that exist in 5 or more files:", int((waves_per_name >= 5).sum()))

Different column names in all files together: 888
Names that exist in only ONE file: 716
Names that exist in 2 or more files: 172
Names that exist in 5 or more files: 46

 888
Names that exist in only ONE file: 716
Names that exist in 2 or more files: 172
Names that exist in 5 or more files: 46

Most columns exist in only one file. They are questions on topics that were asked in one survey only (tax law, tariffs, specific news events...), so they cannot be compared across waves. 

The columns that do repeat in many files are these:

In [42]:
shared = waves_per_name[waves_per_name >= 5].sort_values(ascending=False)
first_text = codebook.drop_duplicates("name").set_index("name")["question text"]
pd.DataFrame({"in how many files": shared, "question text (in the first file that has it)": first_text[shared.index].str[:90]})

,in how many files,question text (in the first file that has it)
name,,
age,7,AGE. What is your age?
attend,7,"ATTEND. Aside from weddings and funerals, how often do you attend religious services... mo"
born,7,"BORN. Would you describe yourself as a 'born again' or evangelical Christian, or not?"
birth_hisp,7,"BIRTH_HISP. Were you born in the United States, on the island of Puerto Rico, or in anothe"
cp,7,Resp has a cell phone
chr,7,CHR. Do you think of yourself as a Christian or not? [IF R NAMED A NON-CHRISTIAN RELIGION
hh3,7,"HH3. How many, including yourself, are adults, age 18 and older?"
hh1,7,"HH1. How many people, including yourself, live in your household?"
cregion,7,Final Census Region after zip/fips merges
density,7,Final Density code after zip/fips merges
ilang,7,Language of interview
igender,7,Interviewer gender
ideo,7,"IDEO. In general, would you describe your political views as... [READ]"
hisp,7,"HISP. Are you of Hispanic, Latino, or Spanish origin, such as Mexican, Puerto Rican or Cub"
weight,7,Final Weight
susr,7,Community type - sample
sex,7,SEX. Respondent's sex [DO NOT ASK]
scregion,7,Census region - sample
income,7,"INCOME. Last year, that is in 2015, what was your total family income from all sources, be"
ll,7,Resp has a landline
partyideo,7,Party and Ideology
party,7,"PARTY. In politics TODAY, do you consider yourself a Republican, Democrat, or independent?"
partyln,7,PARTYLN. As of today do you lean more to the Republican Party or more to the Democratic Pa
partysum,7,Leaned party identification
sstate,7,State from FIPS - sample
state,7,Final State code after zip/fips merges
usr,7,Community type
racethn,7,Race/Ethnicity
relig,7,"RELIG. What is your present religion, if any? Are you Protestant, Roman Catholic, Mormon,"
reg,7,REG. Which of these statements best describes you? [READ IN ORDER] [INSTRUCTION: BE SURE T
qs1,6,"S1. Are you under 18 years old, OR are you 18 or older?"
fcall,6,Date of first call to number
adults,6,# of adults in HH computed from HH1 and HH3
form,6,Form
int_date,6,Interview date
money2,6,MONEY2. That's the end of the interview. If you would like to be reimbursed for your cell
q2,6,"Q.2 All in all, are you satisfied or dissatisfied with the way things are going in this co"
q1,6,Q.1 Do you approve or disapprove of the way Donald Trump is handling his job as President?
sample,6,Sample type
qc1,6,C1. Now thinking about your telephone use… Is there at least one telephone INSIDE your hom
ql1,6,L1. Now thinking about your telephone use… Do you have a working cell phone?
ql1a,6,L1a. Does anyone in your household have a working cell phone?
refusal,6,Refusal Conversion
cellweight,5,Weight for cell sample
q82,5,"Q.82 How concerned, if at all, are you about extremism in the name of Islam in the U.S.? A"
racecmb,5,Combining Race

The columns that repeat are mostly **technical or screening**  or **basic demographics** 

So we keep only what we needs:
1. **Trump job approval** and its "how strongly" follow-up: the measure we want to follow over time.
2. **Weight, date and ID**: to compute weighted shares per wave and know when the interview took place.
3. **Party, ideology, education, age, gender**: to compare groups of people
4. **Survey mode**: because phone and online panel results are not fully comparable.

Everything else is either a one-off question about a specific topic or a fieldwork detail. If later we need more, we add them.